In [ ]:
! python --version

Python 3.10.12

# init
NOTE:
- This was tested with python version 3.12.2 on Mac Sonoma 14.1. Needed to import a downgraded version of numpy to support downgraded version of wandb.
- This was tested with python version 3.10.11 on Windows 11.

In [ ]:
! pip install transformers==4.36.2
! pip install wandb==0.17.1
! pip install accelerate==0.31.0
! pip install rouge_score==0.1.2
! pip install sacrebleu==2.4.2
! pip install sentencepiece==0.1.99
! pip install evaluate==0.4.3
! pip install nltk==3.8.1
! pip install jiwer==3.0.4
! pip install numpy==1.26.4

Requirement already satisfied: transformers==4.36.2 in /usr/local/lib/python3.10/dist-packages (4.36.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (0.26.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (0.15.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (2024.8.30)
Requirement already satisfied: wandb==0.17.1 in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,<6,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (4.25.5)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (2.32.3)
Requirement already satisfied: sentry-sdk>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (2.19.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (1.3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb==0.17.1) (75.1.0)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb==0.17.1) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb==0.17.1) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb==0.17.1) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb==0.17.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb==0.17.1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb==0.17.1) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb==0.17.1) (5.0.1)
Requirement already satisfied: accelerate==0.31.0 in /usr/local/lib/python3.10/dist-packages (0.31.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (0.26.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.31.0) (0.4.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.31.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.10.0->accelerate==0.31.0) (1.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.31.0) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.31.0) (4.66.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.31.0) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.31.0) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.31.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.31.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.31.0) (2024.8.30)
Requirement already satisfied: rouge_score==0.1.2 in /usr/local/lib/python3.10/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score==0.1.2) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge_score==0.1.2) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge_score==0.1.2) (1.26.4)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score==0.1.2) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score==0.1.2) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score==0.1.2) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score==0.1.2) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score==0.1.2) (4.66.6)
Requirement already satisfied: sacrebleu==2.4.2 in /usr/local/lib/python3.10/dist-packages (2.4.2)
Requirement already satisfied: portalocker in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (3.0.0)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (2024.9.11)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (1.26.4)
Requirement already satisfied: colorama in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from sacrebleu==2.4.2) (5.3.0)
Requirement already satisfied: sentencepiece==0.1.99 in /usr/local/lib/python3.10/dist-packages (0.1.99)
Requirement already satisfied: evaluate==0.4.3 in /usr/local/lib/python3.10/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (3.1.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (4.66.6)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate==0.4.3) (2024.9.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (0.26.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate==0.4.3) (3.16.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate==0.4.3) (17.0.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate==0.4.3) (3.11.9)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate==0.4.3) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate==0.4.3) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate==0.4.3) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate==0.4.3) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate==0.4.3) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate==0.4.3) (2024.8.30)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate==0.4.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate==0.4.3) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate==0.4.3) (2024.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.3.1)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate==0.4.3) (1.16.0)
Requirement already satisfied: nltk==3.8.1 in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1) (4.66.6)
Requirement already satisfied: jiwer==3.0.4 in /usr/local/lib/python3.10/dist-packages (3.0.4)
Requirement already satisfied: click<9.0.0,>=8.1.3 in /usr/local/lib/python3.10/dist-packages (from jiwer==3.0.4) (8.1.7)
Requirement already satisfied: rapidfuzz<4,>=3 in /usr/local/lib/python3.10/dist-packages (from jiwer==3.0.4) (3.10.1)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.10/dist-packages (1.26.4)

In [ ]:
from google.colab import drive
import sys
drive.mount('/content/drive')
sys.path.append('./drive/MyDrive/Colab Notebooks/vr-txt-corr/')

import numpy as np
import pandas as pd
import torch
import correction_palette as palette
from transformers import T5TokenizerFast, T5ForConditionalGeneration, Seq2SeqTrainingArguments
from correction_palette import *
from cursor_t5_modeling import CursorT5ForConditionalGeneration
import evaluate
import os
import copy

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(

Using CUDA

In [ ]:
if torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
    print("Using MPS")
elif torch.cuda.is_available():
    gpu_id = 0

    num_gpus = torch.cuda.device_count()
    print(f"Number of GPUs available: {num_gpus}")
    for i in range(num_gpus):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
    device = torch.device(gpu_id)
    print(f"Using CUDA with {torch.cuda.get_device_name(i)}")
else:
    device = torch.device("cpu")
    print("Using CPU")

Number of GPUs available: 1
GPU 0: NVIDIA L4
Using CUDA with NVIDIA L4

# Configure stuffs

In [ ]:
save_dir = './drive/MyDrive/Colab Notebooks/vr-txt-corr/'  # save directory for pretty much anything that is saved by this program (models, tokenizers, logs, etc.)
models_dir = f'{save_dir}saved_models/'
data_dir = f'{save_dir}corr_datasets_experimental/DELETION-INSERTION-MULTIPLE-REPLACEMENT-SINGLE/'

base_model_name = 'google/flan-t5-base'

NUM_SAVES = 2

PORTION = 1 # proportion ofdatasets to use (note: applies to each split)

random_seed = 42
palette.MAX_SOURCE_TOKENS = 512
palette.MAX_NEW_TOKENS = 512
palette.CURSOR_TOKEN = '<|>'
palette.TEXT_SEP_TOKEN = '<||>'
custom_special_tokens_dict = {'additional_special_tokens': [palette.CURSOR_TOKEN, palette.TEXT_SEP_TOKEN]}

gen_kwargs_override = {'num_beams': 24, 'max_new_tokens': palette.MAX_NEW_TOKENS, 'early_stopping': True, 'num_return_sequences': 24}  # these values might be changed in 'Sweep Configuration'

# Computing Metrics

In [ ]:
import difflib
import re


def prefix_key(k: str, prefix: str, sep: str) -> str:
    return f'{prefix}{sep}{k}'

def get_unique_words(text):
    #words = set(text.replace('_', ' ').replace(',', ' ').replace(':', ' ').replace(';', ' ').replace('.', ' ').replace('?', ' ').replace('(', ' ').split().split())
    list_words = re.split(',|\ |_|-|!|\+|\.|\\|\*|\?|\[|\^|\]|\$|\(|\)|\{|\}|\=|\||\:', text)
    words = set(list_words)
    if '' in words:
        words.remove('')
    return words

def get_split_index(split_list,index):
    start_index = 0
    end_index = 0
    for i in range(0,index+1):
        if i == 0:
            start_index = 0
            end_index = len(split_list[i])
        else:
            start_index+=len(split_list[i-1])+1
            end_index= start_index+len(split_list[i])
    return start_index,end_index

def get_diff_start_end(original,new):

    original = ' '+original
    new = ' ' +new
    s1 = original.split(' ')
    s2 = new.split(' ')
    matcher = difflib.SequenceMatcher(a=s1, b=s2)
    #print("Matching Sequences:")
    '''
    a_last_end = 0
    count = 0
    for match in matcher.get_matching_blocks():
        #print("Match             : {}".format(match))
        #print("Matching Sequence : {}".format(s1[match.a:match.a+match.size]))
        #print(match.a,match.a+match.size)
        if count>0:
            if match.a-a_last_end>0:
                #print("missmatch",a_last_end,match.a)
                #print("Miss_matching Sequence : {}".format(s1[a_last_end:match.a]))
                start,e = get_split_index(s1,a_last_end)
                s,end = get_split_index(s1,match.a-1)
                print("mismatch start end:",start,end)
                print("***miss match segment:", string1[start:end])


        count+=1
        a_last_end=match.a+match.size
    '''
    b_last_end = 0
    count = 0
    start_list = []
    end_list = []
    for match in matcher.get_matching_blocks():
        #print("Match             : {}".format(match))
        #print("Matching Sequence : {}".format(s2[match.b:match.b+match.size]))
        #print(match.b,match.b+match.size)
        if count>0:
            if match.b-b_last_end>0:
                #print("missmatch",b_last_end,match.b)
                #print("Miss_matching Sequence : {}".format(s2[b_last_end:match.b]))
                start,_ = get_split_index(s2,b_last_end)
                _,end = get_split_index(s2,match.b-1)
                start_list.append(start-1)
                end_list.append(end-1)

                #print("mismatch start end:",start,end)
                #print("***miss match segment:", new[start:end])
        count+=1
        b_last_end=match.b+match.size

    return start_list, end_list

def filter_corrections(response, sentence_without_marker,data):
    filtered_corrections = []
    filtered_orig_idx = []
    diff_start_list = []
    diff_end_list = []
    for filter_idx in range(len(response['corrections'])):
        origitem = response['corrections'][filter_idx]

        item = origitem.strip(" ")

        if item == sentence_without_marker:
            continue
        if item in filtered_corrections:
            continue

        item_words = get_unique_words(item.lower());
        original_and_input_words = get_unique_words(sentence_without_marker.lower()+" "+data['part'].lower())
        #print("item_words",item_words)
        #print("original_and_input_words",original_and_input_words)
        if not item_words.issubset(original_and_input_words):
            continue

        if data['part'].lower() not in item.lower():
            continue

        # and (response['correction probabilities'][filter_idx]>0):
        if len((data['part']+" "+sentence_without_marker).split()) < len(item.split()):
            continue

        filtered_corrections.append(origitem)
        filtered_orig_idx.append(filter_idx)

        (start_list, end_list) = get_diff_start_end(sentence_without_marker,item)
        diff_start_list.append(start_list)
        diff_end_list.append(end_list)
        '''
        if (response['correction probabilities'][filter_idx]>0.7):
            break
        else:
            print("prob <0.7")
            print(response['correction probabilities'][filter_idx], item)
        '''

    return filtered_corrections, filtered_orig_idx, diff_start_list, diff_end_list

def F1_score(ground_truth, result_list):
    num_of_results = float(len(result_list))
    recall = 0
    precision = 0
    if ground_truth in result_list:
        recall = 1
        precision = 1.0/num_of_results;
    else:
        recall = 0
        precision = 0

    F1 = 2*recall*precision/(recall+precision+0.00000000001)
    return F1,recall,precision

f1,recall,precision = F1_score('how are you',[])
print('recall',recall)
print("precision",precision)
print("F1",f1)


string1 ="It is not warm. It is summer."
string2 ="It is very warm. It is winter."
get_diff_start_end(string1,string2)

recall 0
precision 0
F1 0.0

([6, 23], [10, 30])

In [ ]:
def filter_invalid_samples(_label_str, _input_strs, _beam_str, _best_beam_str):
    label_str = []
    input_strs = []
    best_beam_str = []
    beam_str = []
    for i in range(len(_label_str)):
        e_sentence, phrase, edits, edits_made = _input_strs[i]
        e_sentence, phrase = tokenizer.decode(tokenizer(e_sentence)['input_ids'], skip_special_tokens=True), tokenizer.decode(tokenizer(phrase)['input_ids'], skip_special_tokens=True)
        label = _label_str[i]
        if label == e_sentence:
            continue

        beam_group = _beam_str[i]
        label = label

        d_response = {'corrections': beam_group}
        d_data = {'part': phrase}

        pred_slice_before = beam_group[:5]
        num_correct_before = label in pred_slice_before
        filter_output = filter_corrections(d_response, e_sentence, d_data)

        pred_slice_after = filter_output[0][:5]
        num_correct_after = label in pred_slice_after
        if num_correct_after < num_correct_before:
            print(num_correct_before)
            print(num_correct_after)
            print(f'skipped (sent: |{e_sentence}|, phra: |{phrase}|)')
            print(f"cbefo: |{pred_slice_before[0]}|")
            print(f"cafte: |{pred_slice_after}|")
            print(f"label: |{label}|")
            continue

        label_str.append(label)
        input_strs.append((e_sentence, phrase, edits, edits_made))
        best_beam_str.append(_best_beam_str[i])
        beam_str.append(_beam_str[i])
    return label_str, input_strs, best_beam_str, beam_str

# filter beams based on criterion. save filtered_ids so that we can simulate slicing the top n beams and then filtering without recomputing/refiltering.
def filter_beams(label_str, input_strs, beam_str, best_beam_str):
    filtered_ids = []

    #print(f'beam_str: {np.array(beam_str).shape}')
    #print(f'label_str: {np.array(label_str).shape}')
    #print(f'input_strs: {np.array(input_strs).shape}')
    #print(f'input_strs: {input_strs}')
    for i in range(len(beam_str)): # filter invalid beams
        beam_group = beam_str[i]
        label = label_str[i]
        sentence, phrase, _, _= input_strs[i]

        d_response = {'corrections': beam_group}
        d_data = {'part': phrase}

        pred_slice_before = beam_group[:5]
        num_correct_before = label in pred_slice_before
        filter_output = filter_corrections(d_response, sentence, d_data)
        beam_str[i] = filter_output[0]
        if len(beam_str[i]) > 0:
            best_beam_str[i] = beam_str[i][0]
        filtered_ids.append(filter_output[1])
        pred_slice_after = beam_str[i][:5]
        num_correct_after = label in pred_slice_after
        if num_correct_after < num_correct_before:
            print(f'impossible')
    return filtered_ids, beam_str, best_beam_str

# computing f1, precision, and recall
def compute_fpr(_beam_str, label_str, filtered_ids, prefix: str = 'n_samp'):
    beam_str = copy.deepcopy(_beam_str)
    n_metrics = dict()
    n_table = []
    for j in range(24, 0, -1): # iterate over possible num_samples (to obtain n_metrics)
        f1_sum = 0
        recall_sum = 0
        precision_sum = 0

        for i in range(len(beam_str)):
            if filtered_ids is not None:
                while len(beam_str[i]) > 0 and filtered_ids[i][len(beam_str[i]) - 1] >= j:
                    # remove from end based on filtered_ids because filtered_ids represents the original indices of the beams.
                    # this way, we don't have to keep re-slicing the top n beams and re-filtering
                    beam_str[i].pop()

            metric_output = F1_score(label_str[i], beam_str[i])
            f1_sum += metric_output[0]
            recall_sum += metric_output[1]
            precision_sum += metric_output[2]
            if filtered_ids is None:
                beam_str[i].pop()

        f1 = f1_sum / len(beam_str)
        recall = recall_sum / len(beam_str)
        precision = precision_sum / len(beam_str)

        n_table.append({'n': j, 'f1': f1, 'recall': recall, 'precision': precision})

        n_metrics[f'n{j}/f1'] = f1
        n_metrics[f'n{j}/recall'] = recall
        n_metrics[f'n{j}/precision'] = precision

    n_metrics = {prefix_key(k, prefix,'/'): v for k, v in n_metrics.items()}

    # display tables
    n_table = pd.DataFrame(n_table).iloc[::-1].reset_index(drop=True)
    return n_metrics, n_table

In [ ]:
import os
import pandas as pd

def log_mismatches(input_texts, predictions, labels):
    """
    Logs mismatched cases where predictions do not match labels.

    Parameters:
    - input_texts (List[str]): The input strings.
    - predictions (List[str]): The predicted strings.
    - labels (List[str]): The label strings.
    """
    global mismatch_file
    mismatches = []

    for input_text, pred, label in zip(input_texts, predictions, labels):
        if pred.strip() != label.strip():
            mismatches.append({
                'input': input_text,
                'prediction': pred,
                'label': label
            })

    if mismatches:
        df = pd.DataFrame(mismatches)
        # Check if the file exists to determine whether to write headers
        if not os.path.isfile(mismatch_file):
            df.to_csv(mismatch_file, index=False)
        else:
            df.to_csv(mismatch_file, mode='a', header=False, index=False)
        print(f"Logged {len(mismatches)} mismatched cases to {mismatch_file}")
    else:
        print("No mismatches found in this batch.")

In [ ]:
topk =[1,3,5]

def flatten_stats(stats, topk):
    """
    Reorganize stats into a more compact DataFrame structure with columns:
    - category (edit_count, extra_word_count, etc.)
    - subcat (numerical value)
    - metric (top1, top3, top5)
    - value (accuracy rate)
    - count (number of matches)
    - total (total samples)
    """
    rows = []
    for category in stats:
        for subcat, data in stats[category].items():
            matches = data['matches']
            total = data['total']
            for i, k in enumerate(topk):
                rate = matches[i]/total if total != 0 else 0
                rows.append({
                    'category': category,
                    'subcat': subcat,
                    'metric': f'top{k}',
                    'accuracy': rate,
                    'matches': int(matches[i]),
                    'total': total
                })
    return pd.DataFrame(rows)

from IPython.display import display, HTML
def save_stats_to_csv(stats_df, model_path, triplet_comb):
    """
    Save statistics DataFrame to a CSV file.

    Args:
        stats_df (pd.DataFrame): DataFrame containing the statistics
        model_path (str): Path to save the model
        triplet_comb (str): Triplet combination identifier
    """
    try:
        stats_file = f'{model_path}/stats_triplets-{triplet_comb}-relax10.csv'
        os.makedirs(os.path.dirname(stats_file), exist_ok=True)
        stats_df.to_csv(stats_file, index=False)
        print(f"Saved detailed statistics to {stats_file}")

    except Exception as e:
        print(f"Warning: Failed to save statistics: {e}")

def display_stats_pivot(stats_df):
    """
    Display statistics in a pivot table format.
    Works in both notebook and standard Python environments.

    Args:
        stats_df (pd.DataFrame): DataFrame containing the statistics
    """
    try:
        # Create pivot table
        pivot_df = stats_df.pivot_table(
            index=['category', 'subcat'],
            columns='metric',
            values=['accuracy', 'matches', 'total'],
            aggfunc='first'
        ).round(4)

        # Try notebook display first, fall back to regular print
        try:
            from IPython.display import display
            display(pivot_df)
        except ImportError:
            print("\nStatistics Summary:")
            print("=" * 80)
            print(pivot_df.to_string())
            print("=" * 80)

    except Exception as e:
        print(f"Warning: Failed to display statistics: {e}")

def display_current_stats(stats_df: pd.DataFrame, processed_count: int):
    """
    Display current statistics using display_stats_pivot function,
    with added sample count information

    Args:
        stats_df (pd.DataFrame): Pre-flattened statistics DataFrame
        processed_count (int): Number of samples processed
    """
    print(f"\nStatistics after processing {processed_count} samples:")
    print("=" * 80)

    # Display stats using existing pivot function
    display_stats_pivot(stats_df)

    print("=" * 80)

def compute_stats(input_info, predictions, labels):

    stats = {
        'edit_count': defaultdict(lambda: {'matches': np.zeros(len(topk)), 'total': 0}),
        'extra_word_count': defaultdict(lambda: {'matches': np.zeros(len(topk)), 'total': 0}),
        'extra_word_added': defaultdict(lambda: {'matches': np.zeros(len(topk)), 'total': 0}),
        'part_word_count': defaultdict(lambda: {'matches': np.zeros(len(topk)), 'total': 0})
    }
    i=0
    for preds, label_str, (_, part, edits, edits_made) in zip(predictions, labels,
                                                    input_info):
        words_in_part = part.split()
        part_word_count = len(words_in_part)
        edits = ast.literal_eval(edits)
        edit_count = len(edits)
        edits_made = ast.literal_eval(edits_made)
        # Sort edits_made based on start position
        edits_made = sorted(edits_made, key=lambda x: x[1][0])
        words_edited = sum(em[1][1]-em[1][0] for em in edits_made)
        min_words_needed = edits_made[-1][1][1]-edits_made[0][1][0]
        if min_words_needed < 0:
            print(f"***min_words_needed < 0: {min_words_needed}, part: {part}, label: {label_str},edits_made: {edits_made}")
        extra_word_count = part_word_count - words_edited
        extra_word_added = part_word_count - min_words_needed
        if extra_word_added < 0:
            print(f"***extra_word_added < 0: {extra_word_added}, part: {part}, label: {label_str}, edits_made: {edits_made}")

        stats['edit_count'][edit_count]['total'] += 1
        stats['extra_word_count'][extra_word_count]['total'] += 1
        stats['extra_word_added'][extra_word_added]['total'] += 1
        stats['part_word_count'][part_word_count]['total'] += 1
        is_match_topk = 0
        for j in range(len(topk)):
            is_match_topk = label_str.strip() in preds[:topk[j]]
            stats['edit_count'][edit_count]['matches'][j] += is_match_topk
            stats['extra_word_count'][extra_word_count]['matches'][j] += is_match_topk
            stats['extra_word_added'][extra_word_added]['matches'][j] += is_match_topk
            stats['part_word_count'][part_word_count]['matches'][j] += is_match_topk

        i +=1
        if i % 500 == 0:
            # Flatten stats before displaying
            current_stats_df = flatten_stats(stats, topk)
            display_current_stats(current_stats_df, i)

    return stats

In [ ]:
from IPython.display import display, HTML

cer = evaluate.load('cer')
tkacc = TopKAccuracy()

def compute_metrics(gen_pred: GenPrediction):
    global triplet_comb
    label_ids = gen_pred.label_ids
    label_ids[label_ids == -100] = tokenizer.pad_token_id
    pred_ids = gen_pred.predictions
    pred_ids[pred_ids == -100] = tokenizer.pad_token_id
    _input_strs = gen_pred.inputs_strs
    _label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)
    for lstr in _label_str:
        lstr = ' '.join([word for word in lstr.split(' ') if word != '|>' and word != '|>.'])

    _pred_str = tokenizer.batch_decode(np.array(pred_ids).reshape(-1, len(pred_ids[0][0])), skip_special_tokens=True)
    _pred_str = np.array(_pred_str, dtype=str)


    _best_beam_str = _pred_str[::gen_kwargs_override['num_return_sequences']].tolist()
    _beam_str = _pred_str.reshape(-1, gen_kwargs_override['num_return_sequences']).tolist()


    label_str, input_strs, best_beam_str, beam_str = filter_invalid_samples(_label_str, _input_strs, _beam_str, _best_beam_str)

    # compute metrics before filtering
    tkacc_metrics_unfiltered = tkacc.compute(predictions=beam_str, references=label_str, k_metrics=[1, 3, 5], strict_k=False)
    cer_metric_unfiltered = {'cer_unfiltered': cer.compute(predictions=best_beam_str, references=label_str)}


    # filter bad results based on filtering criterion. also save filtered_ids to avoid unecessary recomputations.
    filtered_ids, beam_str, best_beam_str = filter_beams(label_str, input_strs, beam_str, best_beam_str)

    stats = compute_stats(input_strs, beam_str, label_str)

    # Create the stats DataFrame
    stats_df = flatten_stats(stats, topk)

    # Save and display stats using the new functions
    save_stats_to_csv(stats_df, model_path, triplet_comb)
    print("\nFinal Statistics:")
    display_current_stats(stats_df, len(test_dataset))

    # compute metrics after filtering
    tkacc_metrics_filtered = tkacc.compute(predictions=beam_str, references=label_str, k_metrics=[1, 3, 5], strict_k=False)
    cer_metric_filtered = {'cer_filtered': cer.compute(predictions=best_beam_str, references=label_str)}

    # add prefixes
    tkacc_metrics_unfiltered = {prefix_key(k, 'tkacc_unfiltered', '/'): v for k, v in tkacc_metrics_unfiltered.items()}
    tkacc_metrics_filtered = {prefix_key(k, 'tkacc_filtered', '/'): v for k, v in tkacc_metrics_filtered.items()}


    # construct a table for non-FPR metrics
    metric_table = pd.DataFrame([{
        **cer_metric_unfiltered,
        **cer_metric_filtered,

        **tkacc_metrics_unfiltered,
        **tkacc_metrics_filtered,

    }])

    # display non-FPR metrics
    display(HTML(metric_table.to_html(index=False)))

    # construct final dictionary for metrics (without stats)
    metric_dict = {
        **cer_metric_unfiltered,
        **cer_metric_filtered,
        **tkacc_metrics_unfiltered,
        **tkacc_metrics_filtered,
        'test_sample_size': len(label_str)
    }

    return metric_dict

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

# Model Testing

## Load Dataset

In [ ]:
train_sampling_params = {'correction_strategy': 'normal-multiple',
              'correction_distrib': (0, 5),
              'cursor_strategy': 'normal',
              'cursor_bias_type': 'point',
              'cursor_relax': 10,
              'cursor_rep': 'mask',
              'postprocessor': 'none',
              'invert_case_prob': 0.5,
              'log_stuff': False}
tokenizer = T5TokenizerFast.from_pretrained(base_model_name)
if train_sampling_params['cursor_rep'] in ['token']:
    print(f"added {tokenizer.add_special_tokens(custom_special_tokens_dict)} custom special tokens to tokenizer")

inference_sampling_params = dict(train_sampling_params)
inference_sampling_params['inference'] = True
inference_sampling_params['correction_strategy'] = 'normal-multiple'
inference_sampling_params['correction_distrib'] = (0, 5)
inference_sampling_params['cursor_strategy'] = 'uniform'
inference_sampling_params['cursor_rep'] = train_sampling_params['cursor_rep'] if train_sampling_params['cursor_rep'] is not None else 'token'
inference_sampling_params['cursor_relax'] = 10
inference_sampling_params['postprocessor'] = 'unbounded-triplets'
inference_sampling_params['invert_case_prob'] = 0.5
inference_sampling_params['log_stuff'] = False

inference_sampling_strategy = EditSamplingStrategy(**inference_sampling_params)

original_dataset_path = os.path.join(data_dir, 'test_data.csv')
dataset_path = os.path.join(data_dir, 'triplet_test_data_relax10_correction_dev5_stats.csv')
regen = False
if not os.path.exists(dataset_path) or regen:
    test_dataset_gen = TripletCorrectionDatasetWithEditsGenerator(
        data_path=original_dataset_path,
        tokenizer=tokenizer,
        sampling_strategy=inference_sampling_strategy,
    )
    test_dataset_gen.generate_dataset(
        min_classcounts={
            'l': 1500,
            'm': 2500,
            'r': 1500
        },
        dpath=dataset_path
    )

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

## Load Model

In [ ]:
sweep_name = 'text correction (unbounded triplets cursor strategies)'
model_name = 'correction_normal_multiple_point_uniform_mask_cursor-relax10'
model_path = os.path.join(models_dir, sweep_name, model_name)

model = CursorT5ForConditionalGeneration.from_pretrained(model_path, 'point')

## Test Model

In [ ]:
triplet_runs = [
    ['r'],
    ['l'],
    ['m']
]
mismatch_file=''
triplet_comb = ''
for triplet_classes in triplet_runs:
    triplet_comb = ''.join(triplet_classes)
    print(f'triplet classes: {triplet_classes}')
    # mismatch_file = f'{model_path}/mismatched_cases_triplets-{triplet_comb}-relax10.csv'
    test_dataset = TripletCorrectionDatasetWithEdits(
        data_path=dataset_path,
        tokenizer=tokenizer,
        triplet_classes=triplet_classes,
        scale=PORTION
    )

    # set training arguments
    training_args = Seq2SeqTrainingArguments(
        report_to=[],

        output_dir=''.join([model_path, '/checkpoints/']),

        num_train_epochs=1,

        learning_rate=0,
        weight_decay=0,

        per_device_train_batch_size=0,
        per_device_eval_batch_size=24,

        gradient_accumulation_steps=0,

        optim='adafactor',

        logging_strategy='steps',
        evaluation_strategy='steps',
        save_strategy='steps',

        logging_steps=0.01,
        eval_steps=0.5,
        save_steps=0.5,

        load_best_model_at_end=True,
        metric_for_best_model='loss',
        greater_is_better=False,
        save_total_limit=NUM_SAVES,

        predict_with_generate=True,
        prediction_loss_only=True, # disable using .generate() for evaluation steps during training because it is very slow

        no_cuda=False
    )

    # define training loop
    trainer = EarlyStoppingSeq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=test_dataset,
        eval_dataset=test_dataset,
        compute_metrics=lambda gen_preds : {},
        gen_kwargs_override={**gen_kwargs_override, 'decoder_start_token_id': 0},
        log_stuff=False
    )

    # check vocab
    print(f'model vocab size: {model.config.vocab_size}')
    print(f'tokenizer vocab: {len(tokenizer)}')

    trainer.compute_metrics = compute_metrics
    trainer.args.predict_with_generate = True
    trainer.args.include_inputs_for_metrics = True
    trainer.args.prediction_loss_only = False
    trainer.args.per_device_eval_batch_size = 4

    # # test
    test_evaluation = trainer.evaluate(eval_dataset=test_dataset, metric_key_prefix='test')
    print(f"test evaluation: \n{test_evaluation}\n")

    # save test results
    test_evaluation_df = pd.DataFrame(data=[test_evaluation], columns=test_evaluation.keys())
    test_evaluation_df.to_csv(f'{model_path}/test_results triplets-{triplet_comb}-relax10_stats.csv', index=False)

triplet classes: ['r']
preparing data from ./drive/MyDrive/Colab Notebooks/vr-txt-corr/corr_datasets_experimental/DELETION-INSERTION-MULTIPLE-REPLACEMENT-SINGLE/triplet_test_data_relax10_correction_dev5_stats.csv ...
	reading data ... filtering triplet classes...original len: 25246
updated len: 1500
updated len after dropping nan: 1500
sampling ...
done

/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:444: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(

model vocab size: 32100
tokenizer vocab: 32100

[('That must be a lot of kilometres. With the GPS reading still fresh in our minds, we forged ahead, fueled by a mixture of excitement and apprehension. The mountains now seemed closer, their rugged outlines beckoning us forward.', 'lot in kilometers.', '[((5, 7), (5, 7))]', '[((5, 7), (5, 7))]'), ('Do we need to do anything. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.', 'To do anything here.', '[((6, 6), (6, 7))]', '[((6, 6), (6, 7))]'), ("We will keep teying. Our perseverance will light the way, illuminating pathways we hadn't seen before. Each day brings fresh opportunities to rise and confront our fears head-on.", 'We will keep trying.', '[((3, 4), (3, 4))]', '[((3, 4), (3, 4))]'), ('he extended Freudian theory into adolescence and adulthood l. His research highlighted the significance of peer relationships and their influence on identity formation during teenage years. By integrating concepts from both psychoanalysis and modern psychology, he created a more nuanced understanding of human behavior.', 'extended Freudian theory into adolescence and adulthood.', '[((0, 1), (0, 1)), ((8, 9), (8, 8))]', '[((8, 9), (8, 8))]'), ('I think that we should enforce the agreements. This will help ensure that everyone adheres to their responsibilities and fosters a sense of reliability within the team. By doing so, we can create an environment where open dialogue is encouraged and concerns can be raised without fear.', 'I think that we should enforce the agreement.', '[((7, 8), (7, 8))]', '[((7, 8), (7, 8))]'), ('I think we should consider this request l. The proposal has merit, but we need to conduct a thorough risk assessment to identify any underlying issues. Engaging our stakeholders could provide fresh perspectives that may alter our initial impressions.', 'consider this request.', '[((7, 8), (7, 7))]', '[((7, 8), (7, 7))]'), ('A three-man inquiry team spent months investigating the allegation. Their approach included reviewing financial records, interviewing key personnel, and collecting testimonies from local residents who had experiences relevant to the case. As weeks turned into months, frustration began to mount among the townspeople, who felt their patience was being tested.', 'Months investigating the allegations.', '[((8, 9), (8, 9))]', '[((8, 9), (8, 9))]'), ('He extended Freudian theory into adolescence and adult hood. He introduced concepts that highlighted the impact of peer relationships and social dynamics on individual development. This broader perspective allowed for a more comprehensive understanding of identity formation as a continuous process.', 'Adolescence and adulthood.', '[((7, 9), (7, 8))]', '[((7, 9), (7, 8))]'), ('Many townspeople who had gathered earlier on the main roads. Many townspeople who had gathered earlier on the main road began to exchange greetings, their smiles reflecting the shared excitement of the day. Children weaved in and out of the crowd, their eyes wide with wonder as they spotted the colorful festival decorations being hung.', 'Gathered earlier on the main road.', '[((9, 10), (9, 10))]', '[((9, 10), (9, 10))]'), ('It’s quite a weeknd. The fresh breeze carried the scent of grilled vegetables and marinated meats, making my mouth water in anticipation. My friend, ever the gracious host, had prepared an array of delicious dishes that catered to everyone’s tastes.', "it's quite a weekend.", '[((0, 1), (0, 1)), ((3, 4), (3, 4))]', '[((3, 4), (3, 4)), ((0, 1), (0, 1))]')]
True
False
skipped (sent: |Do we need to do anything. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.|, phra: |To do anything here.|)
cbefo: |Do we need to do anything here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.|
cafte: |['Do we need to do anything here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.', 'Do we need to do anything here. the question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.', 'Do we need to do anything Here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.', 'Do we need to do anything here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget avoiding eye contact.']|
label: |Do we need to do anything. here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.|
True
False
skipped (sent: |he extended Freudian theory into adolescence and adulthood l. His research highlighted the significance of peer relationships and their influence on identity formation during teenage years. By integrating concepts from both psychoanalysis and modern psychology, he created a more nuanced understanding of human behavior.|, phra: |extended Freudian theory into adolescence and adulthood.|)
cbefo: |he extended Freudian theory into adolescence and adulthood His research highlighted the significance of peer relationships and their influence on identity formation during teenage years. By integrating concepts from both psychoanalysis and modern psychology, he created a more nuanced understanding of human behavior.|
cafte: |['he extended Freudian theory into adolescence and adulthood. His research highlighted the significance of peer relationships and their influence on identity formation during teenage years. By integrating concepts from both psychoanalysis and modern psychology, he created a more nuanced understanding of human behavior.']|
label: |he extended Freudian theory into adolescence and adulthood His research highlighted the significance of peer relationships and their influence on identity formation during teenage years. By integrating concepts from both psychoanalysis and modern psychology, he created a more nuanced understanding of human behavior.|
True
False
skipped (sent: |I think we should consider this request l. The proposal has merit, but we need to conduct a thorough risk assessment to identify any underlying issues. Engaging our stakeholders could provide fresh perspectives that may alter our initial impressions.|, phra: |consider this request.|)
cbefo: |I think we should consider this request The proposal has merit, but we need to conduct a thorough risk assessment to identify any underlying issues. Engaging our stakeholders could provide fresh perspectives that may alter our initial impressions.|
cafte: |['I think we should consider this request. The proposal has merit, but we need to conduct a thorough risk assessment to identify any underlying issues. Engaging our stakeholders could provide fresh perspectives that may alter our initial impressions.']|
label: |I think we should consider this request The proposal has merit, but we need to conduct a thorough risk assessment to identify any underlying issues. Engaging our stakeholders could provide fresh perspectives that may alter our initial impressions.|
True
False
skipped (sent: |Many town people who had gathered earlier on the main road. Many townspeople who had gathered earlier on the main road exchanged smiles and warm greetings, reveling in the joy that permeated the atmosphere. As the clock struck nine, the sound of a loud horn signaled the official opening of the fair.|, phra: |main road.|)
cbefo: |Many town people who had gathered earlier on the main road Many townspeople who had gathered earlier on the main road exchanged smiles and warm greetings, reveling in the joy that permeated the atmosphere. As the clock struck nine, the sound of a loud horn signaled the official opening of the fair.|
cafte: |[]|
label: |Many town people who had gathered earlier on the main road Many townspeople who had gathered earlier on the main road exchanged smiles and warm greetings, reveling in the joy that permeated the atmosphere. As the clock struck nine, the sound of a loud horn signaled the official opening of the fair.|
True
False
skipped (sent: |Construction on the complex will begin this year ht. The groundbreaking ceremony is set for next month, with local leaders expected to give speeches highlighting the project's significance. Residents are encouraged to attend and participate in the celebrations, marking a pivotal moment for the community.|, phra: |construction on the complex will begin this year.|)
cbefo: |Construction on the complex will begin this year The groundbreaking ceremony is set for next month, with local leaders expected to give speeches highlighting the project's significance. Residents are encouraged to attend and participate in the celebrations, marking a pivotal moment for the community.|
cafte: |["Construction on the complex will begin this year. The groundbreaking ceremony is set for next month, with local leaders expected to give speeches highlighting the project's significance. Residents are encouraged to attend and participate in the celebrations, marking a pivotal moment for the community."]|
label: |Construction on the complex will begin this year The groundbreaking ceremony is set for next month, with local leaders expected to give speeches highlighting the project's significance. Residents are encouraged to attend and participate in the celebrations, marking a pivotal moment for the community.|
True
False
skipped (sent: |If you need John speak up now. The room remained tense, and all eyes turned to John, who sat frozen in his seat. He could feel the pressure mounting, as if every breath he took needed to carry the weight of their collective anticipation.|, phra: |If you need John speak up now.|)
cbefo: |If you need John speak up now The room remained tense, and all eyes turned to John, who sat frozen in his seat. He could feel the pressure mounting, as if every breath he took needed to carry the weight of their collective anticipation.|
cafte: |[]|
label: |If you need John speak up now The room remained tense, and all eyes turned to John, who sat frozen in his seat. He could feel the pressure mounting, as if every breath he took needed to carry the weight of their collective anticipation.|
True
False
skipped (sent: |Drop him if he was on your fantasy roster. It's time to seek out a replacement who can deliver more consistent points. Look for emerging players who are gaining momentum or veterans who might have been overlooked in previous drafts.|, phra: |if he was on your Fantasy roster.|)
cbefo: |Drop him if he was on your Fantasy roster It's time to seek out a replacement who can deliver more consistent points. Look for emerging players who are gaining momentum or veterans who might have been overlooked in previous drafts.|
cafte: |["Drop him if he was on your Fantasy roster. It's time to seek out a replacement who can deliver more consistent points. Look for emerging players who are gaining momentum or veterans who might have been overlooked in previous drafts."]|
label: |Drop him if he was on your Fantasy roster It's time to seek out a replacement who can deliver more consistent points. Look for emerging players who are gaining momentum or veterans who might have been overlooked in previous drafts.|
True
False
skipped (sent: |Emetson Fittipaldi has never had an engine this good. The roar of the power beneath him was exhilarating, a sound he had dreamed of since his early days on the track. He could already envision the grid positions, the tight corners, and the fierce competition that awaited.|, phra: |This good.|)
cbefo: |Emetson Fittipaldi has never had an engine this good The roar of the power beneath him was exhilarating, a sound he had dreamed of since his early days on the track. He could already envision the grid positions, the tight corners, and the fierce competition that awaited.|
cafte: |[]|
label: |Emetson Fittipaldi has never had an engine this good The roar of the power beneath him was exhilarating, a sound he had dreamed of since his early days on the track. He could already envision the grid positions, the tight corners, and the fierce competition that awaited.|
True
False
skipped (sent: |He was recognised in his field as a pioneer. His dedication inspired numerous young scientists to pursue careers in ecology and conservation. Workshops he organized attracted participants from various disciplines, fostering interdisciplinary collaboration.|, phra: |He was recognized in his field as a pioneer.|)
cbefo: |He was recognized in his field as a pioneer His dedication inspired numerous young scientists to pursue careers in ecology and conservation. Workshops he organized attracted participants from various disciplines, fostering interdisciplinary collaboration.|
cafte: |['He was recognized in his field as a pioneer. His dedication inspired numerous young scientists to pursue careers in ecology and conservation. Workshops he organized attracted participants from various disciplines, fostering interdisciplinary collaboration.']|
label: |He was recognized in his field as a pioneer His dedication inspired numerous young scientists to pursue careers in ecology and conservation. Workshops he organized attracted participants from various disciplines, fostering interdisciplinary collaboration.|
True
False
skipped (sent: |We are proceeding with a great reception so far. Guests are arriving, and their smiles light up the room, making all the planning worthwhile. The check-in process is smooth, thanks to our diligent volunteers who welcome each attendee with warmth.|, phra: |reception so far.|)
cbefo: |We are proceeding with a great reception so far Guests are arriving, and their smiles light up the room, making all the planning worthwhile. The check-in process is smooth, thanks to our diligent volunteers who welcome each attendee with warmth.|
cafte: |[]|
label: |We are proceeding with a great reception so far Guests are arriving, and their smiles light up the room, making all the planning worthwhile. The check-in process is smooth, thanks to our diligent volunteers who welcome each attendee with warmth.|
True
False
skipped (sent: |We are about to leave Heaven. As we stood there, the reality of our departure settled over us like a soft mist. The vibrant colors of the scene seemed to dim slightly, as if the landscape understood our sorrow.|, phra: |Leave Heaven.|)
cbefo: |We are about to leave Heaven As we stood there, the reality of our departure settled over us like a soft mist. The vibrant colors of the scene seemed to dim slightly, as if the landscape understood our sorrow.|
cafte: |[]|
label: |We are about to leave Heaven As we stood there, the reality of our departure settled over us like a soft mist. The vibrant colors of the scene seemed to dim slightly, as if the landscape understood our sorrow.|
True
False
skipped (sent: |Avoid starting either back in Week 10 if at all possible. Week 10 poses significant challenges for many fantasy teams, and it's important to assess alternative options. Look for emerging players who may be undervalued but have favorable matchups.|, phra: |week 10 if at all possible.|)
cbefo: |Avoid starting either back in Week 10 if at all possible Week 10 poses significant challenges for many fantasy teams, and it's important to assess alternative options. Look for emerging players who may be undervalued but have favorable matchups.|
cafte: |[]|
label: |Avoid starting either back in Week 10 if at all possible Week 10 poses significant challenges for many fantasy teams, and it's important to assess alternative options. Look for emerging players who may be undervalued but have favorable matchups.|
True
False
skipped (sent: |Do we need to do anything. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.|, phra: |To do anything here.|)
cbefo: |Do we need to do anything here. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.|
cafte: |['Do we need to do anything here. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.', 'Do we need to do anything here. in preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.', 'Do we need to do anything Here. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.', 'Do we need to do anything here. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far..']|
label: |Do we need to do anything. here. In preparation for the meeting, we should compile a list of the outstanding tasks and assign clear deadlines for each one. It might also be helpful to create a visual timeline that outlines our progress thus far.|
True
False
skipped (sent: |Do you know if this has been done yet. It’s important that we clarify any uncertainties as soon as possible to avoid delays. Perhaps I could send a reminder to the team about the key points we discussed.|, phra: |Done yet.|)
cbefo: |Do you know if this has been done yet It’s important that we clarify any uncertainties as soon as possible to avoid delays. Perhaps I could send a reminder to the team about the key points we discussed.|
cafte: |[]|
label: |Do you know if this has been done yet It’s important that we clarify any uncertainties as soon as possible to avoid delays. Perhaps I could send a reminder to the team about the key points we discussed.|
True
False
skipped (sent: |Can you try this again. Take a moment to gather your thoughts and refocus on the task at hand. Visualize the steps you need to complete and tackle them one at a time.|, phra: |Can you try this again.|)
cbefo: |Can you try this again Take a moment to gather your thoughts and refocus on the task at hand. Visualize the steps you need to complete and tackle them one at a time.|
cafte: |[]|
label: |Can you try this again Take a moment to gather your thoughts and refocus on the task at hand. Visualize the steps you need to complete and tackle them one at a time.|
True
False
skipped (sent: |Do we need to do anything. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.|, phra: |anything here.|)
cbefo: |Do we need to do anything here. The question hung in the air, prompting a ripple of reactions. Some nodded in agreement, while others continued to fidget, avoiding eye contact.|

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9379  0.9527  0.9527     317  322  322   338  338
                 2        0.9577  0.9718  0.9718     136  138  138   142  142
                 3        0.9444  0.9444  0.9444      17   17   17    18   18
                 4        1.0000  1.0000  1.0000       2    2    2     2    2
extra_word_added 0        0.8906  0.9375  0.9375      57   60   60    64   64
                 1        0.9780  0.9890  0.9890      89   90   90    91   91
                 2        0.9615  0.9744  0.9744      75   76   76    78   78
                 3        0.9756  0.9756  0.9756      80   80   80    82   82
                 4        0.9107  0.9107  0.9107      51   51   51    56   56
                 5        0.9565  0.9565  0.9565      44   44   44    46   46
                 6        0.8824  0.9412  0.9412      30   32   32    34   34
                 7        0.9565  0.9565  0.9565      22   22   22    23   23
                 8        0.8462  0.8462  0.8462      11   11   11    13   13
                 9        1.0000  1.0000  1.0000       6    6    6     6    6
                 10       1.0000  1.0000  1.0000       2    2    2     2    2
                 11       1.0000  1.0000  1.0000       3    3    3     3    3
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_count 0        0.9189  0.9730  0.9730      34   36   36    37   37
                 1        0.9625  0.9750  0.9750      77   78   78    80   80
                 2        0.9518  0.9759  0.9759      79   81   81    83   83
                 3        0.9778  0.9778  0.9778      88   88   88    90   90
                 4        0.8772  0.8772  0.8772      50   50   50    57   57
                 5        0.9608  0.9608  0.9608      49   49   49    51   51
                 6        0.9111  0.9556  0.9556      41   43   43    45   45
                 7        0.9583  0.9583  0.9583      23   23   23    24   24
                 8        0.8889  0.8889  0.8889      16   16   16    18   18
                 9        1.0000  1.0000  1.0000       8    8    8     8    8
                 10       1.0000  1.0000  1.0000       2    2    2     2    2
                 11       1.0000  1.0000  1.0000       3    3    3     3    3
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count  1        0.8929  0.9643  0.9643      25   27   27    28   28
                 2        0.9861  1.0000  1.0000      71   72   72    72   72
                 3        0.9365  0.9524  0.9524      59   60   60    63   63
                 4        0.9574  0.9681  0.9681      90   91   91    94   94
                 5        0.9375  0.9375  0.9375      60   60   60    64   64
                 6        0.9464  0.9464  0.9464      53   53   53    56   56
                 7        0.8936  0.9362  0.9362      42   44   44    47   47
                 8        0.9259  0.9259  0.9259      25   25   25    27   27
                 9        0.9630  0.9630  0.9630      26   26   26    27   27
                 10       1.0000  1.0000  1.0000       8    8    8     8    8
                 11       0.8889  0.8889  0.8889       8    8    8     9    9
                 12       1.0000  1.0000  1.0000       3    3    3     3    3
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
                 14       1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count       1       338
                 2       142
                 3        18
                 4         2
extra_word_added 0        64
                 1        91
                 2        78
                 3        82
                 4        56
                 5        46
                 6        34
                 7        23
                 8        13
                 9         6
                 10        2
                 11        3
                 12        1
                 13        1
extra_word_count 0        37
                 1        80
                 2        83
                 3        90
                 4        57
                 5        51
                 6        45
                 7        24
                 8        18
                 9         8
                 10        2
                 11        3
                 12        1
                 13        1
part_word_count  1        28
                 2        72
                 3        63
                 4        94
                 5        64
                 6        56
                 7        47
                 8        27
                 9        27
                 10        8
                 11        9
                 12        3
                 13        1
                 14        1

================================================================================

Statistics after processing 1000 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9451  0.9573  0.9573     620  628  628   656  656
                 2        0.9336  0.9535  0.9535     281  287  287   301  301
                 3        0.9737  0.9737  0.9737      37   37   37    38   38
                 4        0.8000  1.0000  1.0000       4    5    5     5    5
extra_word_added 0        0.9023  0.9474  0.9474     120  126  126   133  133
                 1        0.9538  0.9653  0.9653     165  167  167   173  173
                 2        0.9535  0.9709  0.9709     164  167  167   172  172
                 3        0.9870  0.9870  0.9870     152  152  152   154  154
                 4        0.9259  0.9352  0.9352     100  101  101   108  108
                 5        0.9592  0.9592  0.9592      94   94   94    98   98
                 6        0.8846  0.9231  0.9231      69   72   72    78   78
                 7        0.9524  0.9524  0.9524      40   40   40    42   42
                 8        0.8333  0.8333  0.8333      20   20   20    24   24
                 9        1.0000  1.0000  1.0000       9    9    9     9    9
                 10       1.0000  1.0000  1.0000       3    3    3     3    3
                 11       1.0000  1.0000  1.0000       4    4    4     4    4
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_count 0        0.9351  0.9740  0.9740      72   75   75    77   77
                 1        0.9463  0.9664  0.9664     141  144  144   149  149
                 2        0.9435  0.9661  0.9661     167  171  171   177  177
                 3        0.9880  0.9880  0.9880     164  164  164   166  166
                 4        0.9130  0.9217  0.9217     105  106  106   115  115
                 5        0.9474  0.9561  0.9561     108  109  109   114  114
                 6        0.9100  0.9400  0.9400      91   94   94   100  100
                 7        0.9565  0.9565  0.9565      44   44   44    46   46
                 8        0.8235  0.8235  0.8235      28   28   28    34   34
                 9        1.0000  1.0000  1.0000      12   12   12    12   12
                 10       1.0000  1.0000  1.0000       4    4    4     4    4
                 11       1.0000  1.0000  1.0000       4    4    4     4    4
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count  1        0.9344  0.9836  0.9836      57   60   60    61   61
                 2        0.9769  0.9846  0.9846     127  128  128   130  130
                 3        0.9306  0.9514  0.9514     134  137  137   144  144
                 4        0.9613  0.9779  0.9779     174  177  177   181  181
                 5        0.9402  0.9487  0.9487     110  111  111   117  117
                 6        0.9655  0.9655  0.9655     112  112  112   116  116
                 7        0.8909  0.9182  0.9182      98  101  101   110  110
                 8        0.9423  0.9423  0.9423      49   49   49    52   52
                 9        0.9057  0.9245  0.9245      48   49   49    53   53
                 10       1.0000  1.0000  1.0000      14   14   14    14   14
                 11       0.7692  0.7692  0.7692      10   10   10    13   13
                 12       1.0000  1.0000  1.0000       6    6    6     6    6
                 13       1.0000  1.0000  1.0000       2    2    2     2    2
                 14       1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count       1       656
                 2       301
                 3        38
                 4         5
extra_word_added 0       133
                 1       173
                 2       172
                 3       154
                 4       108
                 5        98
                 6        78
                 7        42
                 8        24
                 9         9
                 10        3
                 11        4
                 12        1
                 13        1
extra_word_count 0        77
                 1       149
                 2       177
                 3       166
                 4       115
                 5       114
                 6       100
                 7        46
                 8        34
                 9        12
                 10        4
                 11        4
                 12        1
                 13        1
part_word_count  1        61
                 2       130
                 3       144
                 4       181
                 5       117
                 6       116
                 7       110
                 8        52
                 9        53
                 10       14
                 11       13
                 12        6
                 13        2
                 14        1

================================================================================
Saved detailed statistics to ./drive/MyDrive/Colab Notebooks/vr-txt-corr/saved_models/text correction (unbounded triplets cursor strategies)/correction_normal_multiple_point_uniform_mask_cursor-relax10/stats_triplets-r-relax10.csv

Final Statistics:

Statistics after processing 1500 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9536  0.9640  0.9640     822  831  831   862  862
                 2        0.9309  0.9514  0.9514     364  372  372   391  391
                 3        0.9643  0.9643  0.9643      54   54   54    56   56
                 4        0.8571  1.0000  1.0000       6    7    7     7    7
extra_word_added 0        0.9012  0.9419  0.9419     155  162  162   172  172
                 1        0.9617  0.9702  0.9702     226  228  228   235  235
                 2        0.9595  0.9730  0.9730     213  216  216   222  222
                 3        0.9717  0.9811  0.9811     206  208  208   212  212
                 4        0.9419  0.9484  0.9484     146  147  147   155  155
                 5        0.9606  0.9606  0.9606     122  122  122   127  127
                 6        0.9043  0.9362  0.9362      85   88   88    94   94
                 7        0.9583  0.9583  0.9583      46   46   46    48   48
                 8        0.8667  0.8667  0.8667      26   26   26    30   30
                 9        1.0000  1.0000  1.0000       9    9    9     9    9
                 10       1.0000  1.0000  1.0000       4    4    4     4    4
                 11       1.0000  1.0000  1.0000       5    5    5     5    5
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       2    2    2     2    2
extra_word_count 0        0.9368  0.9789  0.9789      89   93   93    95   95
                 1        0.9561  0.9707  0.9707     196  199  199   205  205
                 2        0.9471  0.9648  0.9648     215  219  219   227  227
                 3        0.9783  0.9870  0.9870     225  227  227   230  230
                 4        0.9240  0.9298  0.9298     158  159  159   171  171
                 5        0.9456  0.9524  0.9524     139  140  140   147  147
                 6        0.9237  0.9492  0.9492     109  112  112   118  118
                 7        0.9636  0.9636  0.9636      53   53   53    55   55
                 8        0.8537  0.8537  0.8537      35   35   35    41   41
                 9        1.0000  1.0000  1.0000      14   14   14    14   14
                 10       1.0000  1.0000  1.0000       5    5    5     5    5
                 11       1.0000  1.0000  1.0000       5    5    5     5    5
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       2    2    2     2    2
part_word_count  1        0.9359  0.9872  0.9872      73   77   77    78   78
                 2        0.9827  0.9884  0.9884     170  171  171   173  173
                 3        0.9479  0.9635  0.9635     182  185  185   192  192
                 4        0.9461  0.9668  0.9668     228  233  233   241  241
                 5        0.9540  0.9598  0.9598     166  167  167   174  174
                 6        0.9477  0.9477  0.9477     145  145  145   153  153
                 7        0.9118  0.9338  0.9338     124  127  127   136  136
                 8        0.9516  0.9516  0.9516      59   59   59    62   62
                 9        0.9219  0.9375  0.9375      59   60   60    64   64
                 10       1.0000  1.0000  1.0000      16   16   16    16   16
                 11       0.8000  0.8000  0.8000      12   12   12    15   15
                 12       1.0000  1.0000  1.0000       7    7    7     7    7
                 13       1.0000  1.0000  1.0000       3    3    3     3    3
                 14       1.0000  1.0000  1.0000       2    2    2     2    2


metric                  top5
category         subcat
edit_count       1       862
                 2       391
                 3        56
                 4         7
extra_word_added 0       172
                 1       235
                 2       222
                 3       212
                 4       155
                 5       127
                 6        94
                 7        48
                 8        30
                 9         9
                 10        4
                 11        5
                 12        1
                 13        2
extra_word_count 0        95
                 1       205
                 2       227
                 3       230
                 4       171
                 5       147
                 6       118
                 7        55
                 8        41
                 9        14
                 10        5
                 11        5
                 12        1
                 13        2
part_word_count  1        78
                 2       173
                 3       192
                 4       241
                 5       174
                 6       153
                 7       136
                 8        62
                 9        64
                 10       16
                 11       15
                 12        7
                 13        3
                 14        2

================================================================================

test evaluation:
{'test_sample_size': 1316, 'test_loss': 0.010865765623748302, 'test_cer_unfiltered': 0.001468677796317101, 'test_cer_filtered': 0.0006026121267362952, 'test_tkacc_unfiltered/t1acc': 0.9247720364741642, 'test_tkacc_unfiltered/t3acc': 0.9566869300911854, 'test_tkacc_unfiltered/t5acc': 0.9582066869300911, 'test_tkacc_filtered/t1acc': 0.9468085106382979, 'test_tkacc_filtered/t3acc': 0.9604863221884499, 'test_tkacc_filtered/t5acc': 0.9604863221884499, 'test_runtime': 1799.1846, 'test_samples_per_second': 0.834, 'test_steps_per_second': 0.208, 'eval_bloss': None}

triplet classes: ['l']
preparing data from ./drive/MyDrive/Colab Notebooks/vr-txt-corr/corr_datasets_experimental/DELETION-INSERTION-MULTIPLE-REPLACEMENT-SINGLE/triplet_test_data_relax10_correction_dev5_stats.csv ...
	reading data ... filtering triplet classes...original len: 25246
updated len: 2866
updated len after dropping nan: 2866
sampling ...
done
model vocab size: 32100
tokenizer vocab: 32100

/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:444: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(

[('A sense of unity and celebration radiated among the crowd, setting the tone for the evening. As the lights dimmed, it became clear that something special was about to unfold. The company was followed by the premiere of the opening film.', 'The ceremony was followed by the premiere of the', '[((1, 2), (1, 2))]', '[((1, 2), (1, 2))]'), ('The thought of failing in front of my friends was daunting. Ultimately, I made a decision that felt right for me. count me it for this round.', 'Count me out for this round.', '[((0, 1), (0, 1)), ((2, 3), (2, 3))]', '[((2, 3), (2, 3)), ((0, 1), (0, 1))]'), ('Experts from various fields came together to share their insights and propose potential solutions. The atmosphere was charged with anticipation and urgency as stakeholders prepared to engage in meaningful discussions. the event reopens debate on the issues.', 'The event reopens debate on', '[((0, 1), (0, 1)), ((6, 7), (6, 7))]', '[((0, 1), (0, 1))]'), ('I could see the frustration building within the group as we tried to adapt. Ultimately, it became difficult to keep track of what our original goals had been. BUt there have been so many changes in plans that i’m not surprised.', 'but there have been so many', '[((0, 1), (0, 1)), ((10, 11), (10, 11))]', '[((0, 1), (0, 1))]'), ("I’ve already asked my boss for a half-day off on Friday. Alright, time to make my move! Okay I'ii go for a ticket.", "okay I'll go for a ticket.", '[((1, 2), (1, 2))]', '[((1, 2), (1, 2))]'), ('I decided to give it a few minutes before trying again. My mind raced with all the updates I wanted to share. tried to call but could’t reach you.', "tried to call but couldn't reach", '[((0, 1), (0, 1)), ((4, 5), (4, 5))]', '[((4, 5), (4, 5)), ((0, 1), (0, 1))]'), ('While some have placed their trust in the process, others remain skeptical of the intentions behind the negotiations. As the days go by, the pressure mounts, and the desire for a resolution grows ever more urgent. But the oact has not entirely calmed the nation’s nerves.', 'But the pact has not entirely calmed', '[((2, 3), (2, 3)), ((8, 9), (8, 9))]', '[((2, 3), (2, 3))]'), ('Consumers are also affected, often overpaying due to the lack of clarity in pricing. Only by tackling these issues can we hope to create a fair playing field for all. The infotmal costs habe to disappear.', 'the informal costs have', '[((1, 2), (1, 2)), ((3, 4), (3, 4))]', '[((3, 4), (3, 4)), ((1, 2), (1, 2))]'), ('We found ourselves reconsidering the agenda and what topics were truly essential for this gathering. With all the shifting pieces, it felt like we were in a constant state of re-evaluation. but there have been so many changes in the plans that I’m not surprised.', 'but there', '[((0, 1), (0, 1)), ((8, 9), (8, 8)), ((11, 12), (10, 11))]', '[((0, 1), (0, 1))]'), ('The gentle breeze carried the sound of music from a nearby gathering. It felt like a perfect day, full of joy and camaraderie. W head a great time.', 'we had a great time.', '[((0, 2), (0, 2))]', '[((0, 2), (0, 2))]')]
True
False
skipped (sent: |Social media buzzed with messages of support from fans around the league. Each update from the sports reporters heightened the anxiety surrounding the situation. he is listed as day to day.|, phra: |he is listed as day to day.|)
cbefo: |Social media buzzed with messages of support from fans around the league. Each update from the sports reporters heightened the anxiety surrounding the situation. He is listed as day to day.|
cafte: |['Social media buzzed with messages of support from fans around the league. Each update from the sports reporters heightened the anxiety surrounding the situation. He is listed as day to day.', 'Social media buzzed with messages of support from fans around the league. Each update from the sports reporters heightened the anxiety surrounding the situation. He is listed as day to day He is listed as day to day.']|
label: |Social media buzzed with messages of support from fans around the league. Each update from the sports reporters heightened the anxiety surrounding the situation. He is listed as day to day|
True
False
skipped (sent: |Ultimately, finding common ground was crucial for our partnership. We embraced the idea that finding a middle path could lead to mutual satisfaction. That’s a fair trade off.|, phra: |That's a fair trade off.|)
cbefo: |Ultimately, finding common ground was crucial for our partnership. We embraced the idea that finding a middle path could lead to mutual satisfaction. That's a fair trade off|
cafte: |["Ultimately, finding common ground was crucial for our partnership. We embraced the idea that finding a middle path could lead to mutual satisfaction. That's a fair trade off."]|
label: |Ultimately, finding common ground was crucial for our partnership. We embraced the idea that finding a middle path could lead to mutual satisfaction. That's a fair trade off|
True
False
skipped (sent: |The atmosphere shifted as people began sharing their thoughts on the matter. Eventually, someone asked if anyone had concrete information to share. No, at least not to my knowledge.|, phra: |no, at least not to my knowledge.|)
cbefo: |The atmosphere shifted as people began sharing their thoughts on the matter. Eventually, someone asked if anyone had concrete information to share. No, at least not to my knowledge|
cafte: |[]|
label: |The atmosphere shifted as people began sharing their thoughts on the matter. Eventually, someone asked if anyone had concrete information to share. No, at least not to my knowledge|
True
False
skipped (sent: |Each member of the team understood that clarity was key to their success. They needed to establish a common language to move forward effectively. what are the units.|, phra: |What are the units.|)
cbefo: |Each member of the team understood that clarity was key to their success. They needed to establish a common language to move forward effectively. What are the units.|
cafte: |['Each member of the team understood that clarity was key to their success. They needed to establish a common language to move forward effectively. What are the units.', 'Each member of the team understood that clarity was key to their success. They needed to establish a common language to move forward effectively. What are the units What are the units.']|
label: |Each member of the team understood that clarity was key to their success. They needed to establish a common language to move forward effectively. What are the units|
True
False
skipped (sent: |Before long, someone suggested they should enlist the entire neighborhood to help. The plan took shape rapidly, spiraling into a chaotic mix of ambition and creativity. It’s going to be ludicrous.|, phra: |It's going to be ludicrous.|)
cbefo: |Before long, someone suggested they should enlist the entire neighborhood to help. The plan took shape rapidly, spiraling into a chaotic mix of ambition and creativity. It's going to be ludicrous It's going to be ludicrous|
cafte: |["Before long, someone suggested they should enlist the entire neighborhood to help. The plan took shape rapidly, spiraling into a chaotic mix of ambition and creativity. It's going to be ludicrous.", "Before long, someone suggested they should enlist the entire neighborhood to help. The plan took shape rapidly, spiraling into a chaotic mix of ambition and creativity. It's going to be ludicrous It's going to be ludicrous."]|
label: |Before long, someone suggested they should enlist the entire neighborhood to help. The plan took shape rapidly, spiraling into a chaotic mix of ambition and creativity. It's going to be ludicrous|
True
False
skipped (sent: |The layout is user-friendly, making it easy to navigate. I believe it will enhance our understanding of the current standards. Kim, here’s the PSCO Website address.|, phra: |Kim, here's the PSCO website address.|)
cbefo: |The layout is user-friendly, making it easy to navigate. I believe it will enhance our understanding of the current standards. Kim, here's the PSCO website address Kim, here's the PSCO website address|
cafte: |["The layout is user-friendly, making it easy to navigate. I believe it will enhance our understanding of the current standards. Kim, here's the PSCO website address.", "The layout is user-friendly, making it easy to navigate. I believe it will enhance our understanding of the current standards. Kim, here's the PSCO website address Kim, here's the PSCO website address."]|
label: |The layout is user-friendly, making it easy to navigate. I believe it will enhance our understanding of the current standards. Kim, here's the PSCO website address|
True
False
skipped (sent: |I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. a bit behind on my emails.|, phra: |a bit behind on my emails.|)
cbefo: |I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. A bit behind on my emails.|
cafte: |['I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. A bit behind on my emails.', 'I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. A bit behind on my emails A bit behind on my emails.', 'I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. A bit behind on my emails a bit behind on my emails.']|
label: |I completely forgot about the follow-up emails I needed to send. Now, I’m feeling overwhelmed by the sheer volume of messages waiting for me. A bit behind on my emails|
True
False
skipped (sent: |One by one, emotions began to unravel, revealing the fears hidden beneath the surface. It felt as if everyone was waiting for something to happen, gripping the edges of their seats. what is going on.|, phra: |what is going on.|)
cbefo: |One by one, emotions began to unravel, revealing the fears hidden beneath the surface. It felt as if everyone was waiting for something to happen, gripping the edges of their seats. What is going on.|
cafte: |['One by one, emotions began to unravel, revealing the fears hidden beneath the surface. It felt as if everyone was waiting for something to happen, gripping the edges of their seats. What is going on.', 'One by one, emotions began to unravel, revealing the fears hidden beneath the surface. It felt as if everyone was waiting for something to happen, gripping the edges of their seats. What is going on What is going on.']|
label: |One by one, emotions began to unravel, revealing the fears hidden beneath the surface. It felt as if everyone was waiting for something to happen, gripping the edges of their seats. What is going on|
True
False
skipped (sent: |I believe it will provide valuable insights for our next meeting. I'm eager to hear your thoughts on the content. Let me jnow if you can’t open it.|, phra: |Let me know if you can't open it.|)
cbefo: |I believe it will provide valuable insights for our next meeting. I'm eager to hear your thoughts on the content. Let me know if you can't open it.|
cafte: |["I believe it will provide valuable insights for our next meeting. I'm eager to hear your thoughts on the content. Let me know if you can't open it."]|
label: |I believe it will provide valuable insights for our next meeting. I'm eager to hear your thoughts on the content. Let me know if you can't open it|
True
False
skipped (sent: |With the budget constraints tightening, the team needs to strategize effectively. Lastly, effective communication with all parties involved is crucial for transparency and trust. what is the cost issue.|, phra: |What is the cost issue.|)
cbefo: |With the budget constraints tightening, the team needs to strategize effectively. Lastly, effective communication with all parties involved is crucial for transparency and trust. What is the cost issue.|
cafte: |['With the budget constraints tightening, the team needs to strategize effectively. Lastly, effective communication with all parties involved is crucial for transparency and trust. What is the cost issue.', 'With the budget constraints tightening, the team needs to strategize effectively. Lastly, effective communication with all parties involved is crucial for transparency and trust. What is the cost issue What is the cost issue.']|
label: |With the budget constraints tightening, the team needs to strategize effectively. Lastly, effective communication with all parties involved is crucial for transparency and trust. What is the cost issue|
True
False
skipped (sent: |In the distance, the call of an owl added a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. what do you hear.|, phra: |What do you hear.|)
cbefo: |In the distance, the call of an owl added a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. What do you hear|
cafte: |['In the distance, the call of an owl added a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. What do you hear.', 'In the distance, the call of an owl added a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. What do you hear What do you hear.', 'In the distance, a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. What do you hear.']|
label: |In the distance, the call of an owl added a sense of mystery to the night. All these sounds blended harmoniously, drawing one deeper into the enchanting wilderness. What do you hear|
True
False
skipped (sent: |I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am reaaly not wanting to come back.|, phra: |Really not wanting to come back.|)
cbefo: |I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am really not wanting to come back.|
cafte: |['I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am really not wanting to come back.', 'I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am really not wanting to come back really not wanting to come back.', 'I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am really not wanting to come back Really not wanting to come back.']|
label: |I thought about all the responsibilities waiting for me back home. The pressure was building, and all I wanted was to hold onto this moment a little longer. I am really not wanting to come back|
True
False
skipped (sent: |Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. Os Cassandra there today.|, phra: |is Cassandra there today.|)
cbefo: |Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. Is Cassandra there today.|
cafte: |['Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. Is Cassandra there today.', 'Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. is Cassandra there today.', 'Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. IS Cassandra there today.']|
label: |Just then, I remembered that Cassandra usually brought her infectious enthusiasm to the team. Her absence today was definitely noted by all. Is Cassandra there today|
True
False
skipped (sent: |Let me know if you need any further assistance with this. I look forward to hearing back from you soon. let me know if you can’t open it.|, phra: |let me know if you can't open it.|)
cbefo: |Let me know if you need any further assistance with this. I look forward to hearing back from you soon. Let me know if you can't open it.|
cafte: |["Let me know if you need any further assistance with this. I look forward to hearing back from you soon. Let me know if you can't open it."]|
label: |Let me know if you need any further assistance with this. I look forward to hearing back from you soon. Let me know if you can't open it|
True
False
skipped (sent: |Have you found any resources that could assist you? Keep me posted on how everything turns out. i hope everything worked out okay with your rent b.|, phra: |I hope everything worked out okay with your rent.|)
cbefo: |Have you found any resources that could assist you? Keep me posted on how everything turns out. I hope everything worked out okay with your rent.|
cafte: |['Have you found any resources that could assist you? Keep me posted on how everything turns out. I hope everything worked out okay with your rent.', 'Have you found any resources that could assist you? Keep me posted on how everything turns out. I hope everything worked out okay with your rent. B.', 'Have you found any resources that could assist you? Keep me posted on how everything turns out. i hope everything worked out okay with your rent.']|
label: |Have you found any resources that could assist you? Keep me posted on how everything turns out. I hope everything worked out okay with your rent|
True
False
skipped (sent: |I took notes on the feedback we received from the team. At that moment, I wondered if everyone had received the documents I sent out earlier. did you get this.|, phra: |did you get this.|)
cbefo: |I took notes on the feedback we received from the team. At that moment, I wondered if everyone had received the documents I sent out earlier. Did you get this.|
cafte: |['I took notes on the feedback we received from the team. At that moment, I wondered if everyone had received the documents I sent out earlier. Did you get this.', 'I took notes on the feedback we received from the team. At that moment, I wondered if everyone had received the documents I sent out earlier. Did you get this Did you get this.']|
label: |I took notes on the feedback we received from the team. At that moment, I wondered if everyone had received the documents I sent out earlier. Did you get this|
True
False
skipped (sent: |Once we finalize our thoughts, we'll provide you with an update. Thank you for your patience as we navigate this decision-making process. Well let you know in the morning if we are interested or not.|, phra: |we'll let you know in the morning if we are interested or not.|)
cbefo: |Once we finalize our thoughts, we'll provide you with an update. Thank you for your patience as we navigate this decision-making process. We'll let you know in the morning if we are interested or not.|
cafte: |["Once we finalize our thoughts, we'll provide you with an update. Thank you for your patience as we navigate this decision-making process. We'll let you know in the morning if we are interested or not."]|
label: |Once we finalize our thoughts, we'll provide you with an update. Thank you for your patience as we navigate this decision-making process. We'll let you know in the morning if we are interested or not|

Statistics after processing 500 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9789  0.9910  0.9910     325  329  329   332  332
                 2        0.9658  0.9932  1.0000     141  145  146   146  146
                 3        0.9545  1.0000  1.0000      21   22   22    22   22
extra_word_added 0        0.9574  0.9787  0.9787      45   46   46    47   47
                 1        0.9570  0.9892  0.9892      89   92   92    93   93
                 2        0.9706  0.9902  1.0000      99  101  102   102  102
                 3        0.9775  0.9888  0.9888      87   88   88    89   89
                 4        0.9697  1.0000  1.0000      64   66   66    66   66
                 5        1.0000  1.0000  1.0000      49   49   49    49   49
                 6        1.0000  1.0000  1.0000      24   24   24    24   24
                 7        1.0000  1.0000  1.0000      20   20   20    20   20
                 8        1.0000  1.0000  1.0000       9    9    9     9    9
                 9        1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_count 0        0.9375  0.9688  0.9688      30   31   31    32   32
                 1        0.9605  0.9868  0.9868      73   75   75    76   76
                 2        0.9899  0.9899  1.0000      98   98   99    99   99
                 3        0.9770  0.9885  0.9885      85   86   86    87   87
                 4        0.9494  1.0000  1.0000      75   79   79    79   79
                 5        1.0000  1.0000  1.0000      62   62   62    62   62
                 6        1.0000  1.0000  1.0000      26   26   26    26   26
                 7        0.9600  1.0000  1.0000      24   25   25    25   25
                 8        1.0000  1.0000  1.0000      13   13   13    13   13
                 9        1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count  1        0.9524  0.9524  0.9524      20   20   20    21   21
                 2        0.9559  1.0000  1.0000      65   68   68    68   68
                 3        0.9744  0.9744  0.9872      76   76   77    78   78
                 4        0.9901  0.9901  0.9901     100  100  100   101  101
                 5        0.9524  1.0000  1.0000      60   63   63    63   63
                 6        0.9747  1.0000  1.0000      77   79   79    79   79
                 7        0.9706  1.0000  1.0000      33   34   34    34   34
                 8        1.0000  1.0000  1.0000      30   30   30    30   30
                 9        1.0000  1.0000  1.0000      19   19   19    19   19
                 10       1.0000  1.0000  1.0000       3    3    3     3    3
                 11       1.0000  1.0000  1.0000       4    4    4     4    4


metric                  top5
category         subcat
edit_count       1       332
                 2       146
                 3        22
extra_word_added 0        47
                 1        93
                 2       102
                 3        89
                 4        66
                 5        49
                 6        24
                 7        20
                 8         9
                 9         1
extra_word_count 0        32
                 1        76
                 2        99
                 3        87
                 4        79
                 5        62
                 6        26
                 7        25
                 8        13
                 9         1
part_word_count  1        21
                 2        68
                 3        78
                 4       101
                 5        63
                 6        79
                 7        34
                 8        30
                 9        19
                 10        3
                 11        4

================================================================================

Statistics after processing 1000 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9758  0.9909  0.9909     646  656  656   662  662
                 2        0.9684  0.9895  0.9965     276  282  284   285  285
                 3        0.9787  1.0000  1.0000      46   47   47    47   47
                 4        1.0000  1.0000  1.0000       6    6    6     6    6
extra_word_added 0        0.9495  0.9798  0.9798      94   97   97    99   99
                 1        0.9639  0.9897  0.9897     187  192  192   194  194
                 2        0.9657  0.9886  0.9943     169  173  174   175  175
                 3        0.9844  0.9948  0.9948     189  191  191   192  192
                 4        0.9764  0.9921  1.0000     124  126  127   127  127
                 5        0.9885  1.0000  1.0000      86   87   87    87   87
                 6        1.0000  1.0000  1.0000      61   61   61    61   61
                 7        1.0000  1.0000  1.0000      36   36   36    36   36
                 8        0.9565  0.9565  0.9565      22   22   22    23   23
                 9        1.0000  1.0000  1.0000       5    5    5     5    5
                 10       1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_count 0        0.9492  0.9661  0.9661      56   57   57    59   59
                 1        0.9576  0.9879  0.9879     158  163  163   165  165
                 2        0.9721  0.9888  0.9944     174  177  178   179  179
                 3        0.9838  0.9946  0.9946     182  184  184   185  185
                 4        0.9664  0.9933  1.0000     144  148  149   149  149
                 5        0.9904  1.0000  1.0000     103  104  104   104  104
                 6        1.0000  1.0000  1.0000      74   74   74    74   74
                 7        0.9787  1.0000  1.0000      46   47   47    47   47
                 8        0.9655  0.9655  0.9655      28   28   28    29   29
                 9        1.0000  1.0000  1.0000       6    6    6     6    6
                 10       1.0000  1.0000  1.0000       2    2    2     2    2
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count  1        0.9756  0.9756  0.9756      40   40   40    41   41
                 2        0.9549  0.9850  0.9850     127  131  131   133  133
                 3        0.9669  0.9801  0.9868     146  148  149   151  151
                 4        0.9757  0.9951  0.9951     201  205  205   206  206
                 5        0.9708  0.9927  1.0000     133  136  137   137  137
                 6        0.9767  1.0000  1.0000     126  129  129   129  129
                 7        0.9875  1.0000  1.0000      79   80   80    80   80
                 8        1.0000  1.0000  1.0000      63   63   63    63   63
                 9        1.0000  1.0000  1.0000      37   37   37    37   37
                 10       0.9167  0.9167  0.9167      11   11   11    12   12
                 11       1.0000  1.0000  1.0000       8    8    8     8    8
                 12       1.0000  1.0000  1.0000       2    2    2     2    2
                 15       1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count       1       662
                 2       285
                 3        47
                 4         6
extra_word_added 0        99
                 1       194
                 2       175
                 3       192
                 4       127
                 5        87
                 6        61
                 7        36
                 8        23
                 9         5
                 10        1
extra_word_count 0        59
                 1       165
                 2       179
                 3       185
                 4       149
                 5       104
                 6        74
                 7        47
                 8        29
                 9         6
                 10        2
                 12        1
part_word_count  1        41
                 2       133
                 3       151
                 4       206
                 5       137
                 6       129
                 7        80
                 8        63
                 9        37
                 10       12
                 11        8
                 12        2
                 15        1

================================================================================
***extra_word_added < 0: -1, part: expect much better numbers on James , label: With the upcoming match, there’s a palpable excitement in the air. All signs point to a thrilling showcase of skill and strategy as he steps back onto the court. Expect much better numbers on James home turf this week., edits_made: [((0, 1), (0, 1)), ((5, 6), (5, 7))]

Statistics after processing 1500 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count        1       0.9798  0.9940  0.9940     972  986  986   992  992
                  2       0.9652  0.9907  0.9954     416  427  429   431  431
                  3       0.9855  1.0000  1.0000      68   69   69    69   69
                  4       1.0000  1.0000  1.0000       8    8    8     8    8
extra_word_added -1       1.0000  1.0000  1.0000       1    1    1     1    1
                  0       0.9574  0.9858  0.9858     135  139  139   141  141
                  1       0.9725  0.9931  0.9931     283  289  289   291  291
                  2       0.9659  0.9924  0.9962     255  262  263   264  264
                  3       0.9856  0.9964  0.9964     274  277  277   278  278
                  4       0.9744  0.9897  0.9949     190  193  194   195  195
                  5       0.9924  1.0000  1.0000     131  132  132   132  132
                  6       0.9895  1.0000  1.0000      94   95   95    95   95
                  7       0.9811  1.0000  1.0000      52   53   53    53   53
                  8       0.9722  0.9722  0.9722      35   35   35    36   36
                  9       1.0000  1.0000  1.0000      12   12   12    12   12
                  10      1.0000  1.0000  1.0000       2    2    2     2    2
extra_word_count  0       0.9655  0.9770  0.9770      84   85   85    87   87
                  1       0.9628  0.9917  0.9917     233  240  240   242  242
                  2       0.9703  0.9926  0.9963     261  267  268   269  269
                  3       0.9891  0.9964  0.9964     273  275  275   276  276
                  4       0.9679  0.9954  1.0000     211  217  218   218  218
                  5       0.9875  0.9938  0.9938     158  159  159   160  160
                  6       0.9910  1.0000  1.0000     110  111  111   111  111
                  7       0.9722  1.0000  1.0000      70   72   72    72   72
                  8       0.9778  0.9778  0.9778      44   44   44    45   45
                  9       1.0000  1.0000  1.0000      16   16   16    16   16
                  10      1.0000  1.0000  1.0000       3    3    3     3    3
                  12      1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count   1       0.9841  0.9841  0.9841      62   62   62    63   63
                  2       0.9634  0.9895  0.9895     184  189  189   191  191
                  3       0.9688  0.9866  0.9911     217  221  222   224  224
                  4       0.9776  0.9968  0.9968     306  312  312   313  313
                  5       0.9765  0.9953  1.0000     208  212  213   213  213
                  6       0.9783  1.0000  1.0000     180  184  184   184  184
                  7       0.9735  0.9912  0.9912     110  112  112   113  113
                  8       0.9897  1.0000  1.0000      96   97   97    97   97
                  9       1.0000  1.0000  1.0000      62   62   62    62   62
                  10      0.9565  0.9565  0.9565      22   22   22    23   23
                  11      1.0000  1.0000  1.0000      13   13   13    13   13
                  12      1.0000  1.0000  1.0000       3    3    3     3    3
                  15      1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count        1      992
                  2      431
                  3       69
                  4        8
extra_word_added -1        1
                  0      141
                  1      291
                  2      264
                  3      278
                  4      195
                  5      132
                  6       95
                  7       53
                  8       36
                  9       12
                  10       2
extra_word_count  0       87
                  1      242
                  2      269
                  3      276
                  4      218
                  5      160
                  6      111
                  7       72
                  8       45
                  9       16
                  10       3
                  12       1
part_word_count   1       63
                  2      191
                  3      224
                  4      313
                  5      213
                  6      184
                  7      113
                  8       97
                  9       62
                  10      23
                  11      13
                  12       3
                  15       1

================================================================================

Statistics after processing 2000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9774  0.9947  0.9955    1300  1323  1324  1330
                  2       0.9671  0.9931  0.9965     559   574   576   578
                  3       0.9881  1.0000  1.0000      83    84    84    84
                  4       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9479  0.9896  0.9896     182   190   190   192
                  1       0.9758  0.9946  0.9946     363   370   370   372
                  2       0.9641  0.9917  0.9972     349   359   361   362
                  3       0.9783  0.9973  0.9973     360   367   367   368
                  4       0.9799  0.9920  0.9960     244   247   248   249
                  5       0.9947  1.0000  1.0000     189   190   190   190
                  6       0.9851  1.0000  1.0000     132   134   134   134
                  7       0.9839  1.0000  1.0000      61    62    62    62
                  8       0.9783  0.9783  0.9783      45    45    45    46
                  9       1.0000  1.0000  1.0000      18    18    18    18
                  10      1.0000  1.0000  1.0000       4     4     4     4
                  11      1.0000  1.0000  1.0000       1     1     1     1
                  12      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9508  0.9836  0.9836     116   120   120   122
                  1       0.9651  0.9937  0.9937     304   313   313   315
                  2       0.9668  0.9917  0.9972     349   358   360   361
                  3       0.9889  0.9972  0.9972     355   358   358   359
                  4       0.9713  0.9964  1.0000     271   278   279   279
                  5       0.9910  0.9955  0.9955     220   221   221   222
                  6       0.9762  1.0000  1.0000     164   168   168   168
                  7       0.9773  1.0000  1.0000      86    88    88    88
                  8       0.9818  0.9818  0.9818      54    54    54    55
                  9       1.0000  1.0000  1.0000      23    23    23    23
                  10      1.0000  1.0000  1.0000       5     5     5     5
                  11      1.0000  1.0000  1.0000       1     1     1     1
                  12      1.0000  1.0000  1.0000       2     2     2     2
part_word_count   1       0.9681  0.9894  0.9894      91    93    93    94
                  2       0.9677  0.9919  0.9919     240   246   246   248
                  3       0.9635  0.9867  0.9934     290   297   299   301
                  4       0.9758  0.9976  0.9976     404   413   413   414
                  5       0.9774  0.9962  1.0000     259   264   265   265
                  6       0.9836  1.0000  1.0000     240   244   244   244
                  7       0.9766  0.9942  0.9942     167   170   170   171
                  8       0.9839  1.0000  1.0000     122   124   124   124
                  9       0.9881  1.0000  1.0000      83    84    84    84
                  10      0.9667  0.9667  0.9667      29    29    29    30
                  11      1.0000  1.0000  1.0000      18    18    18    18
                  12      1.0000  1.0000  1.0000       5     5     5     5
                  13      1.0000  1.0000  1.0000       1     1     1     1
                  15      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      1330  1330
                  2       578   578
                  3        84    84
                  4         8     8
extra_word_added -1         1     1
                  0       192   192
                  1       372   372
                  2       362   362
                  3       368   368
                  4       249   249
                  5       190   190
                  6       134   134
                  7        62    62
                  8        46    46
                  9        18    18
                  10        4     4
                  11        1     1
                  12        1     1
extra_word_count  0       122   122
                  1       315   315
                  2       361   361
                  3       359   359
                  4       279   279
                  5       222   222
                  6       168   168
                  7        88    88
                  8        55    55
                  9        23    23
                  10        5     5
                  11        1     1
                  12        2     2
part_word_count   1        94    94
                  2       248   248
                  3       301   301
                  4       414   414
                  5       265   265
                  6       244   244
                  7       171   171
                  8       124   124
                  9        84    84
                  10       30    30
                  11       18    18
                  12        5     5
                  13        1     1
                  15        1     1

================================================================================

Statistics after processing 2500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9772  0.9952  0.9964    1629  1659  1661  1667
                  2       0.9681  0.9917  0.9945     698   715   717   721
                  3       0.9902  1.0000  1.0000     101   102   102   102
                  4       1.0000  1.0000  1.0000      10    10    10    10
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9556  0.9879  0.9879     237   245   245   248
                  1       0.9764  0.9936  0.9936     456   464   464   467
                  2       0.9653  0.9907  0.9977     417   428   431   432
                  3       0.9763  0.9978  0.9978     453   463   463   464
                  4       0.9718  0.9937  0.9969     310   317   318   319
                  5       0.9956  1.0000  1.0000     225   226   226   226
                  6       0.9882  1.0000  1.0000     167   169   169   169
                  7       0.9882  1.0000  1.0000      84    85    85    85
                  8       0.9828  0.9828  0.9828      57    57    57    58
                  9       1.0000  1.0000  1.0000      20    20    20    20
                  10      1.0000  1.0000  1.0000       6     6     6     6
                  11      1.0000  1.0000  1.0000       3     3     3     3
                  12      1.0000  1.0000  1.0000       2     2     2     2
extra_word_count  0       0.9597  0.9866  0.9866     143   147   147   149
                  1       0.9696  0.9949  0.9949     383   393   393   395
                  2       0.9696  0.9907  0.9977     415   424   427   428
                  3       0.9803  0.9956  0.9956     449   456   456   458
                  4       0.9690  0.9972  1.0000     344   354   355   355
                  5       0.9891  0.9964  0.9964     273   275   275   276
                  6       0.9808  1.0000  1.0000     204   208   208   208
                  7       0.9754  0.9918  0.9918     119   121   121   122
                  8       0.9857  0.9857  0.9857      69    69    69    70
                  9       1.0000  1.0000  1.0000      25    25    25    25
                  10      1.0000  1.0000  1.0000       8     8     8     8
                  11      1.0000  1.0000  1.0000       3     3     3     3
                  12      1.0000  1.0000  1.0000       3     3     3     3
part_word_count   1       0.9727  0.9909  0.9909     107   109   109   110
                  2       0.9713  0.9936  0.9936     305   312   312   314
                  3       0.9671  0.9863  0.9945     353   360   363   365
                  4       0.9727  0.9961  0.9961     499   511   511   513
                  5       0.9732  0.9970  1.0000     327   335   336   336
                  6       0.9833  1.0000  1.0000     295   300   300   300
                  7       0.9775  0.9955  0.9955     217   221   221   222
                  8       0.9866  1.0000  1.0000     147   149   149   149
                  9       0.9914  1.0000  1.0000     115   116   116   116
                  10      0.9750  0.9750  0.9750      39    39    39    40
                  11      0.9583  0.9583  0.9583      23    23    23    24
                  12      1.0000  1.0000  1.0000       8     8     8     8
                  13      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      1667  1667
                  2       721   721
                  3       102   102
                  4        10    10
extra_word_added -1         1     1
                  0       248   248
                  1       467   467
                  2       432   432
                  3       464   464
                  4       319   319
                  5       226   226
                  6       169   169
                  7        85    85
                  8        58    58
                  9        20    20
                  10        6     6
                  11        3     3
                  12        2     2
extra_word_count  0       149   149
                  1       395   395
                  2       428   428
                  3       458   458
                  4       355   355
                  5       276   276
                  6       208   208
                  7       122   122
                  8        70    70
                  9        25    25
                  10        8     8
                  11        3     3
                  12        3     3
part_word_count   1       110   110
                  2       314   314
                  3       365   365
                  4       513   513
                  5       336   336
                  6       300   300
                  7       222   222
                  8       149   149
                  9       116   116
                  10       40    40
                  11       24    24
                  12        8     8
                  13        2     2
                  15        1     1

================================================================================
Saved detailed statistics to ./drive/MyDrive/Colab Notebooks/vr-txt-corr/saved_models/text correction (unbounded triplets cursor strategies)/correction_normal_multiple_point_uniform_mask_cursor-relax10/stats_triplets-l-relax10.csv

Final Statistics:

Statistics after processing 2866 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9765  0.9941  0.9957    1825  1858  1861  1869
                  2       0.9683  0.9927  0.9951     795   815   817   821
                  3       0.9913  1.0000  1.0000     114   115   115   115
                  4       1.0000  1.0000  1.0000      11    11    11    11
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9577  0.9859  0.9894     272   280   281   284
                  1       0.9767  0.9942  0.9942     502   511   511   514
                  2       0.9673  0.9898  0.9959     474   485   488   490
                  3       0.9695  0.9962  0.9962     508   522   522   524
                  4       0.9733  0.9947  0.9973     365   373   374   375
                  5       0.9960  1.0000  1.0000     246   247   247   247
                  6       0.9892  1.0000  1.0000     184   186   186   186
                  7       0.9895  1.0000  1.0000      94    95    95    95
                  8       0.9844  0.9844  0.9844      63    63    63    64
                  9       1.0000  1.0000  1.0000      23    23    23    23
                  10      1.0000  1.0000  1.0000       8     8     8     8
                  11      1.0000  1.0000  1.0000       3     3     3     3
                  12      1.0000  1.0000  1.0000       2     2     2     2
extra_word_count  0       0.9588  0.9824  0.9882     163   167   168   170
                  1       0.9720  0.9953  0.9953     416   426   426   428
                  2       0.9692  0.9897  0.9959     472   482   485   487
                  3       0.9770  0.9942  0.9942     509   518   518   521
                  4       0.9685  0.9976  1.0000     400   412   413   413
                  5       0.9901  0.9967  0.9967     299   301   301   302
                  6       0.9786  1.0000  1.0000     229   234   234   234
                  7       0.9779  0.9926  0.9926     133   135   135   136
                  8       0.9873  0.9873  0.9873      78    78    78    79
                  9       1.0000  1.0000  1.0000      29    29    29    29
                  10      1.0000  1.0000  1.0000      10    10    10    10
                  11      1.0000  1.0000  1.0000       3     3     3     3
                  12      1.0000  1.0000  1.0000       3     3     3     3
                  13      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9688  0.9844  0.9922     124   126   127   128
                  2       0.9735  0.9941  0.9941     331   338   338   340
                  3       0.9707  0.9878  0.9951     397   404   407   409
                  4       0.9671  0.9931  0.9931     559   574   574   578
                  5       0.9747  0.9975  1.0000     385   394   395   395
                  6       0.9820  1.0000  1.0000     327   333   333   333
                  7       0.9800  0.9960  0.9960     245   249   249   250
                  8       0.9880  1.0000  1.0000     165   167   167   167
                  9       0.9846  1.0000  1.0000     128   130   130   130
                  10      0.9787  0.9787  0.9787      46    46    46    47
                  11      0.9600  0.9600  0.9600      24    24    24    25
                  12      1.0000  1.0000  1.0000      10    10    10    10
                  13      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      1869  1869
                  2       821   821
                  3       115   115
                  4        11    11
extra_word_added -1         1     1
                  0       284   284
                  1       514   514
                  2       490   490
                  3       524   524
                  4       375   375
                  5       247   247
                  6       186   186
                  7        95    95
                  8        64    64
                  9        23    23
                  10        8     8
                  11        3     3
                  12        2     2
extra_word_count  0       170   170
                  1       428   428
                  2       487   487
                  3       521   521
                  4       413   413
                  5       302   302
                  6       234   234
                  7       136   136
                  8        79    79
                  9        29    29
                  10       10    10
                  11        3     3
                  12        3     3
                  13        1     1
part_word_count   1       128   128
                  2       340   340
                  3       409   409
                  4       578   578
                  5       395   395
                  6       333   333
                  7       250   250
                  8       167   167
                  9       130   130
                  10       47    47
                  11       25    25
                  12       10    10
                  13        2     2
                  15        2     2

================================================================================

test evaluation:
{'test_sample_size': 2816, 'test_loss': 0.005093312356621027, 'test_cer_unfiltered': 0.00042399753574081793, 'test_cer_filtered': 0.0003315878164126909, 'test_tkacc_unfiltered/t1acc': 0.9666193181818182, 'test_tkacc_unfiltered/t3acc': 0.9904119318181818, 'test_tkacc_unfiltered/t5acc': 0.9936079545454546, 'test_tkacc_filtered/t1acc': 0.9747869318181818, 'test_tkacc_filtered/t3acc': 0.9939630681818182, 'test_tkacc_filtered/t5acc': 0.9957386363636364, 'test_runtime': 2869.7922, 'test_samples_per_second': 0.999, 'test_steps_per_second': 0.25, 'eval_bloss': None}

triplet classes: ['m']
preparing data from ./drive/MyDrive/Colab Notebooks/vr-txt-corr/corr_datasets_experimental/DELETION-INSERTION-MULTIPLE-REPLACEMENT-SINGLE/triplet_test_data_relax10_correction_dev5_stats.csv ...
	reading data ... filtering triplet classes...original len: 25246
updated len: 20880
updated len after dropping nan: 20880
sampling ...
done
model vocab size: 32100
tokenizer vocab: 32100

/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:444: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(

[("The final trading hours of the day will be crucial in determining the market's direction. Some million ahares changed hands on the New York Stoke. Some million shares changed hands on the New York Stock Exchange as investors reacted to the shifting landscape.", 'new York Stock.', '[((2, 3), (2, 3)), ((9, 10), (9, 10))]', '[((9, 10), (9, 10))]'), ('Everyone felt a sense of pride, knowing their city would be in the global spotlight. Thr city plays host to a visit by US president Bill Clinton. As the day approached, decorations began to adorn the streets, transforming the city into a vibrant display of color and excitement.', 'the city', '[((0, 1), (0, 1))]', '[((0, 1), (0, 1))]'), ('With hearts full of gratitude, we acknowledged that this moment was one we would cherish forever. Both of us arestill here. The warmth of the setting sun embraced us as we sat in comfortable silence, realizing how fortunate we were to have each other.', 'both of us are still here.', '[((3, 4), (3, 5))]', '[((3, 4), (3, 5))]'), ('Maybe we could plan something soon? But I hope to see you at Katis’s store. I remember how we used to spend hours just lounging in the sun, completely lost in laughter and friendship.', "Hope to see you at Kari's house.", '[((7, 9), (7, 9))]', '[((7, 9), (7, 9))]'), ('The group ultimately decided to wait for official word before making any assumptions. Webster that package is training or material has yet to be determined. The anticipation in the room was palpable as everyone reflected on the potential implications of the package.', 'whether that package is', '[((0, 1), (0, 1))]', '[((0, 1), (0, 1))]'), ('As I reached for my phone again, I took a deep breath and tried dialing your number once more. Tried to call you but couldn’t reach you. As I set my phone down, my thoughts drifted to the plans we had discussed.', "call but couldn't reach", '[((3, 4), (3, 3)), ((5, 6), (4, 5))]', '[((5, 6), (4, 5)), ((3, 4), (3, 3))]'), ('Each morning, I woke up more hopeful and excited for what the day would bring. Im fully recovered and back on peace. With renewed energy, I started reconnecting with friends, organizing weekend get-togethers that had long been missed.', 'pace.', '[((0, 1), (0, 1)), ((6, 7), (6, 7))]', '[((6, 7), (6, 7))]'), ('I took a deep breath, steeling myself for the possibility that it may never work again. I’Lil presume it is dead until I hear otherwise. The decision weighed heavily on my heart as I turned away from the machine.', "i'll presume", '[((0, 1), (0, 1))]', '[((0, 1), (0, 1))]'), ('Anticipation built as the lights dimmed, signaling the next exciting phase of the evening. The ceremony was followex by the premiere of the opening film. The atmosphere crackled with anticipation as the curtains drew back, revealing the stunning set and thrilling visuals of the film.', 'the ceremony was followed by the', '[((3, 4), (3, 4))]', '[((3, 4), (3, 4))]'), ('Everyone is hopeful that he will return to full strength soon. Heis listed as day to day. His current status puts the coaching staff in a difficult position as they prepare their strategy.', 'he is listed as day to day.', '[((0, 1), (0, 2))]', '[((0, 1), (0, 2))]')]
True
False
skipped (sent: |Would you like me to reach out to him for us? I'll bug HOlloway and let you know what he says. In the meantime, we should also reflect on the current data we have gathered and identify any gaps that need addressing.|, phra: |know what he says.|)
cbefo: |Would you like me to reach out to him for us? I'll bug HOlloway and let you know what he says In the meantime, we should also reflect on the current data we have gathered and identify any gaps that need addressing.|
cafte: |[]|
label: |Would you like me to reach out to him for us? I'll bug HOlloway and let you know what he says In the meantime, we should also reflect on the current data we have gathered and identify any gaps that need addressing.|
True
False
skipped (sent: |We can't wait to share the final product with you! watch for more details,coming soon. Our team has been working tirelessly to perfect every aspect of this project, and we believe it will revolutionize the way you engage with us.|, phra: |more details, coming soon.|)
cbefo: |We can't wait to share the final product with you! watch for more details, coming soon Our team has been working tirelessly to perfect every aspect of this project, and we believe it will revolutionize the way you engage with us.|
cafte: |["We can't wait to share the final product with you! watch for more details, coming soon. Our team has been working tirelessly to perfect every aspect of this project, and we believe it will revolutionize the way you engage with us."]|
label: |We can't wait to share the final product with you! watch for more details, coming soon Our team has been working tirelessly to perfect every aspect of this project, and we believe it will revolutionize the way you engage with us.|
True
False
skipped (sent: |Just as I was about to send you a quick message, I decided I should check in on you first. Hey TK,how are you doing. I hope life has been treating you well lately.|, phra: |doing.|)
cbefo: |Just as I was about to send you a quick message, I decided I should check in on you first. Hey TK,how are you doing I hope life has been treating you well lately.|
cafte: |['Just as I was about to send you a quick message, I decided I should check in on you first. Hey TK,how are you doing... I hope life has been treating you well lately.']|
label: |Just as I was about to send you a quick message, I decided I should check in on you first. Hey TK,how are you doing I hope life has been treating you well lately.|
True
False
skipped (sent: |After the injection was administered, it was time for monitoring and assessment. He will be re-evaluated after receiving his injection. The doctor emphasized the importance of follow-up appointments to track the patient's progress and response to the treatment.|, phra: |An injection.|)
cbefo: |After the injection was administered, it was time for monitoring and assessment. He will be re-evaluated after receiving an injection The doctor emphasized the importance of follow-up appointments to track the patient's progress and response to the treatment.|
cafte: |["After the injection was administered, it was time for monitoring and assessment. He will be re-evaluated after receiving an injection. The doctor emphasized the importance of follow-up appointments to track the patient's progress and response to the treatment."]|
label: |After the injection was administered, it was time for monitoring and assessment. He will be re-evaluated after receiving an injection The doctor emphasized the importance of follow-up appointments to track the patient's progress and response to the treatment.|
True
False
skipped (sent: |Everyone is waiting for clarity on the situation. Whether that package is trainging or material has yet to be determined. The team has divided the packages into two categories to expedite the review process.|, phra: |Yet to be determined.|)
cbefo: |Everyone is waiting for clarity on the situation. Whether that package is trainging or material has yet to be determined The team has divided the packages into two categories to expedite the review process.|
cafte: |[]|
label: |Everyone is waiting for clarity on the situation. Whether that package is trainging or material has yet to be determined The team has divided the packages into two categories to expedite the review process.|
True
False
skipped (sent: |The forest feels different, as if it too has mourned the absence of the creature, and I begin to fear the worst. I'll presume it is dead until I hear otherwise. The thought weighed heavily on my heart as I surveyed the surrounding trees, their gnarled roots resembling the twisted emotions within me.|, phra: |i hear otherwise.|)
cbefo: |The forest feels different, as if it too has mourned the absence of the creature, and I begin to fear the worst. I'll presume it is dead until I hear otherwise The thought weighed heavily on my heart as I surveyed the surrounding trees, their gnarled roots resembling the twisted emotions within me.|
cafte: |[]|
label: |The forest feels different, as if it too has mourned the absence of the creature, and I begin to fear the worst. I'll presume it is dead until I hear otherwise The thought weighed heavily on my heart as I surveyed the surrounding trees, their gnarled roots resembling the twisted emotions within me.|
True
False
skipped (sent: |Overall, the sentiment among industry insiders remained hopeful for the upcoming quarter. He said Telecom was still in a a position of substantial protection z. This protection stems from the robust customer base that many established firms have cultivated over the years.|, phra: |Telecom was still in a position of substantial protection.|)
cbefo: |Overall, the sentiment among industry insiders remained hopeful for the upcoming quarter. He said Telecom was still in a position of substantial protection This protection stems from the robust customer base that many established firms have cultivated over the years.|
cafte: |['Overall, the sentiment among industry insiders remained hopeful for the upcoming quarter. He said Telecom was still in a position of substantial protection. This protection stems from the robust customer base that many established firms have cultivated over the years.']|
label: |Overall, the sentiment among industry insiders remained hopeful for the upcoming quarter. He said Telecom was still in a position of substantial protection This protection stems from the robust customer base that many established firms have cultivated over the years.|
True
False
skipped (sent: |We can't wait to share what we've been crafting just for you. Watch for more details, coming soon. In the coming days, we will unveil the results of our hard work, and we’re confident that you’ll be impressed.|, phra: |details, coming soon.|)
cbefo: |We can't wait to share what we've been crafting just for you. Watch for more details, coming soon In the coming days, we will unveil the results of our hard work, and we’re confident that you’ll be impressed.|
cafte: |[]|
label: |We can't wait to share what we've been crafting just for you. Watch for more details, coming soon In the coming days, we will unveil the results of our hard work, and we’re confident that you’ll be impressed.|
True
False
skipped (sent: |Let’s regroup and brainstorm some new ideas moving forward. Theresa, I’ve redrafted and we’re still off, even more now. The original vision feels lost amidst the changes we’ve made.|, phra: |I've redrafted and we're still off, even more now.|)
cbefo: |Let’s regroup and brainstorm some new ideas moving forward. Theresa, I've redrafted and we're still off, even more now The original vision feels lost amidst the changes we’ve made.|
cafte: |["Let’s regroup and brainstorm some new ideas moving forward. Theresa, I've redrafted and we're still off, even more now. The original vision feels lost amidst the changes we’ve made."]|
label: |Let’s regroup and brainstorm some new ideas moving forward. Theresa, I've redrafted and we're still off, even more now The original vision feels lost amidst the changes we’ve made.|
True
False
skipped (sent: |Eventually, his perseverance and hard work paid off, leading him to a series of remarkable victories. Mansell went on to five Indy-car triumphs. His success in Indy-car racing not only reaffirmed his abilities but also showcased his versatility as a driver.|, phra: |went on to five Indy-car triumphs.|)
cbefo: |Eventually, his perseverance and hard work paid off, leading him to a series of remarkable victories. Mansell went on to five Indy-car triumphs His success in Indy-car racing not only reaffirmed his abilities but also showcased his versatility as a driver.|
cafte: |[]|
label: |Eventually, his perseverance and hard work paid off, leading him to a series of remarkable victories. Mansell went on to five Indy-car triumphs His success in Indy-car racing not only reaffirmed his abilities but also showcased his versatility as a driver.|
True
False
skipped (sent: |In his presence, the office feels more like a community than just a place to work. nick makes work fun. His playful spirit encourages everyone to share their ideas without fear of judgment.|, phra: |Nick makes work fun.|)
cbefo: |In his presence, the office feels more like a community than just a place to work. Nick makes work fun His playful spirit encourages everyone to share their ideas without fear of judgment.|
cafte: |['In his presence, the office feels more like a community than just a place to work. Nick makes work fun. His playful spirit encourages everyone to share their ideas without fear of judgment.']|
label: |In his presence, the office feels more like a community than just a place to work. Nick makes work fun His playful spirit encourages everyone to share their ideas without fear of judgment.|
True
False
skipped (sent: |Ultimately, prioritizing clarity and conciseness became my main goal. Finally, I would delete yhe paragraph about lawyers. Instead, I contemplated adding a case study that exemplified modern legal practices, which could resonate better with the audience.|, phra: |The paragraph about lawyers.|)
cbefo: |Ultimately, prioritizing clarity and conciseness became my main goal. Finally, I would delete the paragraph about lawyers Instead, I contemplated adding a case study that exemplified modern legal practices, which could resonate better with the audience.|
cafte: |['Ultimately, prioritizing clarity and conciseness became my main goal. Finally, I would delete the paragraph about lawyers. Instead, I contemplated adding a case study that exemplified modern legal practices, which could resonate better with the audience.']|
label: |Ultimately, prioritizing clarity and conciseness became my main goal. Finally, I would delete the paragraph about lawyers Instead, I contemplated adding a case study that exemplified modern legal practices, which could resonate better with the audience.|
True
False
skipped (sent: |Moving forward, I will have to adapt to the new situation. Amy will no longer be here so I will be the only one working on this l. This change puts additional pressure on me, but I am determined to see it through.|, phra: |One working on this.|)
cbefo: |Moving forward, I will have to adapt to the new situation. Amy will no longer be here so I will be the only one working on this This change puts additional pressure on me, but I am determined to see it through.|
cafte: |['Moving forward, I will have to adapt to the new situation. Amy will no longer be here so I will be the only one working on this. This change puts additional pressure on me, but I am determined to see it through.', 'Moving forward, I will have to adapt to the new situation. Amy will no longer be here so I will be the only one working on this. This change puts additional pressure on me, but I am determined to see it through!']|
label: |Moving forward, I will have to adapt to the new situation. Amy will no longer be here so I will be the only one working on this This change puts additional pressure on me, but I am determined to see it through.|
True
False
skipped (sent: |The open road ahead promised new experiences and unforgettable memories. We're on the way. The group set off, their spirits high and hearts racing with anticipation.|, phra: |We're on the way.|)
cbefo: |The open road ahead promised new experiences and unforgettable memories. We're on the way The group set off, their spirits high and hearts racing with anticipation.|
cafte: |[]|
label: |The open road ahead promised new experiences and unforgettable memories. We're on the way The group set off, their spirits high and hearts racing with anticipation.|
True
False
skipped (sent: |Little did anyone know, this season would become one for the history books. History repeated itself last season when Tenerife beat Madrid. The victory sent shockwaves through the league, as many saw it as a fluke.|, phra: |Beat Madrid.|)
cbefo: |Little did anyone know, this season would become one for the history books. History repeated itself last season when Tenerife beat Madrid The victory sent shockwaves through the league, as many saw it as a fluke.|
cafte: |[]|
label: |Little did anyone know, this season would become one for the history books. History repeated itself last season when Tenerife beat Madrid The victory sent shockwaves through the league, as many saw it as a fluke.|
True
False
skipped (sent: |This will be the first time we all come together since the pandemic. I will get the gathering to Gloria tomorrow. I also need to prepare a small welcome speech to make everyone feel special.|, phra: |i will get the gathering to Gloria tomorrow.|)
cbefo: |This will be the first time we all come together since the pandemic. I will get the gathering to Gloria tomorrow I also need to prepare a small welcome speech to make everyone feel special.|
cafte: |[]|
label: |This will be the first time we all come together since the pandemic. I will get the gathering to Gloria tomorrow I also need to prepare a small welcome speech to make everyone feel special.|
True
False
skipped (sent: |A hush fell over the office as the clock neared the announcement time. mixed signals from APS today. Whispers spread quickly as employees interpreted the phrase in various ways.|, phra: |mixed signals from APS today.|)
cbefo: |A hush fell over the office as the clock neared the announcement time. Mixed signals from APS today Whispers spread quickly as employees interpreted the phrase in various ways.|
cafte: |['A hush fell over the office as the clock neared the announcement time. Mixed signals from APS today. Whispers spread quickly as employees interpreted the phrase in various ways.']|
label: |A hush fell over the office as the clock neared the announcement time. Mixed signals from APS today Whispers spread quickly as employees interpreted the phrase in various ways.|
True
False
skipped (sent: |As the sun set over the Mersey, the lights of the stadium glimmered, reminding all of the dreams and realities that collided in this iconic place. Liverpool always has a knack of bringing people down. The laughter of friends gathered in pubs echoed around the brick-lined streets, where conversations about life, love, and football seamlessly intertwined.|, phra: |Knack of bringing people down to earth.|)
cbefo: |As the sun set over the Mersey, the lights of the stadium glimmered, reminding all of the dreams and realities that collided in this iconic place. Liverpool always has a knack of bringing people down to earth. The laughter of friends gathered in pubs echoed around the brick-lined streets, where conversations about life, love, and football seamlessly intertwined.|

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count       1        0.9913  0.9942  0.9942     340  341  341   343  343
                 2        1.0000  1.0000  1.0000     129  129  129   129  129
                 3        0.9565  1.0000  1.0000      22   23   23    23   23
                 4        0.7500  0.7500  0.7500       3    3    3     4    4
                 5        1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_added 0        0.9200  0.9200  0.9200      23   23   23    25   25
                 1        0.9706  1.0000  1.0000      66   68   68    68   68
                 2        1.0000  1.0000  1.0000      70   70   70    70   70
                 3        1.0000  1.0000  1.0000      75   75   75    75   75
                 4        1.0000  1.0000  1.0000      79   79   79    79   79
                 5        1.0000  1.0000  1.0000      62   62   62    62   62
                 6        0.9778  0.9778  0.9778      44   44   44    45   45
                 7        1.0000  1.0000  1.0000      43   43   43    43   43
                 8        1.0000  1.0000  1.0000      16   16   16    16   16
                 9        1.0000  1.0000  1.0000       6    6    6     6    6
                 10       1.0000  1.0000  1.0000       8    8    8     8    8
                 11       1.0000  1.0000  1.0000       2    2    2     2    2
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_count 0        0.9231  0.9231  0.9231      12   12   12    13   13
                 1        0.9615  1.0000  1.0000      50   52   52    52   52
                 2        0.9818  0.9818  0.9818      54   54   54    55   55
                 3        1.0000  1.0000  1.0000      75   75   75    75   75
                 4        1.0000  1.0000  1.0000      85   85   85    85   85
                 5        1.0000  1.0000  1.0000      74   74   74    74   74
                 6        0.9818  0.9818  0.9818      54   54   54    55   55
                 7        1.0000  1.0000  1.0000      49   49   49    49   49
                 8        1.0000  1.0000  1.0000      22   22   22    22   22
                 9        1.0000  1.0000  1.0000       8    8    8     8    8
                 10       1.0000  1.0000  1.0000       8    8    8     8    8
                 11       1.0000  1.0000  1.0000       2    2    2     2    2
                 12       1.0000  1.0000  1.0000       1    1    1     1    1
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count  1        0.9091  0.9091  0.9091      10   10   10    11   11
                 2        0.9744  1.0000  1.0000      38   39   39    39   39
                 3        1.0000  1.0000  1.0000      57   57   57    57   57
                 4        0.9710  0.9855  0.9855      67   68   68    69   69
                 5        1.0000  1.0000  1.0000      78   78   78    78   78
                 6        1.0000  1.0000  1.0000      68   68   68    68   68
                 7        0.9836  0.9836  0.9836      60   60   60    61   61
                 8        1.0000  1.0000  1.0000      54   54   54    54   54
                 9        1.0000  1.0000  1.0000      28   28   28    28   28
                 10       1.0000  1.0000  1.0000      17   17   17    17   17
                 11       1.0000  1.0000  1.0000      14   14   14    14   14
                 12       1.0000  1.0000  1.0000       2    2    2     2    2
                 13       1.0000  1.0000  1.0000       1    1    1     1    1
                 15       1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count       1       343
                 2       129
                 3        23
                 4         4
                 5         1
extra_word_added 0        25
                 1        68
                 2        70
                 3        75
                 4        79
                 5        62
                 6        45
                 7        43
                 8        16
                 9         6
                 10        8
                 11        2
                 12        1
extra_word_count 0        13
                 1        52
                 2        55
                 3        75
                 4        85
                 5        74
                 6        55
                 7        49
                 8        22
                 9         8
                 10        8
                 11        2
                 12        1
                 13        1
part_word_count  1        11
                 2        39
                 3        57
                 4        69
                 5        78
                 6        68
                 7        61
                 8        54
                 9        28
                 10       17
                 11       14
                 12        2
                 13        1
                 15        1

================================================================================
***extra_word_added < 0: -1, part: expect much better numbers on James home turf, label: Confidence is high, and the mood in the locker room is electric. Expect much better numbers on James home turf this week. As the players take to the field, the energy is palpable, and the atmosphere crackles with anticipation., edits_made: [((0, 1), (0, 1)), ((6, 6), (6, 7)), ((7, 8), (8, 9))]

Statistics after processing 1000 samples:
================================================================================

                        accuracy                 matches           total       \
metric                      top1    top3    top5    top1 top3 top5  top1 top3
category         subcat
edit_count        1       0.9838  0.9897  0.9897     668  672  672   679  679
                  2       0.9888  0.9963  0.9963     265  267  267   268  268
                  3       0.9348  0.9565  0.9565      43   44   44    46   46
                  4       0.6667  0.8333  0.8333       4    5    5     6    6
                  5       1.0000  1.0000  1.0000       1    1    1     1    1
extra_word_added -1       1.0000  1.0000  1.0000       1    1    1     1    1
                  0       0.9091  0.9273  0.9273      50   51   51    55   55
                  1       0.9737  1.0000  1.0000     111  114  114   114  114
                  2       0.9695  0.9847  0.9847     127  129  129   131  131
                  3       0.9812  0.9812  0.9812     157  157  157   160  160
                  4       0.9935  1.0000  1.0000     154  155  155   155  155
                  5       1.0000  1.0000  1.0000     133  133  133   133  133
                  6       0.9808  0.9808  0.9808     102  102  102   104  104
                  7       0.9861  1.0000  1.0000      71   72   72    72   72
                  8       1.0000  1.0000  1.0000      33   33   33    33   33
                  9       1.0000  1.0000  1.0000      21   21   21    21   21
                  10      1.0000  1.0000  1.0000      15   15   15    15   15
                  11      1.0000  1.0000  1.0000       3    3    3     3    3
                  12      1.0000  1.0000  1.0000       3    3    3     3    3
extra_word_count  0       0.8571  0.8929  0.8929      24   25   25    28   28
                  1       0.9634  1.0000  1.0000      79   82   82    82   82
                  2       0.9626  0.9720  0.9720     103  104  104   107  107
                  3       0.9880  0.9880  0.9880     164  164  164   166  166
                  4       0.9938  0.9938  0.9938     161  161  161   162  162
                  5       0.9935  1.0000  1.0000     153  154  154   154  154
                  6       0.9837  0.9837  0.9837     121  121  121   123  123
                  7       0.9773  1.0000  1.0000      86   88   88    88   88
                  8       1.0000  1.0000  1.0000      41   41   41    41   41
                  9       1.0000  1.0000  1.0000      24   24   24    24   24
                  10      1.0000  1.0000  1.0000      18   18   18    18   18
                  11      1.0000  1.0000  1.0000       3    3    3     3    3
                  12      1.0000  1.0000  1.0000       3    3    3     3    3
                  13      1.0000  1.0000  1.0000       1    1    1     1    1
part_word_count   1       0.8182  0.8636  0.8636      18   19   19    22   22
                  2       0.9846  1.0000  1.0000      64   65   65    65   65
                  3       0.9688  0.9792  0.9792      93   94   94    96   96
                  4       0.9724  0.9862  0.9862     141  143  143   145  145
                  5       0.9939  0.9939  0.9939     163  163  163   164  164
                  6       0.9931  0.9931  0.9931     143  143  143   144  144
                  7       0.9855  0.9855  0.9855     136  136  136   138  138
                  8       0.9794  1.0000  1.0000      95   97   97    97   97
                  9       0.9839  1.0000  1.0000      61   62   62    62   62
                  10      1.0000  1.0000  1.0000      33   33   33    33   33
                  11      1.0000  1.0000  1.0000      24   24   24    24   24
                  12      1.0000  1.0000  1.0000       5    5    5     5    5
                  13      1.0000  1.0000  1.0000       4    4    4     4    4
                  15      1.0000  1.0000  1.0000       1    1    1     1    1


metric                  top5
category         subcat
edit_count        1      679
                  2      268
                  3       46
                  4        6
                  5        1
extra_word_added -1        1
                  0       55
                  1      114
                  2      131
                  3      160
                  4      155
                  5      133
                  6      104
                  7       72
                  8       33
                  9       21
                  10      15
                  11       3
                  12       3
extra_word_count  0       28
                  1       82
                  2      107
                  3      166
                  4      162
                  5      154
                  6      123
                  7       88
                  8       41
                  9       24
                  10      18
                  11       3
                  12       3
                  13       1
part_word_count   1       22
                  2       65
                  3       96
                  4      145
                  5      164
                  6      144
                  7      138
                  8       97
                  9       62
                  10      33
                  11      24
                  12       5
                  13       4
                  15       1

================================================================================

Statistics after processing 1500 samples:
================================================================================

                        accuracy                 matches           total  \
metric                      top1    top3    top5    top1 top3 top5  top1
category         subcat
edit_count        1       0.9820  0.9910  0.9910     984  993  993  1002
                  2       0.9783  0.9904  0.9928     406  411  412   415
                  3       0.9595  0.9730  0.9730      71   72   72    74
                  4       0.7500  0.8750  0.8750       6    7    7     8
                  5       1.0000  1.0000  1.0000       1    1    1     1
extra_word_added -1       1.0000  1.0000  1.0000       1    1    1     1
                  0       0.8987  0.9367  0.9494      71   74   75    79
                  1       0.9752  1.0000  1.0000     157  161  161   161
                  2       0.9635  0.9844  0.9844     185  189  189   192
                  3       0.9794  0.9835  0.9835     238  239  239   243
                  4       0.9836  0.9918  0.9918     240  242  242   244
                  5       1.0000  1.0000  1.0000     197  197  197   197
                  6       0.9875  0.9875  0.9875     158  158  158   160
                  7       0.9904  1.0000  1.0000     103  104  104   104
                  8       0.9821  1.0000  1.0000      55   56   56    56
                  9       1.0000  1.0000  1.0000      30   30   30    30
                  10      1.0000  1.0000  1.0000      23   23   23    23
                  11      1.0000  1.0000  1.0000       6    6    6     6
                  12      1.0000  1.0000  1.0000       4    4    4     4
extra_word_count  0       0.8684  0.8947  0.9211      33   34   35    38
                  1       0.9580  1.0000  1.0000     114  119  119   119
                  2       0.9487  0.9744  0.9744     148  152  152   156
                  3       0.9839  0.9880  0.9880     245  246  246   249
                  4       0.9846  0.9884  0.9884     255  256  256   259
                  5       0.9954  1.0000  1.0000     215  216  216   216
                  6       0.9894  0.9894  0.9894     187  187  187   189
                  7       0.9846  1.0000  1.0000     128  130  130   130
                  8       0.9848  1.0000  1.0000      65   66   66    66
                  9       1.0000  1.0000  1.0000      38   38   38    38
                  10      1.0000  1.0000  1.0000      28   28   28    28
                  11      1.0000  1.0000  1.0000       6    6    6     6
                  12      1.0000  1.0000  1.0000       4    4    4     4
                  13      1.0000  1.0000  1.0000       2    2    2     2
part_word_count   1       0.8214  0.8571  0.8929      23   24   25    28
                  2       0.9789  1.0000  1.0000      93   95   95    95
                  3       0.9640  0.9784  0.9784     134  136  136   139
                  4       0.9676  0.9907  0.9907     209  214  214   216
                  5       0.9764  0.9843  0.9843     248  250  250   254
                  6       0.9953  0.9953  0.9953     214  214  214   215
                  7       0.9902  0.9902  0.9902     202  202  202   204
                  8       0.9865  1.0000  1.0000     146  148  148   148
                  9       0.9796  1.0000  1.0000      96   98   98    98
                  10      1.0000  1.0000  1.0000      47   47   47    47
                  11      1.0000  1.0000  1.0000      38   38   38    38
                  12      1.0000  1.0000  1.0000      10   10   10    10
                  13      1.0000  1.0000  1.0000       6    6    6     6
                  15      1.0000  1.0000  1.0000       2    2    2     2


metric                   top3  top5
category         subcat
edit_count        1      1002  1002
                  2       415   415
                  3        74    74
                  4         8     8
                  5         1     1
extra_word_added -1         1     1
                  0        79    79
                  1       161   161
                  2       192   192
                  3       243   243
                  4       244   244
                  5       197   197
                  6       160   160
                  7       104   104
                  8        56    56
                  9        30    30
                  10       23    23
                  11        6     6
                  12        4     4
extra_word_count  0        38    38
                  1       119   119
                  2       156   156
                  3       249   249
                  4       259   259
                  5       216   216
                  6       189   189
                  7       130   130
                  8        66    66
                  9        38    38
                  10       28    28
                  11        6     6
                  12        4     4
                  13        2     2
part_word_count   1        28    28
                  2        95    95
                  3       139   139
                  4       216   216
                  5       254   254
                  6       215   215
                  7       204   204
                  8       148   148
                  9        98    98
                  10       47    47
                  11       38    38
                  12       10    10
                  13        6     6
                  15        2     2

================================================================================

Statistics after processing 2000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9799  0.9918  0.9925    1315  1331  1332  1342
                  2       0.9743  0.9890  0.9908     530   538   539   544
                  3       0.9706  0.9804  0.9804      99   100   100   102
                  4       0.8182  0.9091  0.9091       9    10    10    11
                  5       1.0000  1.0000  1.0000       1     1     1     1
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9074  0.9444  0.9630      98   102   104   108
                  1       0.9763  1.0000  1.0000     206   211   211   211
                  2       0.9672  0.9854  0.9854     265   270   270   274
                  3       0.9787  0.9878  0.9878     321   324   324   328
                  4       0.9807  0.9904  0.9904     305   308   308   311
                  5       1.0000  1.0000  1.0000     245   245   245   245
                  6       0.9779  0.9867  0.9867     221   223   223   226
                  7       0.9857  1.0000  1.0000     138   140   140   140
                  8       0.9859  1.0000  1.0000      70    71    71    71
                  9       0.9737  1.0000  1.0000      37    38    38    38
                  10      1.0000  1.0000  1.0000      30    30    30    30
                  11      1.0000  1.0000  1.0000      10    10    10    10
                  12      1.0000  1.0000  1.0000       5     5     5     5
                  13      1.0000  1.0000  1.0000       2     2     2     2
extra_word_count  0       0.8824  0.9020  0.9412      45    46    48    51
                  1       0.9625  1.0000  1.0000     154   160   160   160
                  2       0.9554  0.9777  0.9777     214   219   219   224
                  3       0.9786  0.9908  0.9908     320   324   324   327
                  4       0.9851  0.9910  0.9910     330   332   332   335
                  5       0.9929  0.9964  0.9964     279   280   280   281
                  6       0.9810  0.9886  0.9886     258   260   260   263
                  7       0.9826  1.0000  1.0000     169   172   172   172
                  8       0.9880  1.0000  1.0000      82    83    83    83
                  9       0.9796  1.0000  1.0000      48    49    49    49
                  10      1.0000  1.0000  1.0000      35    35    35    35
                  11      1.0000  1.0000  1.0000      10    10    10    10
                  12      1.0000  1.0000  1.0000       6     6     6     6
                  13      1.0000  1.0000  1.0000       4     4     4     4
part_word_count   1       0.8421  0.8684  0.9211      32    33    35    38
                  2       0.9846  1.0000  1.0000     128   130   130   130
                  3       0.9643  0.9796  0.9796     189   192   192   196
                  4       0.9652  0.9930  0.9930     277   285   285   287
                  5       0.9752  0.9876  0.9876     315   319   319   323
                  6       0.9965  0.9965  0.9965     282   282   282   283
                  7       0.9789  0.9860  0.9860     279   281   281   285
                  8       0.9844  1.0000  1.0000     189   192   192   192
                  9       0.9844  1.0000  1.0000     126   128   128   128
                  10      1.0000  1.0000  1.0000      61    61    61    61
                  11      0.9804  1.0000  1.0000      50    51    51    51
                  12      1.0000  1.0000  1.0000      13    13    13    13
                  13      1.0000  1.0000  1.0000      10    10    10    10
                  14      1.0000  1.0000  1.0000       1     1     1     1
                  15      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      1342  1342
                  2       544   544
                  3       102   102
                  4        11    11
                  5         1     1
extra_word_added -1         1     1
                  0       108   108
                  1       211   211
                  2       274   274
                  3       328   328
                  4       311   311
                  5       245   245
                  6       226   226
                  7       140   140
                  8        71    71
                  9        38    38
                  10       30    30
                  11       10    10
                  12        5     5
                  13        2     2
extra_word_count  0        51    51
                  1       160   160
                  2       224   224
                  3       327   327
                  4       335   335
                  5       281   281
                  6       263   263
                  7       172   172
                  8        83    83
                  9        49    49
                  10       35    35
                  11       10    10
                  12        6     6
                  13        4     4
part_word_count   1        38    38
                  2       130   130
                  3       196   196
                  4       287   287
                  5       323   323
                  6       283   283
                  7       285   285
                  8       192   192
                  9       128   128
                  10       61    61
                  11       51    51
                  12       13    13
                  13       10    10
                  14        1     1
                  15        2     2

================================================================================

Statistics after processing 2500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9785  0.9904  0.9916    1637  1657  1659  1673
                  2       0.9723  0.9869  0.9898     666   676   678   685
                  3       0.9766  0.9844  0.9844     125   126   126   128
                  4       0.8333  0.9167  0.9167      10    11    11    12
                  5       1.0000  1.0000  1.0000       2     2     2     2
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.8986  0.9275  0.9565     124   128   132   138
                  1       0.9733  0.9962  0.9962     255   261   261   262
                  2       0.9708  0.9883  0.9883     333   339   339   343
                  3       0.9760  0.9856  0.9856     407   411   411   417
                  4       0.9821  0.9923  0.9923     384   388   388   391
                  5       0.9969  1.0000  1.0000     323   324   324   324
                  6       0.9734  0.9848  0.9848     256   259   259   263
                  7       0.9877  1.0000  1.0000     161   163   163   163
                  8       0.9897  1.0000  1.0000      96    97    97    97
                  9       0.9778  1.0000  1.0000      44    45    45    45
                  10      1.0000  1.0000  1.0000      34    34    34    34
                  11      1.0000  1.0000  1.0000      12    12    12    12
                  12      1.0000  1.0000  1.0000       7     7     7     7
                  13      1.0000  1.0000  1.0000       3     3     3     3
extra_word_count  0       0.8696  0.8841  0.9420      60    61    65    69
                  1       0.9645  0.9949  0.9949     190   196   196   197
                  2       0.9588  0.9828  0.9828     279   286   286   291
                  3       0.9752  0.9876  0.9876     393   398   398   403
                  4       0.9856  0.9928  0.9928     411   414   414   417
                  5       0.9918  0.9973  0.9973     364   366   366   367
                  6       0.9773  0.9870  0.9870     301   304   304   308
                  7       0.9855  1.0000  1.0000     204   207   207   207
                  8       0.9828  0.9914  0.9914     114   115   115   116
                  9       0.9833  1.0000  1.0000      59    60    60    60
                  10      1.0000  1.0000  1.0000      40    40    40    40
                  11      1.0000  1.0000  1.0000      12    12    12    12
                  12      1.0000  1.0000  1.0000       8     8     8     8
                  13      1.0000  1.0000  1.0000       5     5     5     5
part_word_count   1       0.8200  0.8400  0.9200      41    42    46    50
                  2       0.9878  1.0000  1.0000     162   164   164   164
                  3       0.9676  0.9798  0.9798     239   242   242   247
                  4       0.9592  0.9891  0.9891     353   364   364   368
                  5       0.9770  0.9898  0.9898     382   387   387   391
                  6       0.9945  0.9973  0.9973     363   364   364   365
                  7       0.9763  0.9852  0.9852     330   333   333   338
                  8       0.9876  1.0000  1.0000     238   241   241   241
                  9       0.9877  1.0000  1.0000     161   163   163   163
                  10      0.9875  0.9875  0.9875      79    79    79    80
                  11      0.9833  1.0000  1.0000      59    60    60    60
                  12      1.0000  1.0000  1.0000      16    16    16    16
                  13      1.0000  1.0000  1.0000      13    13    13    13
                  14      1.0000  1.0000  1.0000       1     1     1     1
                  15      1.0000  1.0000  1.0000       3     3     3     3


metric                   top3  top5
category         subcat
edit_count        1      1673  1673
                  2       685   685
                  3       128   128
                  4        12    12
                  5         2     2
extra_word_added -1         1     1
                  0       138   138
                  1       262   262
                  2       343   343
                  3       417   417
                  4       391   391
                  5       324   324
                  6       263   263
                  7       163   163
                  8        97    97
                  9        45    45
                  10       34    34
                  11       12    12
                  12        7     7
                  13        3     3
extra_word_count  0        69    69
                  1       197   197
                  2       291   291
                  3       403   403
                  4       417   417
                  5       367   367
                  6       308   308
                  7       207   207
                  8       116   116
                  9        60    60
                  10       40    40
                  11       12    12
                  12        8     8
                  13        5     5
part_word_count   1        50    50
                  2       164   164
                  3       247   247
                  4       368   368
                  5       391   391
                  6       365   365
                  7       338   338
                  8       241   241
                  9       163   163
                  10       80    80
                  11       60    60
                  12       16    16
                  13       13    13
                  14        1     1
                  15        3     3

================================================================================

Statistics after processing 3000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9797  0.9911  0.9921    1974  1997  1999  2015
                  2       0.9741  0.9877  0.9901     791   802   804   812
                  3       0.9810  0.9873  0.9873     155   156   156   158
                  4       0.8462  0.9231  0.9231      11    12    12    13
                  5       1.0000  1.0000  1.0000       2     2     2     2
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9167  0.9405  0.9643     154   158   162   168
                  1       0.9716  0.9968  0.9968     308   316   316   317
                  2       0.9710  0.9855  0.9855     402   408   408   414
                  3       0.9807  0.9884  0.9884     509   513   513   519
                  4       0.9825  0.9934  0.9934     449   454   454   457
                  5       0.9974  1.0000  1.0000     388   389   389   389
                  6       0.9745  0.9873  0.9873     306   310   310   314
                  7       0.9841  0.9947  0.9947     186   188   188   189
                  8       0.9915  1.0000  1.0000     117   118   118   118
                  9       0.9796  1.0000  1.0000      48    49    49    49
                  10      1.0000  1.0000  1.0000      38    38    38    38
                  11      1.0000  1.0000  1.0000      16    16    16    16
                  12      1.0000  1.0000  1.0000       8     8     8     8
                  13      1.0000  1.0000  1.0000       3     3     3     3
extra_word_count  0       0.8966  0.9080  0.9540      78    79    83    87
                  1       0.9667  0.9958  0.9958     232   239   239   240
                  2       0.9574  0.9801  0.9801     337   345   345   352
                  3       0.9800  0.9900  0.9900     491   496   496   501
                  4       0.9856  0.9938  0.9938     480   484   484   487
                  5       0.9931  0.9977  0.9977     433   435   435   436
                  6       0.9785  0.9892  0.9892     364   368   368   372
                  7       0.9833  0.9958  0.9958     236   239   239   240
                  8       0.9861  0.9931  0.9931     142   143   143   144
                  9       0.9846  1.0000  1.0000      64    65    65    65
                  10      1.0000  1.0000  1.0000      46    46    46    46
                  11      1.0000  1.0000  1.0000      16    16    16    16
                  12      1.0000  1.0000  1.0000       9     9     9     9
                  13      1.0000  1.0000  1.0000       5     5     5     5
part_word_count   1       0.8636  0.8788  0.9394      57    58    62    66
                  2       0.9845  1.0000  1.0000     190   193   193   193
                  3       0.9668  0.9767  0.9767     291   294   294   301
                  4       0.9649  0.9912  0.9912     440   452   452   456
                  5       0.9786  0.9914  0.9914     457   463   463   467
                  6       0.9954  0.9977  0.9977     432   433   433   434
                  7       0.9775  0.9875  0.9875     391   395   395   400
                  8       0.9894  1.0000  1.0000     280   283   283   283
                  9       0.9850  0.9950  0.9950     197   199   199   200
                  10      0.9892  0.9892  0.9892      92    92    92    93
                  11      0.9851  1.0000  1.0000      66    67    67    67
                  12      1.0000  1.0000  1.0000      19    19    19    19
                  13      1.0000  1.0000  1.0000      17    17    17    17
                  14      1.0000  1.0000  1.0000       1     1     1     1
                  15      1.0000  1.0000  1.0000       3     3     3     3


metric                   top3  top5
category         subcat
edit_count        1      2015  2015
                  2       812   812
                  3       158   158
                  4        13    13
                  5         2     2
extra_word_added -1         1     1
                  0       168   168
                  1       317   317
                  2       414   414
                  3       519   519
                  4       457   457
                  5       389   389
                  6       314   314
                  7       189   189
                  8       118   118
                  9        49    49
                  10       38    38
                  11       16    16
                  12        8     8
                  13        3     3
extra_word_count  0        87    87
                  1       240   240
                  2       352   352
                  3       501   501
                  4       487   487
                  5       436   436
                  6       372   372
                  7       240   240
                  8       144   144
                  9        65    65
                  10       46    46
                  11       16    16
                  12        9     9
                  13        5     5
part_word_count   1        66    66
                  2       193   193
                  3       301   301
                  4       456   456
                  5       467   467
                  6       434   434
                  7       400   400
                  8       283   283
                  9       200   200
                  10       93    93
                  11       67    67
                  12       19    19
                  13       17    17
                  14        1     1
                  15        3     3

================================================================================

Statistics after processing 3500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9817  0.9919  0.9927    2301  2325  2327  2344
                  2       0.9740  0.9896  0.9917     935   950   952   960
                  3       0.9832  0.9888  0.9888     176   177   177   179
                  4       0.8667  0.9333  0.9333      13    14    14    15
                  5       1.0000  1.0000  1.0000       2     2     2     2
extra_word_added -1       1.0000  1.0000  1.0000       1     1     1     1
                  0       0.9140  0.9462  0.9677     170   176   180   186
                  1       0.9735  0.9974  0.9974     368   377   377   378
                  2       0.9734  0.9877  0.9877     476   483   483   489
                  3       0.9834  0.9900  0.9900     592   596   596   602
                  4       0.9847  0.9943  0.9943     514   519   519   522
                  5       0.9956  0.9978  0.9978     450   451   451   452
                  6       0.9754  0.9891  0.9891     357   362   362   366
                  7       0.9866  0.9955  0.9955     221   223   223   224
                  8       0.9928  1.0000  1.0000     137   138   138   138
                  9       0.9839  1.0000  1.0000      61    62    62    62
                  10      1.0000  1.0000  1.0000      51    51    51    51
                  11      1.0000  1.0000  1.0000      17    17    17    17
                  12      1.0000  1.0000  1.0000       8     8     8     8
                  13      1.0000  1.0000  1.0000       3     3     3     3
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8947  0.9158  0.9579      85    87    91    95
                  1       0.9685  0.9965  0.9965     277   285   285   286
                  2       0.9609  0.9829  0.9829     393   402   402   409
                  3       0.9810  0.9914  0.9914     568   574   574   579
                  4       0.9876  0.9947  0.9947     559   563   563   566
                  5       0.9921  0.9961  0.9961     504   506   506   508
                  6       0.9814  0.9907  0.9907     422   426   426   430
                  7       0.9823  0.9965  0.9965     277   281   281   282
                  8       0.9882  0.9941  0.9941     167   168   168   169
                  9       0.9875  1.0000  1.0000      79    80    80    80
                  10      1.0000  1.0000  1.0000      63    63    63    63
                  11      1.0000  1.0000  1.0000      18    18    18    18
                  12      1.0000  1.0000  1.0000       9     9     9     9
                  13      1.0000  1.0000  1.0000       5     5     5     5
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8649  0.8919  0.9459      64    66    70    74
                  2       0.9870  1.0000  1.0000     227   230   230   230
                  3       0.9686  0.9800  0.9800     339   343   343   350
                  4       0.9658  0.9924  0.9924     509   523   523   527
                  5       0.9814  0.9926  0.9926     527   533   533   537
                  6       0.9942  0.9961  0.9961     516   517   517   519
                  7       0.9800  0.9889  0.9889     440   444   444   449
                  8       0.9910  1.0000  1.0000     330   333   333   333
                  9       0.9829  0.9957  0.9957     230   233   233   234
                  10      0.9912  0.9912  0.9912     113   113   113   114
                  11      0.9885  1.0000  1.0000      86    87    87    87
                  12      1.0000  1.0000  1.0000      23    23    23    23
                  13      1.0000  1.0000  1.0000      18    18    18    18
                  14      1.0000  1.0000  1.0000       1     1     1     1
                  15      1.0000  1.0000  1.0000       4     4     4     4


metric                   top3  top5
category         subcat
edit_count        1      2344  2344
                  2       960   960
                  3       179   179
                  4        15    15
                  5         2     2
extra_word_added -1         1     1
                  0       186   186
                  1       378   378
                  2       489   489
                  3       602   602
                  4       522   522
                  5       452   452
                  6       366   366
                  7       224   224
                  8       138   138
                  9        62    62
                  10       51    51
                  11       17    17
                  12        8     8
                  13        3     3
                  14        1     1
extra_word_count  0        95    95
                  1       286   286
                  2       409   409
                  3       579   579
                  4       566   566
                  5       508   508
                  6       430   430
                  7       282   282
                  8       169   169
                  9        80    80
                  10       63    63
                  11       18    18
                  12        9     9
                  13        5     5
                  14        1     1
part_word_count   1        74    74
                  2       230   230
                  3       350   350
                  4       527   527
                  5       537   537
                  6       519   519
                  7       449   449
                  8       333   333
                  9       234   234
                  10      114   114
                  11       87    87
                  12       23    23
                  13       18    18
                  14        1     1
                  15        4     4

================================================================================
***extra_word_added < 0: -1, part: home turf, label: The energy surrounding this week’s events is palpable, and everyone is eagerly anticipating his next move. Expect much better numbers on James home turf this week. His familiarity with the local environment allows him to perform with greater confidence., edits_made: [((6, 6), (6, 7)), ((7, 8), (8, 9))]

Statistics after processing 4000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9812  0.9925  0.9932    2613  2643  2645  2663
                  2       0.9749  0.9910  0.9928    1087  1105  1107  1115
                  3       0.9852  0.9901  0.9901     200   201   201   203
                  4       0.8750  0.9375  0.9375      14    15    15    16
                  5       1.0000  1.0000  1.0000       3     3     3     3
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9220  0.9512  0.9707     189   195   199   205
                  1       0.9725  0.9954  0.9954     425   435   435   437
                  2       0.9711  0.9892  0.9892     537   547   547   553
                  3       0.9838  0.9912  0.9912     669   674   674   680
                  4       0.9836  0.9951  0.9951     600   607   607   610
                  5       0.9960  0.9980  0.9980     502   503   503   504
                  6       0.9739  0.9905  0.9905     410   417   417   421
                  7       0.9885  0.9962  0.9962     257   259   259   260
                  8       0.9938  1.0000  1.0000     160   161   161   161
                  9       0.9861  1.0000  1.0000      71    72    72    72
                  10      1.0000  1.0000  1.0000      57    57    57    57
                  11      1.0000  1.0000  1.0000      21    21    21    21
                  12      1.0000  1.0000  1.0000      11    11    11    11
                  13      1.0000  1.0000  1.0000       5     5     5     5
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9048  0.9238  0.9619      95    97   101   105
                  1       0.9662  0.9938  0.9938     314   323   323   325
                  2       0.9592  0.9850  0.9850     447   459   459   466
                  3       0.9817  0.9924  0.9924     642   649   649   654
                  4       0.9864  0.9955  0.9955     651   657   657   660
                  5       0.9929  0.9965  0.9965     561   563   563   565
                  6       0.9796  0.9919  0.9919     481   487   487   491
                  7       0.9848  0.9970  0.9970     325   329   329   330
                  8       0.9897  0.9949  0.9949     193   194   194   195
                  9       0.9896  1.0000  1.0000      95    96    96    96
                  10      1.0000  1.0000  1.0000      70    70    70    70
                  11      1.0000  1.0000  1.0000      23    23    23    23
                  12      1.0000  1.0000  1.0000      12    12    12    12
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8765  0.9012  0.9506      71    73    77    81
                  2       0.9806  0.9961  0.9961     253   257   257   258
                  3       0.9679  0.9827  0.9827     392   398   398   405
                  4       0.9681  0.9933  0.9933     576   591   591   595
                  5       0.9790  0.9935  0.9935     606   615   615   619
                  6       0.9932  0.9966  0.9966     584   586   586   588
                  7       0.9804  0.9902  0.9902     500   505   505   510
                  8       0.9921  1.0000  1.0000     375   378   378   378
                  9       0.9856  0.9964  0.9964     273   276   276   277
                  10      0.9923  0.9923  0.9923     129   129   129   130
                  11      0.9900  1.0000  1.0000      99   100   100   100
                  12      1.0000  1.0000  1.0000      28    28    28    28
                  13      1.0000  1.0000  1.0000      24    24    24    24
                  14      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       4     4     4     4
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      2663  2663
                  2      1115  1115
                  3       203   203
                  4        16    16
                  5         3     3
extra_word_added -1         2     2
                  0       205   205
                  1       437   437
                  2       553   553
                  3       680   680
                  4       610   610
                  5       504   504
                  6       421   421
                  7       260   260
                  8       161   161
                  9        72    72
                  10       57    57
                  11       21    21
                  12       11    11
                  13        5     5
                  14        1     1
extra_word_count  0       105   105
                  1       325   325
                  2       466   466
                  3       654   654
                  4       660   660
                  5       565   565
                  6       491   491
                  7       330   330
                  8       195   195
                  9        96    96
                  10       70    70
                  11       23    23
                  12       12    12
                  13        7     7
                  14        1     1
part_word_count   1        81    81
                  2       258   258
                  3       405   405
                  4       595   595
                  5       619   619
                  6       588   588
                  7       510   510
                  8       378   378
                  9       277   277
                  10      130   130
                  11      100   100
                  12       28    28
                  13       24    24
                  14        2     2
                  15        4     4
                  16        1     1

================================================================================

Statistics after processing 4500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9820  0.9923  0.9930    2940  2971  2973  2994
                  2       0.9721  0.9904  0.9928    1219  1242  1245  1254
                  3       0.9822  0.9867  0.9867     221   222   222   225
                  4       0.8636  0.9545  0.9545      19    21    21    22
                  5       1.0000  1.0000  1.0000       5     5     5     5
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9198  0.9536  0.9705     218   226   230   237
                  1       0.9705  0.9941  0.9941     493   505   505   508
                  2       0.9711  0.9887  0.9887     604   615   615   622
                  3       0.9842  0.9908  0.9908     747   752   752   759
                  4       0.9838  0.9956  0.9956     670   678   678   681
                  5       0.9946  0.9982  0.9982     554   556   556   557
                  6       0.9744  0.9893  0.9915     457   464   465   469
                  7       0.9866  0.9933  0.9933     295   297   297   299
                  8       0.9944  1.0000  1.0000     177   178   178   178
                  9       0.9877  1.0000  1.0000      80    81    81    81
                  10      1.0000  1.0000  1.0000      63    63    63    63
                  11      1.0000  1.0000  1.0000      24    24    24    24
                  12      1.0000  1.0000  1.0000      14    14    14    14
                  13      1.0000  1.0000  1.0000       5     5     5     5
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9016  0.9262  0.9590     110   113   117   122
                  1       0.9629  0.9920  0.9920     363   374   374   377
                  2       0.9625  0.9869  0.9869     513   526   526   533
                  3       0.9809  0.9905  0.9905     719   726   726   733
                  4       0.9851  0.9959  0.9959     725   733   733   736
                  5       0.9937  0.9968  0.9968     626   628   628   630
                  6       0.9781  0.9909  0.9927     535   542   543   547
                  7       0.9840  0.9947  0.9947     370   374   374   376
                  8       0.9907  0.9954  0.9954     214   215   215   216
                  9       0.9905  1.0000  1.0000     104   105   105   105
                  10      1.0000  1.0000  1.0000      76    76    76    76
                  11      1.0000  1.0000  1.0000      26    26    26    26
                  12      1.0000  1.0000  1.0000      15    15    15    15
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8737  0.9053  0.9474      83    86    90    95
                  2       0.9797  0.9966  0.9966     290   295   295   296
                  3       0.9654  0.9827  0.9827     446   454   454   462
                  4       0.9699  0.9925  0.9925     644   659   659   664
                  5       0.9785  0.9928  0.9928     684   694   694   699
                  6       0.9924  0.9969  0.9969     650   653   653   655
                  7       0.9808  0.9895  0.9913     561   566   567   572
                  8       0.9883  0.9977  0.9977     423   427   427   428
                  9       0.9871  0.9968  0.9968     306   309   309   310
                  10      0.9931  0.9931  0.9931     143   143   143   144
                  11      0.9908  1.0000  1.0000     108   109   109   109
                  12      1.0000  1.0000  1.0000      31    31    31    31
                  13      1.0000  1.0000  1.0000      27    27    27    27
                  14      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       5     5     5     5
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      2994  2994
                  2      1254  1254
                  3       225   225
                  4        22    22
                  5         5     5
extra_word_added -1         2     2
                  0       237   237
                  1       508   508
                  2       622   622
                  3       759   759
                  4       681   681
                  5       557   557
                  6       469   469
                  7       299   299
                  8       178   178
                  9        81    81
                  10       63    63
                  11       24    24
                  12       14    14
                  13        5     5
                  14        1     1
extra_word_count  0       122   122
                  1       377   377
                  2       533   533
                  3       733   733
                  4       736   736
                  5       630   630
                  6       547   547
                  7       376   376
                  8       216   216
                  9       105   105
                  10       76    76
                  11       26    26
                  12       15    15
                  13        7     7
                  14        1     1
part_word_count   1        95    95
                  2       296   296
                  3       462   462
                  4       664   664
                  5       699   699
                  6       655   655
                  7       572   572
                  8       428   428
                  9       310   310
                  10      144   144
                  11      109   109
                  12       31    31
                  13       27    27
                  14        2     2
                  15        5     5
                  16        1     1

================================================================================

Statistics after processing 5000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9813  0.9919  0.9925    3260  3295  3297  3322
                  2       0.9714  0.9893  0.9921    1361  1386  1390  1401
                  3       0.9837  0.9878  0.9878     241   242   242   245
                  4       0.8889  0.9630  0.9630      24    26    26    27
                  5       1.0000  1.0000  1.0000       5     5     5     5
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9192  0.9538  0.9692     239   248   252   260
                  1       0.9707  0.9927  0.9927     531   543   543   547
                  2       0.9672  0.9857  0.9872     678   691   692   701
                  3       0.9858  0.9917  0.9917     836   841   841   848
                  4       0.9840  0.9960  0.9960     737   746   746   749
                  5       0.9937  0.9984  0.9984     628   631   631   632
                  6       0.9728  0.9883  0.9903     501   509   510   515
                  7       0.9849  0.9910  0.9910     327   329   329   332
                  8       0.9951  1.0000  1.0000     203   204   204   204
                  9       0.9892  1.0000  1.0000      92    93    93    93
                  10      1.0000  1.0000  1.0000      71    71    71    71
                  11      1.0000  1.0000  1.0000      25    25    25    25
                  12      1.0000  1.0000  1.0000      15    15    15    15
                  13      1.0000  1.0000  1.0000       5     5     5     5
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8947  0.9248  0.9549     119   123   127   133
                  1       0.9653  0.9926  0.9926     390   401   401   404
                  2       0.9582  0.9833  0.9849     573   588   589   598
                  3       0.9828  0.9914  0.9914     802   809   809   816
                  4       0.9853  0.9963  0.9963     802   811   811   814
                  5       0.9915  0.9958  0.9958     704   707   707   710
                  6       0.9769  0.9901  0.9917     592   600   601   606
                  7       0.9856  0.9952  0.9952     411   415   415   417
                  8       0.9918  0.9959  0.9959     241   242   242   243
                  9       0.9918  1.0000  1.0000     121   122   122   122
                  10      0.9884  0.9884  0.9884      85    85    85    86
                  11      1.0000  1.0000  1.0000      27    27    27    27
                  12      1.0000  1.0000  1.0000      16    16    16    16
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8667  0.9048  0.9429      91    95    99   105
                  2       0.9810  0.9968  0.9968     310   315   315   316
                  3       0.9632  0.9806  0.9826     497   506   507   516
                  4       0.9704  0.9919  0.9919     722   738   738   744
                  5       0.9790  0.9934  0.9934     746   757   757   762
                  6       0.9932  0.9973  0.9973     731   734   734   736
                  7       0.9769  0.9877  0.9892     634   641   642   649
                  8       0.9894  0.9979  0.9979     465   469   469   470
                  9       0.9884  0.9971  0.9971     342   345   345   346
                  10      0.9938  0.9938  0.9938     160   160   160   161
                  11      0.9919  1.0000  1.0000     123   124   124   124
                  12      0.9706  0.9706  0.9706      33    33    33    34
                  13      1.0000  1.0000  1.0000      29    29    29    29
                  14      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       5     5     5     5
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      3322  3322
                  2      1401  1401
                  3       245   245
                  4        27    27
                  5         5     5
extra_word_added -1         2     2
                  0       260   260
                  1       547   547
                  2       701   701
                  3       848   848
                  4       749   749
                  5       632   632
                  6       515   515
                  7       332   332
                  8       204   204
                  9        93    93
                  10       71    71
                  11       25    25
                  12       15    15
                  13        5     5
                  14        1     1
extra_word_count  0       133   133
                  1       404   404
                  2       598   598
                  3       816   816
                  4       814   814
                  5       710   710
                  6       606   606
                  7       417   417
                  8       243   243
                  9       122   122
                  10       86    86
                  11       27    27
                  12       16    16
                  13        7     7
                  14        1     1
part_word_count   1       105   105
                  2       316   316
                  3       516   516
                  4       744   744
                  5       762   762
                  6       736   736
                  7       649   649
                  8       470   470
                  9       346   346
                  10      161   161
                  11      124   124
                  12       34    34
                  13       29    29
                  14        2     2
                  15        5     5
                  16        1     1

================================================================================

Statistics after processing 5500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9808  0.9921  0.9926    3580  3621  3623  3650
                  2       0.9697  0.9877  0.9910    1503  1531  1536  1550
                  3       0.9774  0.9887  0.9887     259   262   262   265
                  4       0.8966  0.9655  0.9655      26    28    28    29
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9211  0.9534  0.9677     257   266   270   279
                  1       0.9667  0.9900  0.9900     581   595   595   601
                  2       0.9640  0.9858  0.9884     749   766   768   777
                  3       0.9826  0.9924  0.9924     905   914   914   921
                  4       0.9853  0.9963  0.9963     804   813   813   816
                  5       0.9929  0.9971  0.9971     696   699   699   701
                  6       0.9757  0.9896  0.9913     563   571   572   577
                  7       0.9839  0.9892  0.9892     366   368   368   372
                  8       0.9912  1.0000  1.0000     226   228   228   228
                  9       0.9895  1.0000  1.0000      94    95    95    95
                  10      1.0000  1.0000  1.0000      79    79    79    79
                  11      1.0000  1.0000  1.0000      29    29    29    29
                  12      1.0000  1.0000  1.0000      17    17    17    17
                  13      1.0000  1.0000  1.0000       5     5     5     5
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8958  0.9236  0.9514     129   133   137   144
                  1       0.9643  0.9911  0.9911     432   444   444   448
                  2       0.9546  0.9834  0.9849     631   650   651   661
                  3       0.9797  0.9921  0.9921     868   879   879   886
                  4       0.9863  0.9966  0.9966     864   873   873   876
                  5       0.9911  0.9949  0.9949     779   782   782   786
                  6       0.9765  0.9897  0.9927     665   674   676   681
                  7       0.9850  0.9936  0.9936     460   464   464   467
                  8       0.9888  0.9963  0.9963     265   267   267   268
                  9       0.9923  1.0000  1.0000     129   130   130   130
                  10      0.9895  0.9895  0.9895      94    94    94    95
                  11      1.0000  1.0000  1.0000      32    32    32    32
                  12      1.0000  1.0000  1.0000      18    18    18    18
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8750  0.9107  0.9464      98   102   106   112
                  2       0.9773  0.9943  0.9943     345   351   351   353
                  3       0.9625  0.9804  0.9821     539   549   550   560
                  4       0.9659  0.9915  0.9915     794   815   815   822
                  5       0.9780  0.9939  0.9939     802   815   815   820
                  6       0.9926  0.9963  0.9963     807   810   810   813
                  7       0.9780  0.9890  0.9904     710   718   719   726
                  8       0.9866  0.9943  0.9962     516   520   521   523
                  9       0.9869  0.9974  0.9974     378   382   382   383
                  10      0.9941  0.9941  0.9941     169   169   169   170
                  11      0.9928  1.0000  1.0000     137   138   138   138
                  12      0.9750  0.9750  0.9750      39    39    39    40
                  13      1.0000  1.0000  1.0000      31    31    31    31
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       5     5     5     5
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      3650  3650
                  2      1550  1550
                  3       265   265
                  4        29    29
                  5         6     6
extra_word_added -1         2     2
                  0       279   279
                  1       601   601
                  2       777   777
                  3       921   921
                  4       816   816
                  5       701   701
                  6       577   577
                  7       372   372
                  8       228   228
                  9        95    95
                  10       79    79
                  11       29    29
                  12       17    17
                  13        5     5
                  14        1     1
extra_word_count  0       144   144
                  1       448   448
                  2       661   661
                  3       886   886
                  4       876   876
                  5       786   786
                  6       681   681
                  7       467   467
                  8       268   268
                  9       130   130
                  10       95    95
                  11       32    32
                  12       18    18
                  13        7     7
                  14        1     1
part_word_count   1       112   112
                  2       353   353
                  3       560   560
                  4       822   822
                  5       820   820
                  6       813   813
                  7       726   726
                  8       523   523
                  9       383   383
                  10      170   170
                  11      138   138
                  12       40    40
                  13       31    31
                  14        3     3
                  15        5     5
                  16        1     1

================================================================================

Statistics after processing 6000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9804  0.9922  0.9927    3911  3958  3960  3989
                  2       0.9678  0.9881  0.9911    1625  1659  1664  1679
                  3       0.9760  0.9897  0.9897     285   289   289   292
                  4       0.8824  0.9706  0.9706      30    33    33    34
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9172  0.9536  0.9669     277   288   292   302
                  1       0.9610  0.9895  0.9895     640   659   659   666
                  2       0.9634  0.9870  0.9894     815   835   837   846
                  3       0.9830  0.9930  0.9930     981   991   991   998
                  4       0.9865  0.9966  0.9966     875   884   884   887
                  5       0.9908  0.9974  0.9974     751   756   756   758
                  6       0.9761  0.9889  0.9904     613   621   622   628
                  7       0.9855  0.9903  0.9903     408   410   410   414
                  8       0.9882  1.0000  1.0000     252   255   255   255
                  9       0.9901  1.0000  1.0000     100   101   101   101
                  10      1.0000  1.0000  1.0000      88    88    88    88
                  11      1.0000  1.0000  1.0000      30    30    30    30
                  12      1.0000  1.0000  1.0000      18    18    18    18
                  13      1.0000  1.0000  1.0000       6     6     6     6
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8839  0.9226  0.9484     137   143   147   155
                  1       0.9592  0.9918  0.9918     470   486   486   490
                  2       0.9560  0.9835  0.9849     695   715   716   727
                  3       0.9793  0.9928  0.9928     947   960   960   967
                  4       0.9864  0.9969  0.9969     941   951   951   954
                  5       0.9882  0.9953  0.9953     838   844   844   848
                  6       0.9769  0.9891  0.9918     719   728   730   736
                  7       0.9865  0.9942  0.9942     511   515   515   518
                  8       0.9866  0.9967  0.9967     295   298   298   299
                  9       0.9928  1.0000  1.0000     137   138   138   138
                  10      0.9904  0.9904  0.9904     103   103   103   104
                  11      1.0000  1.0000  1.0000      34    34    34    34
                  12      1.0000  1.0000  1.0000      20    20    20    20
                  13      1.0000  1.0000  1.0000       9     9     9     9
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8729  0.9153  0.9492     103   108   112   118
                  2       0.9689  0.9948  0.9948     374   384   384   386
                  3       0.9629  0.9806  0.9823     597   608   609   620
                  4       0.9667  0.9911  0.9911     872   894   894   902
                  5       0.9786  0.9944  0.9944     868   882   882   887
                  6       0.9908  0.9966  0.9966     866   871   871   874
                  7       0.9760  0.9899  0.9912     774   785   786   793
                  8       0.9860  0.9930  0.9948     564   568   569   572
                  9       0.9859  0.9976  0.9976     419   424   424   425
                  10      0.9946  0.9946  0.9946     184   184   184   185
                  11      0.9934  1.0000  1.0000     150   151   151   151
                  12      0.9762  0.9762  0.9762      41    41    41    42
                  13      1.0000  1.0000  1.0000      31    31    31    31
                  14      1.0000  1.0000  1.0000       6     6     6     6
                  15      1.0000  1.0000  1.0000       7     7     7     7
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      3989  3989
                  2      1679  1679
                  3       292   292
                  4        34    34
                  5         6     6
extra_word_added -1         2     2
                  0       302   302
                  1       666   666
                  2       846   846
                  3       998   998
                  4       887   887
                  5       758   758
                  6       628   628
                  7       414   414
                  8       255   255
                  9       101   101
                  10       88    88
                  11       30    30
                  12       18    18
                  13        6     6
                  14        1     1
extra_word_count  0       155   155
                  1       490   490
                  2       727   727
                  3       967   967
                  4       954   954
                  5       848   848
                  6       736   736
                  7       518   518
                  8       299   299
                  9       138   138
                  10      104   104
                  11       34    34
                  12       20    20
                  13        9     9
                  14        1     1
part_word_count   1       118   118
                  2       386   386
                  3       620   620
                  4       902   902
                  5       887   887
                  6       874   874
                  7       793   793
                  8       572   572
                  9       425   425
                  10      185   185
                  11      151   151
                  12       42    42
                  13       31    31
                  14        6     6
                  15        7     7
                  16        1     1

================================================================================

Statistics after processing 6500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9807  0.9923  0.9930    4227  4277  4280  4310
                  2       0.9673  0.9885  0.9913    1774  1813  1818  1834
                  3       0.9744  0.9904  0.9904     305   310   310   313
                  4       0.8919  0.9730  0.9730      33    36    36    37
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9164  0.9552  0.9672     307   320   324   335
                  1       0.9622  0.9902  0.9902     687   707   707   714
                  2       0.9639  0.9880  0.9902     882   904   906   915
                  3       0.9824  0.9926  0.9926    1058  1069  1069  1077
                  4       0.9864  0.9969  0.9969     942   952   952   955
                  5       0.9903  0.9976  0.9976     813   819   819   821
                  6       0.9764  0.9882  0.9912     663   671   673   679
                  7       0.9869  0.9913  0.9913     453   455   455   459
                  8       0.9858  1.0000  1.0000     277   281   281   281
                  9       0.9906  1.0000  1.0000     105   106   106   106
                  10      1.0000  1.0000  1.0000      97    97    97    97
                  11      1.0000  1.0000  1.0000      32    32    32    32
                  12      1.0000  1.0000  1.0000      20    20    20    20
                  13      1.0000  1.0000  1.0000       6     6     6     6
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8876  0.9290  0.9527     150   157   161   169
                  1       0.9598  0.9924  0.9924     502   519   519   523
                  2       0.9556  0.9835  0.9848     754   776   777   789
                  3       0.9788  0.9923  0.9923    1014  1028  1028  1036
                  4       0.9864  0.9971  0.9971    1017  1028  1028  1031
                  5       0.9881  0.9957  0.9957     911   918   918   922
                  6       0.9775  0.9888  0.9925     782   791   794   800
                  7       0.9860  0.9947  0.9947     563   568   568   571
                  8       0.9849  0.9970  0.9970     326   330   330   331
                  9       0.9931  1.0000  1.0000     144   145   145   145
                  10      0.9912  0.9912  0.9912     113   113   113   114
                  11      1.0000  1.0000  1.0000      36    36    36    36
                  12      1.0000  1.0000  1.0000      22    22    22    22
                  13      1.0000  1.0000  1.0000      10    10    10    10
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8750  0.9219  0.9531     112   118   122   128
                  2       0.9684  0.9951  0.9951     398   409   409   411
                  3       0.9639  0.9804  0.9819     640   651   652   664
                  4       0.9664  0.9908  0.9908     949   973   973   982
                  5       0.9789  0.9947  0.9947     929   944   944   949
                  6       0.9905  0.9968  0.9968     936   942   942   945
                  7       0.9758  0.9896  0.9919     845   857   859   866
                  8       0.9872  0.9936  0.9952     618   622   623   626
                  9       0.9831  0.9979  0.9979     464   471   471   472
                  10      0.9949  0.9949  0.9949     197   197   197   198
                  11      0.9939  1.0000  1.0000     163   164   164   164
                  12      0.9783  0.9783  0.9783      45    45    45    46
                  13      1.0000  1.0000  1.0000      34    34    34    34
                  14      1.0000  1.0000  1.0000       6     6     6     6
                  15      1.0000  1.0000  1.0000       8     8     8     8
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      4310  4310
                  2      1834  1834
                  3       313   313
                  4        37    37
                  5         6     6
extra_word_added -1         2     2
                  0       335   335
                  1       714   714
                  2       915   915
                  3      1077  1077
                  4       955   955
                  5       821   821
                  6       679   679
                  7       459   459
                  8       281   281
                  9       106   106
                  10       97    97
                  11       32    32
                  12       20    20
                  13        6     6
                  14        1     1
extra_word_count  0       169   169
                  1       523   523
                  2       789   789
                  3      1036  1036
                  4      1031  1031
                  5       922   922
                  6       800   800
                  7       571   571
                  8       331   331
                  9       145   145
                  10      114   114
                  11       36    36
                  12       22    22
                  13       10    10
                  14        1     1
part_word_count   1       128   128
                  2       411   411
                  3       664   664
                  4       982   982
                  5       949   949
                  6       945   945
                  7       866   866
                  8       626   626
                  9       472   472
                  10      198   198
                  11      164   164
                  12       46    46
                  13       34    34
                  14        6     6
                  15        8     8
                  16        1     1

================================================================================

Statistics after processing 7000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9807  0.9927  0.9933    4570  4626  4629  4660
                  2       0.9678  0.9893  0.9918    1891  1933  1938  1954
                  3       0.9736  0.9912  0.9912     332   338   338   341
                  4       0.8974  0.9744  0.9744      35    38    38    39
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9171  0.9586  0.9696     332   347   351   362
                  1       0.9634  0.9908  0.9908     736   757   757   764
                  2       0.9636  0.9889  0.9909     953   978   980   989
                  3       0.9830  0.9932  0.9932    1156  1168  1168  1176
                  4       0.9862  0.9971  0.9971    1004  1015  1015  1018
                  5       0.9898  0.9966  0.9966     872   878   878   881
                  6       0.9754  0.9891  0.9918     713   723   725   731
                  7       0.9880  0.9920  0.9920     492   494   494   498
                  8       0.9869  1.0000  1.0000     301   305   305   305
                  9       0.9911  1.0000  1.0000     111   112   112   112
                  10      1.0000  1.0000  1.0000      98    98    98    98
                  11      1.0000  1.0000  1.0000      34    34    34    34
                  12      1.0000  1.0000  1.0000      22    22    22    22
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8913  0.9348  0.9565     164   172   176   184
                  1       0.9591  0.9929  0.9929     539   558   558   562
                  2       0.9554  0.9847  0.9859     814   839   840   852
                  3       0.9798  0.9930  0.9930    1113  1128  1128  1136
                  4       0.9863  0.9973  0.9973    1080  1092  1092  1095
                  5       0.9878  0.9949  0.9949     971   978   978   983
                  6       0.9769  0.9896  0.9931     847   858   861   867
                  7       0.9870  0.9951  0.9951     607   612   612   615
                  8       0.9861  0.9972  0.9972     355   359   359   360
                  9       0.9935  1.0000  1.0000     153   154   154   154
                  10      0.9914  0.9914  0.9914     115   115   115   116
                  11      1.0000  1.0000  1.0000      40    40    40    40
                  12      1.0000  1.0000  1.0000      24    24    24    24
                  13      1.0000  1.0000  1.0000      11    11    11    11
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8777  0.9281  0.9568     122   129   133   139
                  2       0.9683  0.9955  0.9955     427   439   439   441
                  3       0.9611  0.9819  0.9833     692   707   708   720
                  4       0.9685  0.9917  0.9917    1045  1070  1070  1079
                  5       0.9802  0.9951  0.9951     992  1007  1007  1012
                  6       0.9891  0.9960  0.9960     996  1003  1003  1007
                  7       0.9754  0.9904  0.9925     913   927   929   936
                  8       0.9880  0.9940  0.9955     661   665   666   669
                  9       0.9844  0.9980  0.9980     504   511   511   512
                  10      0.9953  0.9953  0.9953     212   212   212   213
                  11      0.9940  1.0000  1.0000     167   168   168   168
                  12      0.9800  0.9800  0.9800      49    49    49    50
                  13      1.0000  1.0000  1.0000      37    37    37    37
                  14      1.0000  1.0000  1.0000       8     8     8     8
                  15      1.0000  1.0000  1.0000       8     8     8     8
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      4660  4660
                  2      1954  1954
                  3       341   341
                  4        39    39
                  5         6     6
extra_word_added -1         2     2
                  0       362   362
                  1       764   764
                  2       989   989
                  3      1176  1176
                  4      1018  1018
                  5       881   881
                  6       731   731
                  7       498   498
                  8       305   305
                  9       112   112
                  10       98    98
                  11       34    34
                  12       22    22
                  13        7     7
                  14        1     1
extra_word_count  0       184   184
                  1       562   562
                  2       852   852
                  3      1136  1136
                  4      1095  1095
                  5       983   983
                  6       867   867
                  7       615   615
                  8       360   360
                  9       154   154
                  10      116   116
                  11       40    40
                  12       24    24
                  13       11    11
                  14        1     1
part_word_count   1       139   139
                  2       441   441
                  3       720   720
                  4      1079  1079
                  5      1012  1012
                  6      1007  1007
                  7       936   936
                  8       669   669
                  9       512   512
                  10      213   213
                  11      168   168
                  12       50    50
                  13       37    37
                  14        8     8
                  15        8     8
                  16        1     1

================================================================================

Statistics after processing 7500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9808  0.9926  0.9932    4896  4955  4958  4992
                  2       0.9690  0.9895  0.9919    2032  2075  2080  2097
                  3       0.9723  0.9917  0.9917     351   358   358   361
                  4       0.9091  0.9773  0.9773      40    43    43    44
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9182  0.9616  0.9719     359   376   380   391
                  1       0.9645  0.9902  0.9902     787   808   808   816
                  2       0.9652  0.9896  0.9915    1025  1051  1053  1062
                  3       0.9840  0.9936  0.9936    1230  1242  1242  1250
                  4       0.9846  0.9955  0.9955    1087  1099  1099  1104
                  5       0.9883  0.9958  0.9958     932   939   939   943
                  6       0.9772  0.9898  0.9924     770   780   782   788
                  7       0.9886  0.9924  0.9924     521   523   523   527
                  8       0.9875  1.0000  1.0000     316   320   320   320
                  9       0.9920  1.0000  1.0000     124   125   125   125
                  10      1.0000  1.0000  1.0000     103   103   103   103
                  11      1.0000  1.0000  1.0000      35    35    35    35
                  12      1.0000  1.0000  1.0000      26    26    26    26
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8923  0.9385  0.9590     174   183   187   195
                  1       0.9605  0.9918  0.9918     584   603   603   608
                  2       0.9575  0.9858  0.9869     879   905   906   918
                  3       0.9800  0.9933  0.9933    1179  1195  1195  1203
                  4       0.9858  0.9958  0.9958    1177  1189  1189  1194
                  5       0.9858  0.9943  0.9943    1038  1047  1047  1053
                  6       0.9785  0.9903  0.9935     910   921   924   930
                  7       0.9877  0.9954  0.9954     643   648   648   651
                  8       0.9868  0.9974  0.9974     373   377   377   378
                  9       0.9940  1.0000  1.0000     167   168   168   168
                  10      0.9917  0.9917  0.9917     120   120   120   121
                  11      1.0000  1.0000  1.0000      41    41    41    41
                  12      1.0000  1.0000  1.0000      28    28    28    28
                  13      1.0000  1.0000  1.0000      11    11    11    11
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8859  0.9329  0.9597     132   139   143   149
                  2       0.9660  0.9936  0.9936     455   468   468   471
                  3       0.9640  0.9833  0.9846     750   765   766   778
                  4       0.9702  0.9921  0.9921    1108  1133  1133  1142
                  5       0.9782  0.9937  0.9937    1079  1096  1096  1103
                  6       0.9880  0.9954  0.9954    1072  1080  1080  1085
                  7       0.9762  0.9911  0.9931     984   999  1001  1008
                  8       0.9887  0.9943  0.9958     699   703   704   707
                  9       0.9852  0.9981  0.9981     532   539   539   540
                  10      0.9957  0.9957  0.9957     230   230   230   231
                  11      0.9943  1.0000  1.0000     174   175   175   175
                  12      0.9804  0.9804  0.9804      50    50    50    51
                  13      1.0000  1.0000  1.0000      43    43    43    43
                  14      1.0000  1.0000  1.0000       8     8     8     8
                  15      1.0000  1.0000  1.0000       8     8     8     8
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      4992  4992
                  2      2097  2097
                  3       361   361
                  4        44    44
                  5         6     6
extra_word_added -1         2     2
                  0       391   391
                  1       816   816
                  2      1062  1062
                  3      1250  1250
                  4      1104  1104
                  5       943   943
                  6       788   788
                  7       527   527
                  8       320   320
                  9       125   125
                  10      103   103
                  11       35    35
                  12       26    26
                  13        7     7
                  14        1     1
extra_word_count  0       195   195
                  1       608   608
                  2       918   918
                  3      1203  1203
                  4      1194  1194
                  5      1053  1053
                  6       930   930
                  7       651   651
                  8       378   378
                  9       168   168
                  10      121   121
                  11       41    41
                  12       28    28
                  13       11    11
                  14        1     1
part_word_count   1       149   149
                  2       471   471
                  3       778   778
                  4      1142  1142
                  5      1103  1103
                  6      1085  1085
                  7      1008  1008
                  8       707   707
                  9       540   540
                  10      231   231
                  11      175   175
                  12       51    51
                  13       43    43
                  14        8     8
                  15        8     8
                  16        1     1

================================================================================

Statistics after processing 8000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9803  0.9923  0.9929    5235  5299  5302  5340
                  2       0.9698  0.9901  0.9923    2151  2196  2201  2218
                  3       0.9717  0.9897  0.9897     378   385   385   389
                  4       0.9149  0.9787  0.9787      43    46    46    47
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9193  0.9609  0.9707     376   393   397   409
                  1       0.9645  0.9897  0.9897     842   864   864   873
                  2       0.9661  0.9896  0.9913    1111  1138  1140  1150
                  3       0.9842  0.9940  0.9940    1306  1319  1319  1327
                  4       0.9839  0.9949  0.9949    1162  1175  1175  1181
                  5       0.9889  0.9960  0.9960     978   985   985   989
                  6       0.9764  0.9906  0.9929     829   841   843   849
                  7       0.9875  0.9911  0.9911     552   554   554   559
                  8       0.9856  1.0000  1.0000     342   347   347   347
                  9       0.9924  1.0000  1.0000     131   132   132   132
                  10      1.0000  1.0000  1.0000     110   110   110   110
                  11      1.0000  1.0000  1.0000      36    36    36    36
                  12      1.0000  1.0000  1.0000      28    28    28    28
                  13      1.0000  1.0000  1.0000       7     7     7     7
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8966  0.9409  0.9606     182   191   195   203
                  1       0.9601  0.9908  0.9908     626   646   646   652
                  2       0.9590  0.9850  0.9860     959   985   986  1000
                  3       0.9812  0.9937  0.9937    1253  1269  1269  1277
                  4       0.9843  0.9953  0.9953    1257  1271  1271  1277
                  5       0.9864  0.9946  0.9946    1089  1098  1098  1104
                  6       0.9769  0.9910  0.9940     974   988   991   997
                  7       0.9870  0.9942  0.9942     684   689   689   693
                  8       0.9853  0.9976  0.9976     403   408   408   409
                  9       0.9943  1.0000  1.0000     175   176   176   176
                  10      0.9922  0.9922  0.9922     127   127   127   128
                  11      1.0000  1.0000  1.0000      42    42    42    42
                  12      1.0000  1.0000  1.0000      29    29    29    29
                  13      1.0000  1.0000  1.0000      12    12    12    12
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8917  0.9363  0.9618     140   147   151   157
                  2       0.9644  0.9921  0.9921     488   502   502   506
                  3       0.9666  0.9845  0.9857     811   826   827   839
                  4       0.9706  0.9910  0.9910    1190  1215  1215  1226
                  5       0.9780  0.9932  0.9932    1156  1174  1174  1182
                  6       0.9877  0.9956  0.9956    1127  1136  1136  1141
                  7       0.9758  0.9916  0.9935    1047  1064  1066  1073
                  8       0.9879  0.9933  0.9946     736   740   741   745
                  9       0.9830  0.9983  0.9983     578   587   587   588
                  10      0.9959  0.9959  0.9959     243   243   243   244
                  11      0.9945  1.0000  1.0000     182   183   183   183
                  12      0.9815  0.9815  0.9815      53    53    53    54
                  13      1.0000  1.0000  1.0000      44    44    44    44
                  14      1.0000  1.0000  1.0000       9     9     9     9
                  15      1.0000  1.0000  1.0000       8     8     8     8
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      5340  5340
                  2      2218  2218
                  3       389   389
                  4        47    47
                  5         6     6
extra_word_added -1         2     2
                  0       409   409
                  1       873   873
                  2      1150  1150
                  3      1327  1327
                  4      1181  1181
                  5       989   989
                  6       849   849
                  7       559   559
                  8       347   347
                  9       132   132
                  10      110   110
                  11       36    36
                  12       28    28
                  13        7     7
                  14        1     1
extra_word_count  0       203   203
                  1       652   652
                  2      1000  1000
                  3      1277  1277
                  4      1277  1277
                  5      1104  1104
                  6       997   997
                  7       693   693
                  8       409   409
                  9       176   176
                  10      128   128
                  11       42    42
                  12       29    29
                  13       12    12
                  14        1     1
part_word_count   1       157   157
                  2       506   506
                  3       839   839
                  4      1226  1226
                  5      1182  1182
                  6      1141  1141
                  7      1073  1073
                  8       745   745
                  9       588   588
                  10      244   244
                  11      183   183
                  12       54    54
                  13       44    44
                  14        9     9
                  15        8     8
                  16        1     1

================================================================================

Statistics after processing 8500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9806  0.9924  0.9929    5549  5616  5619  5659
                  2       0.9697  0.9899  0.9924    2301  2349  2355  2373
                  3       0.9707  0.9878  0.9878     397   404   404   409
                  4       0.9245  0.9811  0.9811      49    52    52    53
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9194  0.9631  0.9724     399   418   422   434
                  1       0.9635  0.9871  0.9871     897   919   919   931
                  2       0.9652  0.9895  0.9919    1194  1224  1227  1237
                  3       0.9842  0.9935  0.9935    1372  1385  1385  1394
                  4       0.9839  0.9952  0.9952    1225  1239  1239  1245
                  5       0.9896  0.9962  0.9962    1049  1056  1056  1060
                  6       0.9778  0.9911  0.9933     881   893   895   901
                  7       0.9882  0.9916  0.9916     586   588   588   593
                  8       0.9866  1.0000  1.0000     367   372   372   372
                  9       0.9929  1.0000  1.0000     139   140   140   140
                  10      1.0000  1.0000  1.0000     117   117   117   117
                  11      1.0000  1.0000  1.0000      37    37    37    37
                  12      1.0000  1.0000  1.0000      28    28    28    28
                  13      1.0000  1.0000  1.0000       8     8     8     8
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8950  0.9452  0.9635     196   207   211   219
                  1       0.9609  0.9899  0.9899     664   684   684   691
                  2       0.9597  0.9859  0.9869    1024  1052  1053  1067
                  3       0.9808  0.9933  0.9933    1325  1342  1342  1351
                  4       0.9836  0.9948  0.9948    1320  1335  1335  1342
                  5       0.9865  0.9941  0.9949    1167  1176  1177  1183
                  6       0.9773  0.9905  0.9934    1034  1048  1051  1058
                  7       0.9879  0.9946  0.9946     734   739   739   743
                  8       0.9863  0.9977  0.9977     432   437   437   438
                  9       0.9946  1.0000  1.0000     184   185   185   185
                  10      0.9926  0.9926  0.9926     134   134   134   135
                  11      1.0000  1.0000  1.0000      44    44    44    44
                  12      1.0000  1.0000  1.0000      30    30    30    30
                  13      1.0000  1.0000  1.0000      13    13    13    13
                  14      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8895  0.9419  0.9651     153   162   166   172
                  2       0.9642  0.9906  0.9906     511   525   525   530
                  3       0.9690  0.9856  0.9867     874   889   890   902
                  4       0.9698  0.9907  0.9907    1254  1281  1281  1293
                  5       0.9776  0.9936  0.9936    1221  1241  1241  1249
                  6       0.9884  0.9959  0.9959    1194  1203  1203  1208
                  7       0.9756  0.9904  0.9930    1120  1137  1140  1148
                  8       0.9874  0.9924  0.9937     782   786   787   792
                  9       0.9840  0.9984  0.9984     616   625   625   626
                  10      0.9962  0.9962  0.9962     264   264   264   265
                  11      0.9948  1.0000  1.0000     191   192   192   192
                  12      0.9828  0.9828  0.9828      57    57    57    58
                  13      1.0000  1.0000  1.0000      46    46    46    46
                  14      1.0000  1.0000  1.0000      10    10    10    10
                  15      1.0000  1.0000  1.0000       8     8     8     8
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      5659  5659
                  2      2373  2373
                  3       409   409
                  4        53    53
                  5         6     6
extra_word_added -1         2     2
                  0       434   434
                  1       931   931
                  2      1237  1237
                  3      1394  1394
                  4      1245  1245
                  5      1060  1060
                  6       901   901
                  7       593   593
                  8       372   372
                  9       140   140
                  10      117   117
                  11       37    37
                  12       28    28
                  13        8     8
                  14        1     1
extra_word_count  0       219   219
                  1       691   691
                  2      1067  1067
                  3      1351  1351
                  4      1342  1342
                  5      1183  1183
                  6      1058  1058
                  7       743   743
                  8       438   438
                  9       185   185
                  10      135   135
                  11       44    44
                  12       30    30
                  13       13    13
                  14        1     1
part_word_count   1       172   172
                  2       530   530
                  3       902   902
                  4      1293  1293
                  5      1249  1249
                  6      1208  1208
                  7      1148  1148
                  8       792   792
                  9       626   626
                  10      265   265
                  11      192   192
                  12       58    58
                  13       46    46
                  14       10    10
                  15        8     8
                  16        1     1

================================================================================

Statistics after processing 9000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9808  0.9925  0.9930    5874  5944  5947  5989
                  2       0.9698  0.9905  0.9928    2441  2493  2499  2517
                  3       0.9699  0.9884  0.9884     419   427   427   432
                  4       0.9286  0.9821  0.9821      52    55    55    56
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9180  0.9623  0.9712     414   434   438   451
                  1       0.9638  0.9879  0.9879     958   982   982   994
                  2       0.9663  0.9900  0.9923    1262  1293  1296  1306
                  3       0.9844  0.9939  0.9939    1453  1467  1467  1476
                  4       0.9840  0.9954  0.9954    1295  1310  1310  1316
                  5       0.9902  0.9965  0.9965    1116  1123  1123  1127
                  6       0.9768  0.9916  0.9937     926   940   942   948
                  7       0.9889  0.9921  0.9921     624   626   626   631
                  8       0.9849  0.9975  0.9975     391   396   396   397
                  9       0.9935  1.0000  1.0000     153   154   154   154
                  10      1.0000  1.0000  1.0000     120   120   120   120
                  11      1.0000  1.0000  1.0000      39    39    39    39
                  12      1.0000  1.0000  1.0000      30    30    30    30
                  13      1.0000  1.0000  1.0000       8     8     8     8
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8884  0.9420  0.9598     199   211   215   224
                  1       0.9621  0.9905  0.9905     711   732   732   739
                  2       0.9608  0.9866  0.9875    1079  1108  1109  1123
                  3       0.9818  0.9937  0.9937    1406  1423  1423  1432
                  4       0.9838  0.9951  0.9951    1399  1415  1415  1422
                  5       0.9865  0.9944  0.9952    1244  1254  1255  1261
                  6       0.9758  0.9910  0.9937    1088  1105  1108  1115
                  7       0.9885  0.9949  0.9949     777   782   782   786
                  8       0.9849  0.9957  0.9957     458   463   463   465
                  9       0.9950  1.0000  1.0000     199   200   200   200
                  10      0.9929  0.9929  0.9929     139   139   139   140
                  11      1.0000  1.0000  1.0000      47    47    47    47
                  12      1.0000  1.0000  1.0000      31    31    31    31
                  13      1.0000  1.0000  1.0000      13    13    13    13
                  14      1.0000  1.0000  1.0000       2     2     2     2
part_word_count   1       0.8807  0.9375  0.9602     155   165   169   176
                  2       0.9661  0.9911  0.9911     541   555   555   560
                  3       0.9695  0.9863  0.9874     922   938   939   951
                  4       0.9708  0.9912  0.9912    1329  1357  1357  1369
                  5       0.9789  0.9940  0.9940    1298  1318  1318  1326
                  6       0.9883  0.9961  0.9961    1264  1274  1274  1279
                  7       0.9752  0.9909  0.9934    1181  1200  1203  1211
                  8       0.9859  0.9930  0.9941     842   848   849   854
                  9       0.9832  0.9970  0.9970     645   654   654   656
                  10      0.9965  0.9965  0.9965     288   288   288   289
                  11      0.9949  1.0000  1.0000     197   198   198   198
                  12      0.9841  0.9841  0.9841      62    62    62    63
                  13      1.0000  1.0000  1.0000      48    48    48    48
                  14      1.0000  1.0000  1.0000      10    10    10    10
                  15      1.0000  1.0000  1.0000       9     9     9     9
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      5989  5989
                  2      2517  2517
                  3       432   432
                  4        56    56
                  5         6     6
extra_word_added -1         2     2
                  0       451   451
                  1       994   994
                  2      1306  1306
                  3      1476  1476
                  4      1316  1316
                  5      1127  1127
                  6       948   948
                  7       631   631
                  8       397   397
                  9       154   154
                  10      120   120
                  11       39    39
                  12       30    30
                  13        8     8
                  14        1     1
extra_word_count  0       224   224
                  1       739   739
                  2      1123  1123
                  3      1432  1432
                  4      1422  1422
                  5      1261  1261
                  6      1115  1115
                  7       786   786
                  8       465   465
                  9       200   200
                  10      140   140
                  11       47    47
                  12       31    31
                  13       13    13
                  14        2     2
part_word_count   1       176   176
                  2       560   560
                  3       951   951
                  4      1369  1369
                  5      1326  1326
                  6      1279  1279
                  7      1211  1211
                  8       854   854
                  9       656   656
                  10      289   289
                  11      198   198
                  12       63    63
                  13       48    48
                  14       10    10
                  15        9     9
                  16        1     1

================================================================================

Statistics after processing 9500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9810  0.9924  0.9929    6191  6263  6266  6311
                  2       0.9708  0.9906  0.9929    2594  2647  2653  2672
                  3       0.9712  0.9889  0.9889     438   446   446   451
                  4       0.9167  0.9667  0.9667      55    58    58    60
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9170  0.9617  0.9702     431   452   456   470
                  1       0.9658  0.9886  0.9886    1018  1042  1042  1054
                  2       0.9668  0.9899  0.9921    1339  1371  1374  1385
                  3       0.9846  0.9936  0.9936    1538  1552  1552  1562
                  4       0.9835  0.9950  0.9950    1370  1386  1386  1393
                  5       0.9898  0.9958  0.9958    1166  1173  1173  1178
                  6       0.9779  0.9920  0.9940     972   986   988   994
                  7       0.9894  0.9924  0.9924     653   655   655   660
                  8       0.9858  0.9976  0.9976     417   422   422   423
                  9       0.9938  1.0000  1.0000     161   162   162   162
                  10      1.0000  1.0000  1.0000     132   132   132   132
                  11      1.0000  1.0000  1.0000      44    44    44    44
                  12      1.0000  1.0000  1.0000      31    31    31    31
                  13      1.0000  1.0000  1.0000       9     9     9     9
                  14      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8894  0.9404  0.9574     209   221   225   235
                  1       0.9642  0.9911  0.9911     755   776   776   783
                  2       0.9613  0.9874  0.9882    1143  1174  1175  1189
                  3       0.9816  0.9928  0.9928    1491  1508  1508  1519
                  4       0.9840  0.9953  0.9953    1478  1495  1495  1502
                  5       0.9864  0.9940  0.9947    1306  1316  1317  1324
                  6       0.9768  0.9914  0.9940    1137  1154  1157  1164
                  7       0.9891  0.9951  0.9951     814   819   819   823
                  8       0.9857  0.9959  0.9959     484   489   489   491
                  9       0.9905  0.9953  0.9953     209   210   210   211
                  10      0.9935  0.9935  0.9935     154   154   154   155
                  11      1.0000  1.0000  1.0000      55    55    55    55
                  12      1.0000  1.0000  1.0000      33    33    33    33
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       2     2     2     2
part_word_count   1       0.8859  0.9402  0.9620     163   173   177   184
                  2       0.9663  0.9899  0.9899     574   588   588   594
                  3       0.9713  0.9872  0.9881     983   999  1000  1012
                  4       0.9711  0.9910  0.9910    1410  1439  1439  1452
                  5       0.9780  0.9936  0.9936    1375  1397  1397  1406
                  6       0.9880  0.9955  0.9955    1322  1332  1332  1338
                  7       0.9764  0.9913  0.9937    1240  1259  1262  1270
                  8       0.9865  0.9933  0.9944     880   886   887   892
                  9       0.9840  0.9971  0.9971     677   686   686   688
                  10      0.9967  0.9967  0.9967     303   303   303   304
                  11      0.9906  0.9953  0.9953     211   212   212   213
                  12      0.9863  0.9863  0.9863      72    72    72    73
                  13      1.0000  1.0000  1.0000      51    51    51    51
                  14      1.0000  1.0000  1.0000      13    13    13    13
                  15      1.0000  1.0000  1.0000       9     9     9     9
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      6311  6311
                  2      2672  2672
                  3       451   451
                  4        60    60
                  5         6     6
extra_word_added -1         2     2
                  0       470   470
                  1      1054  1054
                  2      1385  1385
                  3      1562  1562
                  4      1393  1393
                  5      1178  1178
                  6       994   994
                  7       660   660
                  8       423   423
                  9       162   162
                  10      132   132
                  11       44    44
                  12       31    31
                  13        9     9
                  14        1     1
extra_word_count  0       235   235
                  1       783   783
                  2      1189  1189
                  3      1519  1519
                  4      1502  1502
                  5      1324  1324
                  6      1164  1164
                  7       823   823
                  8       491   491
                  9       211   211
                  10      155   155
                  11       55    55
                  12       33    33
                  13       14    14
                  14        2     2
part_word_count   1       184   184
                  2       594   594
                  3      1012  1012
                  4      1452  1452
                  5      1406  1406
                  6      1338  1338
                  7      1270  1270
                  8       892   892
                  9       688   688
                  10      304   304
                  11      213   213
                  12       73    73
                  13       51    51
                  14       13    13
                  15        9     9
                  16        1     1

================================================================================

Statistics after processing 10000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9816  0.9928  0.9932    6519  6593  6596  6641
                  2       0.9709  0.9904  0.9925    2733  2788  2794  2815
                  3       0.9705  0.9895  0.9895     461   470   470   475
                  4       0.9206  0.9683  0.9683      58    61    61    63
                  5       1.0000  1.0000  1.0000       6     6     6     6
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9155  0.9618  0.9698     455   478   482   497
                  1       0.9673  0.9891  0.9891    1065  1089  1089  1101
                  2       0.9655  0.9896  0.9917    1398  1433  1436  1448
                  3       0.9854  0.9939  0.9939    1620  1634  1634  1644
                  4       0.9843  0.9952  0.9952    1445  1461  1461  1468
                  5       0.9904  0.9960  0.9960    1237  1244  1244  1249
                  6       0.9791  0.9924  0.9943    1029  1043  1045  1051
                  7       0.9899  0.9928  0.9928     687   689   689   694
                  8       0.9865  0.9977  0.9977     437   442   442   443
                  9       0.9942  1.0000  1.0000     171   172   172   172
                  10      1.0000  1.0000  1.0000     140   140   140   140
                  11      1.0000  1.0000  1.0000      48    48    48    48
                  12      1.0000  1.0000  1.0000      32    32    32    32
                  13      1.0000  1.0000  1.0000       9     9     9     9
                  14      1.0000  1.0000  1.0000       2     2     2     2
extra_word_count  0       0.8939  0.9429  0.9592     219   231   235   245
                  1       0.9646  0.9915  0.9915     790   812   812   819
                  2       0.9597  0.9871  0.9879    1192  1226  1227  1242
                  3       0.9814  0.9926  0.9926    1582  1600  1600  1612
                  4       0.9848  0.9956  0.9956    1552  1569  1569  1576
                  5       0.9872  0.9943  0.9950    1386  1396  1397  1404
                  6       0.9779  0.9918  0.9943    1197  1214  1217  1224
                  7       0.9896  0.9954  0.9954     853   858   858   862
                  8       0.9865  0.9961  0.9961     510   515   515   517
                  9       0.9911  0.9955  0.9955     222   223   223   224
                  10      0.9939  0.9939  0.9939     163   163   163   164
                  11      1.0000  1.0000  1.0000      60    60    60    60
                  12      1.0000  1.0000  1.0000      34    34    34    34
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       3     3     3     3
part_word_count   1       0.8901  0.9424  0.9634     170   180   184   191
                  2       0.9681  0.9904  0.9904     607   621   621   627
                  3       0.9704  0.9866  0.9876    1016  1033  1034  1047
                  4       0.9707  0.9909  0.9909    1489  1520  1520  1534
                  5       0.9784  0.9939  0.9939    1447  1470  1470  1479
                  6       0.9880  0.9958  0.9958    1403  1414  1414  1420
                  7       0.9776  0.9918  0.9940    1312  1331  1334  1342
                  8       0.9872  0.9936  0.9947     923   929   930   935
                  9       0.9848  0.9972  0.9972     712   721   721   723
                  10      0.9969  0.9969  0.9969     321   321   321   322
                  11      0.9911  0.9955  0.9955     222   223   223   224
                  12      0.9872  0.9872  0.9872      77    77    77    78
                  13      1.0000  1.0000  1.0000      54    54    54    54
                  14      1.0000  1.0000  1.0000      13    13    13    13
                  15      1.0000  1.0000  1.0000      10    10    10    10
                  16      1.0000  1.0000  1.0000       1     1     1     1


metric                   top3  top5
category         subcat
edit_count        1      6641  6641
                  2      2815  2815
                  3       475   475
                  4        63    63
                  5         6     6
extra_word_added -1         2     2
                  0       497   497
                  1      1101  1101
                  2      1448  1448
                  3      1644  1644
                  4      1468  1468
                  5      1249  1249
                  6      1051  1051
                  7       694   694
                  8       443   443
                  9       172   172
                  10      140   140
                  11       48    48
                  12       32    32
                  13        9     9
                  14        2     2
extra_word_count  0       245   245
                  1       819   819
                  2      1242  1242
                  3      1612  1612
                  4      1576  1576
                  5      1404  1404
                  6      1224  1224
                  7       862   862
                  8       517   517
                  9       224   224
                  10      164   164
                  11       60    60
                  12       34    34
                  13       14    14
                  14        3     3
part_word_count   1       191   191
                  2       627   627
                  3      1047  1047
                  4      1534  1534
                  5      1479  1479
                  6      1420  1420
                  7      1342  1342
                  8       935   935
                  9       723   723
                  10      322   322
                  11      224   224
                  12       78    78
                  13       54    54
                  14       13    13
                  15       10    10
                  16        1     1

================================================================================

Statistics after processing 10500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9818  0.9928  0.9933    6853  6930  6933  6980
                  2       0.9712  0.9905  0.9925    2867  2924  2930  2952
                  3       0.9677  0.9879  0.9879     480   490   490   496
                  4       0.9231  0.9692  0.9692      60    63    63    65
                  5       1.0000  1.0000  1.0000       7     7     7     7
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9149  0.9622  0.9698     484   509   513   529
                  1       0.9692  0.9897  0.9897    1133  1157  1157  1169
                  2       0.9665  0.9895  0.9915    1471  1506  1509  1522
                  3       0.9848  0.9941  0.9941    1682  1698  1698  1708
                  4       0.9839  0.9955  0.9955    1529  1547  1547  1554
                  5       0.9901  0.9954  0.9954    1294  1301  1301  1307
                  6       0.9791  0.9918  0.9936    1076  1090  1092  1099
                  7       0.9903  0.9931  0.9931     715   717   717   722
                  8       0.9871  0.9978  0.9978     459   464   464   465
                  9       0.9944  1.0000  1.0000     177   178   178   178
                  10      1.0000  1.0000  1.0000     145   145   145   145
                  11      1.0000  1.0000  1.0000      53    53    53    53
                  12      1.0000  1.0000  1.0000      35    35    35    35
                  13      1.0000  1.0000  1.0000       9     9     9     9
                  14      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.8981  0.9434  0.9585     238   250   254   265
                  1       0.9669  0.9920  0.9920     846   868   868   875
                  2       0.9618  0.9878  0.9885    1259  1293  1294  1309
                  3       0.9793  0.9923  0.9923    1653  1675  1675  1688
                  4       0.9843  0.9958  0.9958    1633  1652  1652  1659
                  5       0.9871  0.9939  0.9946    1449  1459  1460  1468
                  6       0.9781  0.9914  0.9937    1248  1265  1268  1276
                  7       0.9899  0.9955  0.9955     884   889   889   893
                  8       0.9871  0.9963  0.9963     536   541   541   543
                  9       0.9914  0.9957  0.9957     230   231   231   232
                  10      0.9942  0.9942  0.9942     171   171   171   172
                  11      1.0000  1.0000  1.0000      65    65    65    65
                  12      1.0000  1.0000  1.0000      37    37    37    37
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8932  0.9417  0.9612     184   194   198   206
                  2       0.9702  0.9911  0.9911     652   666   666   672
                  3       0.9719  0.9873  0.9882    1074  1091  1092  1105
                  4       0.9707  0.9913  0.9913    1558  1591  1591  1605
                  5       0.9775  0.9936  0.9936    1524  1549  1549  1559
                  6       0.9866  0.9953  0.9953    1475  1488  1488  1495
                  7       0.9778  0.9914  0.9936    1367  1386  1389  1398
                  8       0.9876  0.9938  0.9949     959   965   966   971
                  9       0.9854  0.9973  0.9973     740   749   749   751
                  10      0.9970  0.9970  0.9970     336   336   336   337
                  11      0.9914  0.9957  0.9957     231   232   232   233
                  12      0.9882  0.9882  0.9882      84    84    84    85
                  13      1.0000  1.0000  1.0000      58    58    58    58
                  14      1.0000  1.0000  1.0000      13    13    13    13
                  15      1.0000  1.0000  1.0000      10    10    10    10
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      6980  6980
                  2      2952  2952
                  3       496   496
                  4        65    65
                  5         7     7
extra_word_added -1         2     2
                  0       529   529
                  1      1169  1169
                  2      1522  1522
                  3      1708  1708
                  4      1554  1554
                  5      1307  1307
                  6      1099  1099
                  7       722   722
                  8       465   465
                  9       178   178
                  10      145   145
                  11       53    53
                  12       35    35
                  13        9     9
                  14        2     2
                  15        1     1
extra_word_count  0       265   265
                  1       875   875
                  2      1309  1309
                  3      1688  1688
                  4      1659  1659
                  5      1468  1468
                  6      1276  1276
                  7       893   893
                  8       543   543
                  9       232   232
                  10      172   172
                  11       65    65
                  12       37    37
                  13       14    14
                  14        3     3
                  15        1     1
part_word_count   1       206   206
                  2       672   672
                  3      1105  1105
                  4      1605  1605
                  5      1559  1559
                  6      1495  1495
                  7      1398  1398
                  8       971   971
                  9       751   751
                  10      337   337
                  11      233   233
                  12       85    85
                  13       58    58
                  14       13    13
                  15       10    10
                  16        2     2

================================================================================

Statistics after processing 11000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9821  0.9930  0.9934    7186  7266  7269  7317
                  2       0.9718  0.9909  0.9929    2994  3053  3059  3081
                  3       0.9696  0.9886  0.9886     511   521   521   527
                  4       0.9265  0.9706  0.9706      63    66    66    68
                  5       1.0000  1.0000  1.0000       7     7     7     7
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9168  0.9638  0.9711     507   533   537   553
                  1       0.9705  0.9902  0.9902    1184  1208  1208  1220
                  2       0.9676  0.9900  0.9919    1554  1590  1593  1606
                  3       0.9844  0.9944  0.9944    1766  1784  1784  1794
                  4       0.9835  0.9951  0.9951    1605  1624  1624  1632
                  5       0.9905  0.9956  0.9956    1352  1359  1359  1365
                  6       0.9797  0.9921  0.9938    1112  1126  1128  1135
                  7       0.9907  0.9934  0.9934     747   749   749   754
                  8       0.9879  0.9980  0.9980     490   495   495   496
                  9       0.9947  1.0000  1.0000     187   188   188   188
                  10      1.0000  1.0000  1.0000     150   150   150   150
                  11      1.0000  1.0000  1.0000      57    57    57    57
                  12      1.0000  1.0000  1.0000      35    35    35    35
                  13      1.0000  1.0000  1.0000      10    10    10    10
                  14      1.0000  1.0000  1.0000       2     2     2     2
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9029  0.9460  0.9604     251   263   267   278
                  1       0.9683  0.9923  0.9923     885   907   907   914
                  2       0.9635  0.9883  0.9891    1321  1355  1356  1371
                  3       0.9791  0.9927  0.9927    1736  1760  1760  1773
                  4       0.9840  0.9954  0.9954    1718  1738  1738  1746
                  5       0.9870  0.9942  0.9948    1519  1530  1531  1539
                  6       0.9788  0.9917  0.9939    1294  1311  1314  1322
                  7       0.9893  0.9957  0.9957     922   928   928   932
                  8       0.9878  0.9965  0.9965     568   573   573   575
                  9       0.9919  0.9959  0.9959     244   245   245   246
                  10      0.9944  0.9944  0.9944     178   178   178   179
                  11      1.0000  1.0000  1.0000      69    69    69    69
                  12      1.0000  1.0000  1.0000      37    37    37    37
                  13      1.0000  1.0000  1.0000      15    15    15    15
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8977  0.9442  0.9628     193   203   207   215
                  2       0.9715  0.9915  0.9915     682   696   696   702
                  3       0.9733  0.9879  0.9888    1128  1145  1146  1159
                  4       0.9715  0.9917  0.9917    1639  1673  1673  1687
                  5       0.9773  0.9939  0.9939    1590  1617  1617  1627
                  6       0.9866  0.9949  0.9949    1551  1564  1564  1572
                  7       0.9781  0.9918  0.9938    1426  1446  1449  1458
                  8       0.9882  0.9941  0.9951    1002  1008  1009  1014
                  9       0.9849  0.9975  0.9975     782   792   792   794
                  10      0.9972  0.9972  0.9972     357   357   357   358
                  11      0.9916  0.9958  0.9958     236   237   237   238
                  12      0.9890  0.9890  0.9890      90    90    90    91
                  13      1.0000  1.0000  1.0000      59    59    59    59
                  14      1.0000  1.0000  1.0000      14    14    14    14
                  15      1.0000  1.0000  1.0000      10    10    10    10
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      7317  7317
                  2      3081  3081
                  3       527   527
                  4        68    68
                  5         7     7
extra_word_added -1         2     2
                  0       553   553
                  1      1220  1220
                  2      1606  1606
                  3      1794  1794
                  4      1632  1632
                  5      1365  1365
                  6      1135  1135
                  7       754   754
                  8       496   496
                  9       188   188
                  10      150   150
                  11       57    57
                  12       35    35
                  13       10    10
                  14        2     2
                  15        1     1
extra_word_count  0       278   278
                  1       914   914
                  2      1371  1371
                  3      1773  1773
                  4      1746  1746
                  5      1539  1539
                  6      1322  1322
                  7       932   932
                  8       575   575
                  9       246   246
                  10      179   179
                  11       69    69
                  12       37    37
                  13       15    15
                  14        3     3
                  15        1     1
part_word_count   1       215   215
                  2       702   702
                  3      1159  1159
                  4      1687  1687
                  5      1627  1627
                  6      1572  1572
                  7      1458  1458
                  8      1014  1014
                  9       794   794
                  10      358   358
                  11      238   238
                  12       91    91
                  13       59    59
                  14       14    14
                  15       10    10
                  16        2     2

================================================================================

Statistics after processing 11500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9825  0.9932  0.9936    7523  7605  7608  7657
                  2       0.9723  0.9913  0.9932    3128  3189  3195  3217
                  3       0.9709  0.9891  0.9891     534   544   544   550
                  4       0.9275  0.9710  0.9710      64    67    67    69
                  5       1.0000  1.0000  1.0000       7     7     7     7
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9183  0.9652  0.9722     528   555   559   575
                  1       0.9710  0.9906  0.9906    1238  1263  1263  1275
                  2       0.9685  0.9905  0.9923    1627  1664  1667  1680
                  3       0.9851  0.9947  0.9947    1845  1863  1863  1873
                  4       0.9836  0.9947  0.9947    1678  1697  1697  1706
                  5       0.9909  0.9958  0.9958    1413  1420  1420  1426
                  6       0.9806  0.9924  0.9941    1163  1177  1179  1186
                  7       0.9911  0.9936  0.9936     779   781   781   786
                  8       0.9865  0.9981  0.9981     513   519   519   520
                  9       0.9951  1.0000  1.0000     202   203   203   203
                  10      1.0000  1.0000  1.0000     157   157   157   157
                  11      1.0000  1.0000  1.0000      60    60    60    60
                  12      1.0000  1.0000  1.0000      36    36    36    36
                  13      1.0000  1.0000  1.0000      11    11    11    11
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9048  0.9490  0.9626     266   279   283   294
                  1       0.9684  0.9926  0.9926     919   942   942   949
                  2       0.9653  0.9889  0.9896    1389  1423  1424  1439
                  3       0.9794  0.9930  0.9930    1808  1833  1833  1846
                  4       0.9841  0.9951  0.9951    1799  1819  1819  1828
                  5       0.9876  0.9944  0.9950    1595  1606  1607  1615
                  6       0.9797  0.9920  0.9942    1348  1365  1368  1376
                  7       0.9897  0.9959  0.9959     960   966   966   970
                  8       0.9867  0.9967  0.9967     593   599   599   601
                  9       0.9924  0.9962  0.9962     262   263   263   264
                  10      0.9946  0.9946  0.9946     185   185   185   186
                  11      1.0000  1.0000  1.0000      72    72    72    72
                  12      1.0000  1.0000  1.0000      39    39    39    39
                  13      1.0000  1.0000  1.0000      16    16    16    16
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.8991  0.9474  0.9649     205   216   220   228
                  2       0.9713  0.9918  0.9918     711   726   726   732
                  3       0.9746  0.9885  0.9893    1188  1205  1206  1219
                  4       0.9726  0.9920  0.9920    1706  1740  1740  1754
                  5       0.9776  0.9941  0.9941    1659  1687  1687  1697
                  6       0.9866  0.9945  0.9945    1621  1634  1634  1643
                  7       0.9790  0.9921  0.9941    1495  1515  1518  1527
                  8       0.9887  0.9943  0.9953    1047  1053  1054  1059
                  9       0.9843  0.9976  0.9976     815   826   826   828
                  10      0.9973  0.9973  0.9973     373   373   373   374
                  11      0.9921  0.9960  0.9960     251   252   252   253
                  12      0.9895  0.9895  0.9895      94    94    94    95
                  13      1.0000  1.0000  1.0000      63    63    63    63
                  14      1.0000  1.0000  1.0000      14    14    14    14
                  15      1.0000  1.0000  1.0000      12    12    12    12
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      7657  7657
                  2      3217  3217
                  3       550   550
                  4        69    69
                  5         7     7
extra_word_added -1         2     2
                  0       575   575
                  1      1275  1275
                  2      1680  1680
                  3      1873  1873
                  4      1706  1706
                  5      1426  1426
                  6      1186  1186
                  7       786   786
                  8       520   520
                  9       203   203
                  10      157   157
                  11       60    60
                  12       36    36
                  13       11    11
                  14        3     3
                  15        1     1
extra_word_count  0       294   294
                  1       949   949
                  2      1439  1439
                  3      1846  1846
                  4      1828  1828
                  5      1615  1615
                  6      1376  1376
                  7       970   970
                  8       601   601
                  9       264   264
                  10      186   186
                  11       72    72
                  12       39    39
                  13       16    16
                  14        4     4
                  15        1     1
part_word_count   1       228   228
                  2       732   732
                  3      1219  1219
                  4      1754  1754
                  5      1697  1697
                  6      1643  1643
                  7      1527  1527
                  8      1059  1059
                  9       828   828
                  10      374   374
                  11      253   253
                  12       95    95
                  13       63    63
                  14       14    14
                  15       12    12
                  16        2     2

================================================================================

Statistics after processing 12000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9828  0.9934  0.9939    7848  7932  7936  7985
                  2       0.9723  0.9911  0.9928    3259  3322  3328  3352
                  3       0.9676  0.9863  0.9863     567   578   578   586
                  4       0.9286  0.9714  0.9714      65    68    68    70
                  5       1.0000  1.0000  1.0000       7     7     7     7
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9147  0.9615  0.9682     547   575   579   598
                  1       0.9720  0.9909  0.9909    1284  1309  1309  1321
                  2       0.9681  0.9909  0.9926    1702  1742  1745  1758
                  3       0.9853  0.9949  0.9949    1944  1963  1963  1973
                  4       0.9831  0.9938  0.9944    1743  1762  1763  1773
                  5       0.9913  0.9960  0.9960    1479  1486  1486  1492
                  6       0.9814  0.9927  0.9943    1214  1228  1230  1237
                  7       0.9914  0.9939  0.9939     808   810   810   815
                  8       0.9871  0.9982  0.9982     536   542   542   543
                  9       0.9953  1.0000  1.0000     211   212   212   212
                  10      1.0000  1.0000  1.0000     162   162   162   162
                  11      1.0000  1.0000  1.0000      62    62    62    62
                  12      1.0000  1.0000  1.0000      36    36    36    36
                  13      1.0000  1.0000  1.0000      12    12    12    12
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9052  0.9477  0.9608     277   290   294   306
                  1       0.9695  0.9929  0.9929     953   976   976   983
                  2       0.9654  0.9894  0.9900    1453  1489  1490  1505
                  3       0.9798  0.9928  0.9928    1895  1920  1920  1934
                  4       0.9832  0.9942  0.9947    1868  1889  1890  1900
                  5       0.9864  0.9941  0.9947    1673  1686  1687  1696
                  6       0.9805  0.9923  0.9944    1407  1424  1427  1435
                  7       0.9900  0.9960  0.9960     995  1001  1001  1005
                  8       0.9873  0.9968  0.9968     624   630   630   632
                  9       0.9928  0.9964  0.9964     274   275   275   276
                  10      0.9948  0.9948  0.9948     191   191   191   192
                  11      1.0000  1.0000  1.0000      74    74    74    74
                  12      1.0000  1.0000  1.0000      40    40    40    40
                  13      1.0000  1.0000  1.0000      17    17    17    17
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9025  0.9492  0.9661     213   224   228   236
                  2       0.9711  0.9908  0.9908     740   755   755   762
                  3       0.9756  0.9890  0.9898    1241  1258  1259  1272
                  4       0.9727  0.9924  0.9924    1784  1820  1820  1834
                  5       0.9774  0.9932  0.9938    1727  1755  1756  1767
                  6       0.9867  0.9948  0.9948    1700  1714  1714  1723
                  7       0.9780  0.9912  0.9931    1554  1575  1578  1589
                  8       0.9882  0.9946  0.9955    1089  1096  1097  1102
                  9       0.9850  0.9977  0.9977     851   862   862   864
                  10      0.9975  0.9975  0.9975     395   395   395   396
                  11      0.9924  0.9962  0.9962     261   262   262   263
                  12      0.9898  0.9898  0.9898      97    97    97    98
                  13      1.0000  1.0000  1.0000      64    64    64    64
                  14      1.0000  1.0000  1.0000      15    15    15    15
                  15      1.0000  1.0000  1.0000      13    13    13    13
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      7985  7985
                  2      3352  3352
                  3       586   586
                  4        70    70
                  5         7     7
extra_word_added -1         2     2
                  0       598   598
                  1      1321  1321
                  2      1758  1758
                  3      1973  1973
                  4      1773  1773
                  5      1492  1492
                  6      1237  1237
                  7       815   815
                  8       543   543
                  9       212   212
                  10      162   162
                  11       62    62
                  12       36    36
                  13       12    12
                  14        3     3
                  15        1     1
extra_word_count  0       306   306
                  1       983   983
                  2      1505  1505
                  3      1934  1934
                  4      1900  1900
                  5      1696  1696
                  6      1435  1435
                  7      1005  1005
                  8       632   632
                  9       276   276
                  10      192   192
                  11       74    74
                  12       40    40
                  13       17    17
                  14        4     4
                  15        1     1
part_word_count   1       236   236
                  2       762   762
                  3      1272  1272
                  4      1834  1834
                  5      1767  1767
                  6      1723  1723
                  7      1589  1589
                  8      1102  1102
                  9       864   864
                  10      396   396
                  11      263   263
                  12       98    98
                  13       64    64
                  14       15    15
                  15       13    13
                  16        2     2

================================================================================

Statistics after processing 12500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9830  0.9934  0.9939    8193  8280  8284  8335
                  2       0.9721  0.9908  0.9925    3379  3444  3450  3476
                  3       0.9688  0.9869  0.9869     590   601   601   609
                  4       0.9306  0.9722  0.9722      67    70    70    72
                  5       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9190  0.9635  0.9698     579   607   611   630
                  1       0.9714  0.9912  0.9912    1327  1354  1354  1366
                  2       0.9689  0.9913  0.9929    1777  1818  1821  1834
                  3       0.9848  0.9946  0.9946    2008  2028  2028  2039
                  4       0.9832  0.9941  0.9946    1819  1839  1840  1850
                  5       0.9910  0.9955  0.9955    1540  1547  1547  1554
                  6       0.9813  0.9922  0.9938    1260  1274  1276  1284
                  7       0.9919  0.9942  0.9942     857   859   859   864
                  8       0.9876  0.9982  0.9982     559   565   565   566
                  9       0.9955  1.0000  1.0000     221   222   222   222
                  10      0.9942  0.9942  0.9942     172   172   172   173
                  11      1.0000  1.0000  1.0000      64    64    64    64
                  12      1.0000  1.0000  1.0000      36    36    36    36
                  13      1.0000  1.0000  1.0000      12    12    12    12
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9105  0.9506  0.9630     295   308   312   324
                  1       0.9696  0.9931  0.9931     988  1012  1012  1019
                  2       0.9662  0.9898  0.9904    1515  1552  1553  1568
                  3       0.9795  0.9925  0.9925    1957  1983  1983  1998
                  4       0.9829  0.9945  0.9950    1953  1976  1977  1987
                  5       0.9864  0.9938  0.9943    1742  1755  1756  1766
                  6       0.9806  0.9920  0.9940    1463  1480  1483  1492
                  7       0.9906  0.9962  0.9962    1049  1055  1055  1059
                  8       0.9878  0.9970  0.9970     649   655   655   657
                  9       0.9931  0.9965  0.9965     287   288   288   289
                  10      0.9901  0.9901  0.9901     201   201   201   203
                  11      1.0000  1.0000  1.0000      76    76    76    76
                  12      1.0000  1.0000  1.0000      40    40    40    40
                  13      1.0000  1.0000  1.0000      17    17    17    17
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9080  0.9520  0.9680     227   238   242   250
                  2       0.9710  0.9912  0.9912     769   785   785   792
                  3       0.9766  0.9894  0.9902    1296  1313  1314  1327
                  4       0.9726  0.9921  0.9921    1844  1881  1881  1896
                  5       0.9777  0.9935  0.9940    1796  1825  1826  1837
                  6       0.9862  0.9945  0.9945    1787  1802  1802  1812
                  7       0.9775  0.9909  0.9927    1609  1631  1634  1646
                  8       0.9888  0.9948  0.9957    1146  1153  1154  1159
                  9       0.9855  0.9978  0.9978     886   897   897   899
                  10      0.9976  0.9976  0.9976     410   410   410   411
                  11      0.9928  0.9964  0.9964     274   275   275   276
                  12      0.9802  0.9802  0.9802      99    99    99   101
                  13      1.0000  1.0000  1.0000      64    64    64    64
                  14      1.0000  1.0000  1.0000      15    15    15    15
                  15      1.0000  1.0000  1.0000      13    13    13    13
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      8335  8335
                  2      3476  3476
                  3       609   609
                  4        72    72
                  5         8     8
extra_word_added -1         2     2
                  0       630   630
                  1      1366  1366
                  2      1834  1834
                  3      2039  2039
                  4      1850  1850
                  5      1554  1554
                  6      1284  1284
                  7       864   864
                  8       566   566
                  9       222   222
                  10      173   173
                  11       64    64
                  12       36    36
                  13       12    12
                  14        3     3
                  15        1     1
extra_word_count  0       324   324
                  1      1019  1019
                  2      1568  1568
                  3      1998  1998
                  4      1987  1987
                  5      1766  1766
                  6      1492  1492
                  7      1059  1059
                  8       657   657
                  9       289   289
                  10      203   203
                  11       76    76
                  12       40    40
                  13       17    17
                  14        4     4
                  15        1     1
part_word_count   1       250   250
                  2       792   792
                  3      1327  1327
                  4      1896  1896
                  5      1837  1837
                  6      1812  1812
                  7      1646  1646
                  8      1159  1159
                  9       899   899
                  10      411   411
                  11      276   276
                  12      101   101
                  13       64    64
                  14       15    15
                  15       13    13
                  16        2     2

================================================================================

Statistics after processing 13000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9823  0.9931  0.9935    8503  8596  8600  8656
                  2       0.9716  0.9906  0.9923    3521  3590  3596  3624
                  3       0.9685  0.9874  0.9874     615   627   627   635
                  4       0.9351  0.9740  0.9740      72    75    75    77
                  5       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9181  0.9621  0.9681     605   634   638   659
                  1       0.9711  0.9915  0.9915    1376  1405  1405  1417
                  2       0.9687  0.9911  0.9927    1854  1897  1900  1914
                  3       0.9834  0.9933  0.9933    2069  2090  2090  2104
                  4       0.9839  0.9943  0.9948    1893  1913  1914  1924
                  5       0.9901  0.9951  0.9951    1608  1616  1616  1624
                  6       0.9799  0.9925  0.9940    1314  1331  1333  1341
                  7       0.9922  0.9944  0.9944     893   895   895   900
                  8       0.9864  0.9983  0.9983     582   589   589   590
                  9       0.9957  1.0000  1.0000     229   230   230   230
                  10      0.9943  0.9943  0.9943     174   174   174   175
                  11      1.0000  1.0000  1.0000      65    65    65    65
                  12      1.0000  1.0000  1.0000      38    38    38    38
                  13      1.0000  1.0000  1.0000      13    13    13    13
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9086  0.9469  0.9587     308   321   325   339
                  1       0.9679  0.9934  0.9934    1024  1051  1051  1058
                  2       0.9670  0.9902  0.9908    1581  1619  1620  1635
                  3       0.9777  0.9913  0.9913    2015  2043  2043  2061
                  4       0.9836  0.9947  0.9952    2037  2060  2061  2071
                  5       0.9854  0.9930  0.9935    1818  1832  1833  1845
                  6       0.9794  0.9923  0.9942    1521  1541  1544  1553
                  7       0.9909  0.9964  0.9964    1092  1098  1098  1102
                  8       0.9869  0.9971  0.9971     679   686   686   688
                  9       0.9934  0.9967  0.9967     299   300   300   301
                  10      0.9902  0.9902  0.9902     203   203   203   205
                  11      1.0000  1.0000  1.0000      77    77    77    77
                  12      1.0000  1.0000  1.0000      42    42    42    42
                  13      1.0000  1.0000  1.0000      18    18    18    18
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9042  0.9464  0.9617     236   247   251   261
                  2       0.9709  0.9915  0.9915     801   818   818   825
                  3       0.9761  0.9899  0.9906    1349  1368  1369  1382
                  4       0.9714  0.9913  0.9913    1902  1941  1941  1958
                  5       0.9776  0.9932  0.9937    1873  1903  1904  1916
                  6       0.9857  0.9942  0.9942    1862  1878  1878  1889
                  7       0.9761  0.9907  0.9924    1671  1696  1699  1712
                  8       0.9892  0.9950  0.9959    1196  1203  1204  1209
                  9       0.9850  0.9979  0.9979     917   929   929   931
                  10      0.9977  0.9977  0.9977     431   431   431   432
                  11      0.9930  0.9965  0.9965     284   285   285   286
                  12      0.9804  0.9804  0.9804     100   100   100   102
                  13      1.0000  1.0000  1.0000      66    66    66    66
                  14      1.0000  1.0000  1.0000      16    16    16    16
                  15      1.0000  1.0000  1.0000      13    13    13    13
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      8656  8656
                  2      3624  3624
                  3       635   635
                  4        77    77
                  5         8     8
extra_word_added -1         2     2
                  0       659   659
                  1      1417  1417
                  2      1914  1914
                  3      2104  2104
                  4      1924  1924
                  5      1624  1624
                  6      1341  1341
                  7       900   900
                  8       590   590
                  9       230   230
                  10      175   175
                  11       65    65
                  12       38    38
                  13       13    13
                  14        3     3
                  15        1     1
extra_word_count  0       339   339
                  1      1058  1058
                  2      1635  1635
                  3      2061  2061
                  4      2071  2071
                  5      1845  1845
                  6      1553  1553
                  7      1102  1102
                  8       688   688
                  9       301   301
                  10      205   205
                  11       77    77
                  12       42    42
                  13       18    18
                  14        4     4
                  15        1     1
part_word_count   1       261   261
                  2       825   825
                  3      1382  1382
                  4      1958  1958
                  5      1916  1916
                  6      1889  1889
                  7      1712  1712
                  8      1209  1209
                  9       931   931
                  10      432   432
                  11      286   286
                  12      102   102
                  13       66    66
                  14       16    16
                  15       13    13
                  16        2     2

================================================================================

Statistics after processing 13500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9824  0.9931  0.9936    8843  8939  8943  9001
                  2       0.9713  0.9907  0.9923    3649  3722  3728  3757
                  3       0.9695  0.9878  0.9878     635   647   647   655
                  4       0.9367  0.9747  0.9747      74    77    77    79
                  5       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9202  0.9623  0.9681     634   663   667   689
                  1       0.9723  0.9919  0.9919    1438  1467  1467  1479
                  2       0.9692  0.9914  0.9929    1917  1961  1964  1978
                  3       0.9834  0.9936  0.9936    2137  2159  2159  2173
                  4       0.9840  0.9940  0.9945    1974  1994  1995  2006
                  5       0.9887  0.9947  0.9947    1668  1678  1678  1687
                  6       0.9784  0.9928  0.9942    1360  1380  1382  1390
                  7       0.9925  0.9947  0.9947     929   931   931   936
                  8       0.9871  0.9984  0.9984     611   618   618   619
                  9       0.9958  1.0000  1.0000     237   238   238   238
                  10      0.9945  0.9945  0.9945     180   180   180   181
                  11      1.0000  1.0000  1.0000      67    67    67    67
                  12      1.0000  1.0000  1.0000      38    38    38    38
                  13      1.0000  1.0000  1.0000      13    13    13    13
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9122  0.9490  0.9603     322   335   339   353
                  1       0.9692  0.9937  0.9937    1071  1098  1098  1105
                  2       0.9676  0.9906  0.9912    1645  1684  1685  1700
                  3       0.9780  0.9916  0.9916    2085  2114  2114  2132
                  4       0.9837  0.9944  0.9949    2115  2138  2139  2150
                  5       0.9839  0.9922  0.9927    1891  1907  1908  1922
                  6       0.9789  0.9926  0.9944    1578  1600  1603  1612
                  7       0.9904  0.9965  0.9965    1133  1140  1140  1144
                  8       0.9875  0.9972  0.9972     709   716   716   718
                  9       0.9935  0.9967  0.9967     305   306   306   307
                  10      0.9905  0.9905  0.9905     209   209   209   211
                  11      1.0000  1.0000  1.0000      78    78    78    78
                  12      1.0000  1.0000  1.0000      44    44    44    44
                  13      1.0000  1.0000  1.0000      19    19    19    19
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9077  0.9483  0.9631     246   257   261   271
                  2       0.9720  0.9918  0.9918     833   850   850   857
                  3       0.9764  0.9903  0.9910    1404  1424  1425  1438
                  4       0.9720  0.9916  0.9916    1977  2017  2017  2034
                  5       0.9780  0.9930  0.9935    1959  1989  1990  2003
                  6       0.9851  0.9939  0.9939    1923  1940  1940  1952
                  7       0.9751  0.9904  0.9921    1725  1752  1755  1769
                  8       0.9890  0.9953  0.9961    1254  1262  1263  1268
                  9       0.9845  0.9979  0.9979     955   968   968   970
                  10      0.9977  0.9977  0.9977     440   440   440   441
                  11      0.9932  0.9966  0.9966     291   292   292   293
                  12      0.9808  0.9808  0.9808     102   102   102   104
                  13      1.0000  1.0000  1.0000      68    68    68    68
                  14      1.0000  1.0000  1.0000      16    16    16    16
                  15      1.0000  1.0000  1.0000      14    14    14    14
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      9001  9001
                  2      3757  3757
                  3       655   655
                  4        79    79
                  5         8     8
extra_word_added -1         2     2
                  0       689   689
                  1      1479  1479
                  2      1978  1978
                  3      2173  2173
                  4      2006  2006
                  5      1687  1687
                  6      1390  1390
                  7       936   936
                  8       619   619
                  9       238   238
                  10      181   181
                  11       67    67
                  12       38    38
                  13       13    13
                  14        3     3
                  15        1     1
extra_word_count  0       353   353
                  1      1105  1105
                  2      1700  1700
                  3      2132  2132
                  4      2150  2150
                  5      1922  1922
                  6      1612  1612
                  7      1144  1144
                  8       718   718
                  9       307   307
                  10      211   211
                  11       78    78
                  12       44    44
                  13       19    19
                  14        4     4
                  15        1     1
part_word_count   1       271   271
                  2       857   857
                  3      1438  1438
                  4      2034  2034
                  5      2003  2003
                  6      1952  1952
                  7      1769  1769
                  8      1268  1268
                  9       970   970
                  10      441   441
                  11      293   293
                  12      104   104
                  13       68    68
                  14       16    16
                  15       14    14
                  16        2     2

================================================================================

Statistics after processing 14000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9822  0.9932  0.9936    9179  9281  9285  9345
                  2       0.9717  0.9905  0.9923    3780  3853  3860  3890
                  3       0.9688  0.9866  0.9866     653   665   665   674
                  4       0.9277  0.9639  0.9759      77    80    81    83
                  5       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9208  0.9618  0.9689     651   680   685   707
                  1       0.9732  0.9922  0.9922    1488  1517  1517  1529
                  2       0.9689  0.9908  0.9922    1993  2038  2041  2057
                  3       0.9833  0.9934  0.9934    2234  2257  2257  2272
                  4       0.9836  0.9942  0.9947    2040  2062  2063  2074
                  5       0.9886  0.9948  0.9948    1727  1738  1738  1747
                  6       0.9785  0.9924  0.9945    1411  1431  1434  1442
                  7       0.9927  0.9948  0.9948     957   959   959   964
                  8       0.9844  0.9969  0.9969     632   640   640   642
                  9       0.9960  1.0000  1.0000     248   249   249   249
                  10      0.9947  0.9947  0.9947     186   186   186   187
                  11      1.0000  1.0000  1.0000      68    68    68    68
                  12      1.0000  1.0000  1.0000      42    42    42    42
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9123  0.9479  0.9616     333   346   351   365
                  1       0.9701  0.9938  0.9938    1103  1130  1130  1137
                  2       0.9677  0.9904  0.9909    1708  1748  1749  1765
                  3       0.9785  0.9919  0.9919    2182  2212  2212  2230
                  4       0.9834  0.9946  0.9951    2192  2217  2218  2229
                  5       0.9834  0.9920  0.9925    1956  1973  1974  1989
                  6       0.9784  0.9916  0.9940    1634  1656  1660  1670
                  7       0.9907  0.9966  0.9966    1166  1173  1173  1177
                  8       0.9852  0.9960  0.9960     733   741   741   744
                  9       0.9938  0.9969  0.9969     319   320   320   321
                  10      0.9910  0.9910  0.9910     219   219   219   221
                  11      1.0000  1.0000  1.0000      79    79    79    79
                  12      1.0000  1.0000  1.0000      48    48    48    48
                  13      1.0000  1.0000  1.0000      20    20    20    20
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9071  0.9464  0.9643     254   265   270   280
                  2       0.9729  0.9921  0.9921     860   877   877   884
                  3       0.9772  0.9906  0.9913    1460  1480  1481  1494
                  4       0.9716  0.9915  0.9915    2054  2096  2096  2114
                  5       0.9784  0.9933  0.9938    2042  2073  2074  2087
                  6       0.9842  0.9936  0.9936    1987  2006  2006  2019
                  7       0.9755  0.9902  0.9924    1792  1819  1823  1837
                  8       0.9885  0.9946  0.9954    1289  1297  1298  1304
                  9       0.9831  0.9970  0.9970     989  1003  1003  1006
                  10      0.9978  0.9978  0.9978     454   454   454   455
                  11      0.9935  0.9967  0.9967     304   305   305   306
                  12      0.9811  0.9811  0.9811     104   104   104   106
                  13      1.0000  1.0000  1.0000      74    74    74    74
                  14      1.0000  1.0000  1.0000      17    17    17    17
                  15      1.0000  1.0000  1.0000      15    15    15    15
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      9345  9345
                  2      3890  3890
                  3       674   674
                  4        83    83
                  5         8     8
extra_word_added -1         2     2
                  0       707   707
                  1      1529  1529
                  2      2057  2057
                  3      2272  2272
                  4      2074  2074
                  5      1747  1747
                  6      1442  1442
                  7       964   964
                  8       642   642
                  9       249   249
                  10      187   187
                  11       68    68
                  12       42    42
                  13       14    14
                  14        3     3
                  15        1     1
extra_word_count  0       365   365
                  1      1137  1137
                  2      1765  1765
                  3      2230  2230
                  4      2229  2229
                  5      1989  1989
                  6      1670  1670
                  7      1177  1177
                  8       744   744
                  9       321   321
                  10      221   221
                  11       79    79
                  12       48    48
                  13       20    20
                  14        4     4
                  15        1     1
part_word_count   1       280   280
                  2       884   884
                  3      1494  1494
                  4      2114  2114
                  5      2087  2087
                  6      2019  2019
                  7      1837  1837
                  8      1304  1304
                  9      1006  1006
                  10      455   455
                  11      306   306
                  12      106   106
                  13       74    74
                  14       17    17
                  15       15    15
                  16        2     2

================================================================================

Statistics after processing 14500 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9821  0.9930  0.9935    9505  9610  9615  9678
                  2       0.9713  0.9906  0.9923    3922  4000  4007  4038
                  3       0.9697  0.9870  0.9870     672   684   684   693
                  4       0.9277  0.9639  0.9759      77    80    81    83
                  5       1.0000  1.0000  1.0000       8     8     8     8
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9211  0.9619  0.9701     677   707   713   735
                  1       0.9724  0.9918  0.9918    1550  1581  1581  1594
                  2       0.9695  0.9906  0.9920    2066  2111  2114  2131
                  3       0.9834  0.9936  0.9936    2311  2335  2335  2350
                  4       0.9828  0.9939  0.9944    2110  2134  2135  2147
                  5       0.9889  0.9950  0.9950    1781  1792  1792  1801
                  6       0.9773  0.9920  0.9940    1467  1489  1492  1501
                  7       0.9930  0.9950  0.9950     986   988   988   993
                  8       0.9851  0.9970  0.9970     662   670   670   672
                  9       0.9961  1.0000  1.0000     254   255   255   255
                  10      0.9947  0.9947  0.9947     189   189   189   190
                  11      1.0000  1.0000  1.0000      69    69    69    69
                  12      1.0000  1.0000  1.0000      42    42    42    42
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9132  0.9474  0.9632     347   360   366   380
                  1       0.9695  0.9932  0.9932    1145  1173  1173  1181
                  2       0.9678  0.9902  0.9907    1773  1814  1815  1832
                  3       0.9788  0.9922  0.9922    2260  2291  2291  2309
                  4       0.9831  0.9944  0.9948    2272  2298  2299  2311
                  5       0.9834  0.9922  0.9927    2010  2028  2029  2044
                  6       0.9770  0.9914  0.9937    1701  1726  1730  1741
                  7       0.9910  0.9967  0.9967    1208  1215  1215  1219
                  8       0.9858  0.9961  0.9961     766   774   774   777
                  9       0.9939  0.9970  0.9970     327   328   328   329
                  10      0.9911  0.9911  0.9911     222   222   222   224
                  11      1.0000  1.0000  1.0000      80    80    80    80
                  12      1.0000  1.0000  1.0000      48    48    48    48
                  13      1.0000  1.0000  1.0000      20    20    20    20
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9075  0.9452  0.9658     265   276   282   292
                  2       0.9739  0.9924  0.9924     895   912   912   919
                  3       0.9761  0.9897  0.9903    1513  1534  1535  1550
                  4       0.9717  0.9918  0.9918    2131  2175  2175  2193
                  5       0.9786  0.9930  0.9935    2103  2134  2135  2149
                  6       0.9843  0.9938  0.9938    2064  2084  2084  2097
                  7       0.9747  0.9900  0.9921    1852  1881  1885  1900
                  8       0.9874  0.9948  0.9955    1331  1341  1342  1348
                  9       0.9839  0.9972  0.9972    1039  1053  1053  1056
                  10      0.9979  0.9979  0.9979     467   467   467   468
                  11      0.9936  0.9968  0.9968     310   311   311   312
                  12      0.9815  0.9815  0.9815     106   106   106   108
                  13      1.0000  1.0000  1.0000      74    74    74    74
                  14      1.0000  1.0000  1.0000      17    17    17    17
                  15      1.0000  1.0000  1.0000      15    15    15    15
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      9678  9678
                  2      4038  4038
                  3       693   693
                  4        83    83
                  5         8     8
extra_word_added -1         2     2
                  0       735   735
                  1      1594  1594
                  2      2131  2131
                  3      2350  2350
                  4      2147  2147
                  5      1801  1801
                  6      1501  1501
                  7       993   993
                  8       672   672
                  9       255   255
                  10      190   190
                  11       69    69
                  12       42    42
                  13       14    14
                  14        3     3
                  15        1     1
extra_word_count  0       380   380
                  1      1181  1181
                  2      1832  1832
                  3      2309  2309
                  4      2311  2311
                  5      2044  2044
                  6      1741  1741
                  7      1219  1219
                  8       777   777
                  9       329   329
                  10      224   224
                  11       80    80
                  12       48    48
                  13       20    20
                  14        4     4
                  15        1     1
part_word_count   1       292   292
                  2       919   919
                  3      1550  1550
                  4      2193  2193
                  5      2149  2149
                  6      2097  2097
                  7      1900  1900
                  8      1348  1348
                  9      1056  1056
                  10      468   468
                  11      312   312
                  12      108   108
                  13       74    74
                  14       17    17
                  15       15    15
                  16        2     2

================================================================================

Statistics after processing 15000 samples:
================================================================================

                        accuracy                 matches             total  \
metric                      top1    top3    top5    top1  top3  top5  top1
category         subcat
edit_count        1       0.9819  0.9926  0.9932    9817  9924  9930  9998
                  2       0.9721  0.9909  0.9926    4078  4157  4164  4195
                  3       0.9705  0.9873  0.9873     690   702   702   711
                  4       0.9310  0.9655  0.9770      81    84    85    87
                  5       1.0000  1.0000  1.0000       9     9     9     9
extra_word_added -1       1.0000  1.0000  1.0000       2     2     2     2
                  0       0.9212  0.9619  0.9698     701   732   738   761
                  1       0.9727  0.9915  0.9915    1601  1632  1632  1646
                  2       0.9704  0.9909  0.9923    2134  2179  2182  2199
                  3       0.9836  0.9934  0.9934    2393  2417  2417  2433
                  4       0.9833  0.9941  0.9946    2182  2206  2207  2219
                  5       0.9867  0.9936  0.9941    1852  1865  1866  1877
                  6       0.9782  0.9923  0.9942    1523  1545  1548  1557
                  7       0.9931  0.9951  0.9951    1013  1015  1015  1020
                  8       0.9856  0.9971  0.9971     684   692   692   694
                  9       0.9962  1.0000  1.0000     263   264   264   264
                  10      0.9949  0.9949  0.9949     195   195   195   196
                  11      1.0000  1.0000  1.0000      71    71    71    71
                  12      1.0000  1.0000  1.0000      43    43    43    43
                  13      1.0000  1.0000  1.0000      14    14    14    14
                  14      1.0000  1.0000  1.0000       3     3     3     3
                  15      1.0000  1.0000  1.0000       1     1     1     1
extra_word_count  0       0.9141  0.9470  0.9621     362   375   381   396
                  1       0.9688  0.9926  0.9926    1178  1207  1207  1216
                  2       0.9688  0.9905  0.9910    1832  1873  1874  1891
                  3       0.9791  0.9920  0.9920    2339  2370  2370  2389
                  4       0.9836  0.9945  0.9950    2344  2370  2371  2383
                  5       0.9816  0.9911  0.9920    2085  2105  2107  2124
                  6       0.9779  0.9917  0.9939    1769  1794  1798  1809
                  7       0.9912  0.9968  0.9968    1246  1253  1253  1257
                  8       0.9864  0.9963  0.9963     795   803   803   806
                  9       0.9941  0.9971  0.9971     337   338   338   339
                  10      0.9914  0.9914  0.9914     231   231   231   233
                  11      1.0000  1.0000  1.0000      83    83    83    83
                  12      1.0000  1.0000  1.0000      49    49    49    49
                  13      1.0000  1.0000  1.0000      20    20    20    20
                  14      1.0000  1.0000  1.0000       4     4     4     4
                  15      1.0000  1.0000  1.0000       1     1     1     1
part_word_count   1       0.9085  0.9444  0.9641     278   289   295   306
                  2       0.9735  0.9915  0.9915     920   937   937   945
                  3       0.9768  0.9900  0.9906    1561  1582  1583  1598
                  4       0.9718  0.9916  0.9916    2208  2253  2253  2272
                  5       0.9792  0.9932  0.9937    2170  2201  2202  2216
                  6       0.9834  0.9935  0.9935    2133  2155  2155  2169
                  7       0.9746  0.9893  0.9919    1921  1950  1955  1971
                  8       0.9878  0.9950  0.9957    1377  1387  1388  1394
                  9       0.9844  0.9973  0.9973    1076  1090  1090  1093
                  10      0.9980  0.9980  0.9980     490   490   490   491
                  11      0.9938  0.9969  0.9969     319   320   320   321
                  12      0.9823  0.9823  0.9823     111   111   111   113
                  13      1.0000  1.0000  1.0000      77    77    77    77
                  14      1.0000  1.0000  1.0000      17    17    17    17
                  15      1.0000  1.0000  1.0000      15    15    15    15
                  16      1.0000  1.0000  1.0000       2     2     2     2


metric                   top3  top5
category         subcat
edit_count        1      9998  9998
                  2      4195  4195
                  3       711   711
                  4        87    87
                  5         9     9
extra_word_added -1         2     2
                  0       761   761
                  1      1646  1646
                  2      2199  2199
                  3      2433  2433
                  4      2219  2219
                  5      1877  1877
                  6      1557  1557
                  7      1020  1020
                  8       694   694
                  9       264   264
                  10      196   196
                  11       71    71
                  12       43    43
                  13       14    14
                  14        3     3
                  15        1     1
extra_word_count  0       396   396
                  1      1216  1216
                  2      1891  1891
                  3      2389  2389
                  4      2383  2383
                  5      2124  2124
                  6      1809  1809
                  7      1257  1257
                  8       806   806
                  9       339   339
                  10      233   233
                  11       83    83
                  12       49    49
                  13       20    20
                  14        4     4
                  15        1     1
part_word_count   1       306   306
                  2       945   945
                  3      1598  1598
                  4      2272  2272
                  5      2216  2216
                  6      2169  2169
                  7      1971  1971
                  8      1394  1394
                  9      1093  1093
                  10      491   491
                  11      321   321
                  12      113   113
                  13       77    77
                  14       17    17
                  15       15    15
                  16        2     2

================================================================================

Statistics after processing 15500 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9821  0.9924  0.9930   10136  10243  10249  10321
                  2       0.9722  0.9910  0.9926    4229   4311   4318   4350
                  3       0.9699  0.9863  0.9863     709    721    721    731
                  4       0.9326  0.9663  0.9775      83     86     87     89
                  5       1.0000  1.0000  1.0000       9      9      9      9
extra_word_added -1       1.0000  1.0000  1.0000       2      2      2      2
                  0       0.9221  0.9617  0.9693     722    753    759    783
                  1       0.9735  0.9917  0.9917    1650   1681   1681   1695
                  2       0.9704  0.9903  0.9916    2200   2245   2248   2267
                  3       0.9833  0.9932  0.9932    2473   2498   2498   2515
                  4       0.9830  0.9939  0.9943    2258   2283   2284   2297
                  5       0.9861  0.9933  0.9938    1919   1933   1934   1946
                  6       0.9788  0.9925  0.9944    1571   1593   1596   1605
                  7       0.9934  0.9953  0.9953    1050   1052   1052   1057
                  8       0.9860  0.9972  0.9972     704    712    712    714
                  9       0.9964  1.0000  1.0000     276    277    277    277
                  10      0.9951  0.9951  0.9951     204    204    204    205
                  11      1.0000  1.0000  1.0000      74     74     74     74
                  12      1.0000  1.0000  1.0000      44     44     44     44
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       3      3      3      3
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9160  0.9481  0.9630     371    384    390    405
                  1       0.9689  0.9920  0.9920    1215   1244   1244   1254
                  2       0.9687  0.9897  0.9903    1889   1930   1931   1950
                  3       0.9790  0.9919  0.9919    2422   2454   2454   2474
                  4       0.9842  0.9947  0.9951    2422   2448   2449   2461
                  5       0.9817  0.9909  0.9918    2149   2169   2171   2189
                  6       0.9775  0.9914  0.9936    1825   1851   1855   1867
                  7       0.9908  0.9969  0.9969    1297   1305   1305   1309
                  8       0.9868  0.9964  0.9964     821    829    829    832
                  9       0.9944  0.9972  0.9972     352    353    353    354
                  10      0.9918  0.9918  0.9918     241    241    241    243
                  11      1.0000  1.0000  1.0000      86     86     86     86
                  12      1.0000  1.0000  1.0000      50     50     50     50
                  13      1.0000  1.0000  1.0000      21     21     21     21
                  14      1.0000  1.0000  1.0000       4      4      4      4
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9100  0.9453  0.9646     283    294    300    311
                  2       0.9733  0.9908  0.9908     949    966    966    975
                  3       0.9763  0.9891  0.9897    1606   1627   1628   1645
                  4       0.9722  0.9919  0.9919    2277   2323   2323   2342
                  5       0.9796  0.9931  0.9935    2256   2287   2288   2303
                  6       0.9835  0.9933  0.9933    2203   2225   2225   2240
                  7       0.9753  0.9896  0.9921    1978   2007   2012   2028
                  8       0.9868  0.9945  0.9951    1424   1435   1436   1443
                  9       0.9842  0.9974  0.9974    1122   1137   1137   1140
                  10      0.9980  0.9980  0.9980     511    511    511    512
                  11      0.9940  0.9970  0.9970     329    330    330    331
                  12      0.9828  0.9828  0.9828     114    114    114    116
                  13      1.0000  1.0000  1.0000      78     78     78     78
                  14      1.0000  1.0000  1.0000      19     19     19     19
                  15      1.0000  1.0000  1.0000      15     15     15     15
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      10321  10321
                  2       4350   4350
                  3        731    731
                  4         89     89
                  5          9      9
extra_word_added -1          2      2
                  0        783    783
                  1       1695   1695
                  2       2267   2267
                  3       2515   2515
                  4       2297   2297
                  5       1946   1946
                  6       1605   1605
                  7       1057   1057
                  8        714    714
                  9        277    277
                  10       205    205
                  11        74     74
                  12        44     44
                  13        15     15
                  14         3      3
                  15         1      1
extra_word_count  0        405    405
                  1       1254   1254
                  2       1950   1950
                  3       2474   2474
                  4       2461   2461
                  5       2189   2189
                  6       1867   1867
                  7       1309   1309
                  8        832    832
                  9        354    354
                  10       243    243
                  11        86     86
                  12        50     50
                  13        21     21
                  14         4      4
                  15         1      1
part_word_count   1        311    311
                  2        975    975
                  3       1645   1645
                  4       2342   2342
                  5       2303   2303
                  6       2240   2240
                  7       2028   2028
                  8       1443   1443
                  9       1140   1140
                  10       512    512
                  11       331    331
                  12       116    116
                  13        78     78
                  14        19     19
                  15        15     15
                  16         2      2

================================================================================
***extra_word_added < 0: -1, part: Expect much better numbers on James , label: Confidence is high, and the team is eager to showcase their hard work. Expect much better numbers on James home turf this week. With the pressure mounting, James feels a mix of excitement and nerves as the match approaches., edits_made: [((0, 1), (0, 1)), ((5, 6), (5, 7))]

Statistics after processing 16000 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9821  0.9924  0.9930   10450  10559  10566  10640
                  2       0.9719  0.9913  0.9929    4360   4447   4454   4486
                  3       0.9702  0.9857  0.9857     748    760    760    771
                  4       0.9362  0.9681  0.9787      88     91     92     94
                  5       1.0000  1.0000  1.0000       9      9      9      9
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9251  0.9631  0.9705     753    784    790    814
                  1       0.9738  0.9915  0.9915    1710   1741   1741   1756
                  2       0.9705  0.9906  0.9919    2269   2316   2319   2338
                  3       0.9827  0.9927  0.9931    2549   2575   2576   2594
                  4       0.9831  0.9941  0.9945    2330   2356   2357   2370
                  5       0.9851  0.9936  0.9941    1987   2004   2005   2017
                  6       0.9794  0.9927  0.9945    1616   1638   1641   1650
                  7       0.9935  0.9954  0.9954    1076   1078   1078   1083
                  8       0.9865  0.9973  0.9973     731    739    739    741
                  9       0.9931  0.9965  0.9965     287    288    288    289
                  10      0.9952  0.9952  0.9952     206    206    206    207
                  11      1.0000  1.0000  1.0000      74     74     74     74
                  12      1.0000  1.0000  1.0000      45     45     45     45
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       3      3      3      3
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9196  0.9504  0.9645     389    402    408    423
                  1       0.9699  0.9923  0.9923    1255   1284   1284   1294
                  2       0.9683  0.9896  0.9901    1957   2000   2001   2021
                  3       0.9788  0.9914  0.9917    2490   2522   2523   2544
                  4       0.9843  0.9949  0.9953    2509   2536   2537   2549
                  5       0.9819  0.9912  0.9921    2226   2247   2249   2267
                  6       0.9765  0.9917  0.9937    1873   1902   1906   1918
                  7       0.9910  0.9970  0.9970    1328   1336   1336   1340
                  8       0.9873  0.9965  0.9965     854    862    862    865
                  9       0.9919  0.9946  0.9946     366    367    367    369
                  10      0.9918  0.9918  0.9918     243    243    243    245
                  11      1.0000  1.0000  1.0000      86     86     86     86
                  12      1.0000  1.0000  1.0000      51     51     51     51
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       4      4      4      4
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9141  0.9479  0.9663     298    309    315    326
                  2       0.9742  0.9911  0.9911     980    997    997   1006
                  3       0.9759  0.9894  0.9900    1662   1685   1686   1703
                  4       0.9726  0.9917  0.9917    2344   2390   2390   2410
                  5       0.9794  0.9924  0.9933    2333   2364   2366   2382
                  6       0.9836  0.9935  0.9935    2286   2309   2309   2324
                  7       0.9755  0.9899  0.9923    2033   2063   2068   2084
                  8       0.9858  0.9946  0.9953    1458   1471   1472   1479
                  9       0.9839  0.9975  0.9975    1163   1179   1179   1182
                  10      0.9962  0.9962  0.9962     530    530    530    532
                  11      0.9941  0.9970  0.9970     336    337    337    338
                  12      0.9829  0.9829  0.9829     115    115    115    117
                  13      1.0000  1.0000  1.0000      78     78     78     78
                  14      1.0000  1.0000  1.0000      22     22     22     22
                  15      1.0000  1.0000  1.0000      15     15     15     15
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      10640  10640
                  2       4486   4486
                  3        771    771
                  4         94     94
                  5          9      9
extra_word_added -1          3      3
                  0        814    814
                  1       1756   1756
                  2       2338   2338
                  3       2594   2594
                  4       2370   2370
                  5       2017   2017
                  6       1650   1650
                  7       1083   1083
                  8        741    741
                  9        289    289
                  10       207    207
                  11        74     74
                  12        45     45
                  13        15     15
                  14         3      3
                  15         1      1
extra_word_count  0        423    423
                  1       1294   1294
                  2       2021   2021
                  3       2544   2544
                  4       2549   2549
                  5       2267   2267
                  6       1918   1918
                  7       1340   1340
                  8        865    865
                  9        369    369
                  10       245    245
                  11        86     86
                  12        51     51
                  13        23     23
                  14         4      4
                  15         1      1
part_word_count   1        326    326
                  2       1006   1006
                  3       1703   1703
                  4       2410   2410
                  5       2382   2382
                  6       2324   2324
                  7       2084   2084
                  8       1479   1479
                  9       1182   1182
                  10       532    532
                  11       338    338
                  12       117    117
                  13        78     78
                  14        22     22
                  15        15     15
                  16         2      2

================================================================================

Statistics after processing 16500 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9823  0.9925  0.9932   10771  10883  10890  10965
                  2       0.9725  0.9916  0.9931    4499   4587   4594   4626
                  3       0.9698  0.9862  0.9862     772    785    785    796
                  4       0.9320  0.9612  0.9709      96     99    100    103
                  5       0.9000  1.0000  1.0000       9     10     10     10
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9276  0.9644  0.9715     782    813    819    843
                  1       0.9737  0.9912  0.9912    1775   1807   1807   1823
                  2       0.9709  0.9908  0.9921    2332   2380   2383   2402
                  3       0.9824  0.9925  0.9929    2623   2650   2651   2670
                  4       0.9833  0.9943  0.9947    2410   2437   2438   2451
                  5       0.9856  0.9938  0.9942    2053   2070   2071   2083
                  6       0.9794  0.9929  0.9947    1661   1684   1687   1696
                  7       0.9928  0.9955  0.9955    1107   1110   1110   1115
                  8       0.9869  0.9974  0.9974     754    762    762    764
                  9       0.9933  0.9966  0.9966     296    297    297    298
                  10      0.9952  0.9952  0.9952     208    208    208    209
                  11      1.0000  1.0000  1.0000      78     78     78     78
                  12      1.0000  1.0000  1.0000      45     45     45     45
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       4      4      4      4
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9226  0.9522  0.9658     405    418    424    439
                  1       0.9709  0.9925  0.9925    1303   1332   1332   1342
                  2       0.9688  0.9899  0.9904    2017   2061   2062   2082
                  3       0.9790  0.9912  0.9916    2560   2592   2593   2615
                  4       0.9840  0.9951  0.9954    2591   2620   2621   2633
                  5       0.9825  0.9915  0.9923    2307   2328   2330   2348
                  6       0.9767  0.9919  0.9939    1926   1956   1960   1972
                  7       0.9898  0.9971  0.9971    1365   1375   1375   1379
                  8       0.9865  0.9955  0.9955     880    888    888    892
                  9       0.9921  0.9947  0.9947     376    377    377    379
                  10      0.9919  0.9919  0.9919     245    245    245    247
                  11      1.0000  1.0000  1.0000      92     92     92     92
                  12      1.0000  1.0000  1.0000      51     51     51     51
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9169  0.9496  0.9674     309    320    326    337
                  2       0.9752  0.9914  0.9914    1022   1039   1039   1048
                  3       0.9760  0.9897  0.9903    1709   1733   1734   1751
                  4       0.9730  0.9915  0.9915    2414   2460   2460   2481
                  5       0.9797  0.9927  0.9935    2408   2440   2442   2458
                  6       0.9837  0.9937  0.9937    2359   2383   2383   2398
                  7       0.9763  0.9902  0.9926    2097   2127   2132   2148
                  8       0.9850  0.9948  0.9954    1510   1525   1526   1533
                  9       0.9843  0.9975  0.9975    1193   1209   1209   1212
                  10      0.9963  0.9963  0.9963     544    544    544    546
                  11      0.9942  0.9971  0.9971     344    345    345    346
                  12      0.9752  0.9835  0.9835     118    119    119    121
                  13      0.9875  0.9875  0.9875      79     79     79     80
                  14      1.0000  1.0000  1.0000      22     22     22     22
                  15      1.0000  1.0000  1.0000      17     17     17     17
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      10965  10965
                  2       4626   4626
                  3        796    796
                  4        103    103
                  5         10     10
extra_word_added -1          3      3
                  0        843    843
                  1       1823   1823
                  2       2402   2402
                  3       2670   2670
                  4       2451   2451
                  5       2083   2083
                  6       1696   1696
                  7       1115   1115
                  8        764    764
                  9        298    298
                  10       209    209
                  11        78     78
                  12        45     45
                  13        15     15
                  14         4      4
                  15         1      1
extra_word_count  0        439    439
                  1       1342   1342
                  2       2082   2082
                  3       2615   2615
                  4       2633   2633
                  5       2348   2348
                  6       1972   1972
                  7       1379   1379
                  8        892    892
                  9        379    379
                  10       247    247
                  11        92     92
                  12        51     51
                  13        23     23
                  14         5      5
                  15         1      1
part_word_count   1        337    337
                  2       1048   1048
                  3       1751   1751
                  4       2481   2481
                  5       2458   2458
                  6       2398   2398
                  7       2148   2148
                  8       1533   1533
                  9       1212   1212
                  10       546    546
                  11       346    346
                  12       121    121
                  13        80     80
                  14        22     22
                  15        17     17
                  16         2      2

================================================================================

Statistics after processing 17000 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9821  0.9927  0.9933   11106  11225  11232  11308
                  2       0.9727  0.9916  0.9931    4630   4720   4727   4760
                  3       0.9707  0.9866  0.9866     794    807    807    818
                  4       0.9320  0.9612  0.9709      96     99    100    103
                  5       0.9091  1.0000  1.0000      10     11     11     11
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9273  0.9654  0.9723     804    837    843    867
                  1       0.9733  0.9909  0.9909    1823   1856   1856   1873
                  2       0.9715  0.9910  0.9923    2383   2431   2434   2453
                  3       0.9825  0.9927  0.9931    2702   2730   2731   2750
                  4       0.9830  0.9945  0.9949    2491   2520   2521   2534
                  5       0.9861  0.9940  0.9944    2121   2138   2139   2151
                  6       0.9801  0.9932  0.9949    1721   1744   1747   1756
                  7       0.9896  0.9948  0.9948    1142   1148   1148   1154
                  8       0.9874  0.9975  0.9975     781    789    789    791
                  9       0.9935  0.9967  0.9967     304    305    305    306
                  10      0.9954  0.9954  0.9954     215    215    215    216
                  11      1.0000  1.0000  1.0000      79     79     79     79
                  12      1.0000  1.0000  1.0000      46     46     46     46
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9226  0.9535  0.9668     417    431    437    452
                  1       0.9703  0.9920  0.9920    1339   1369   1369   1380
                  2       0.9695  0.9901  0.9906    2064   2108   2109   2129
                  3       0.9792  0.9915  0.9918    2638   2671   2672   2694
                  4       0.9834  0.9952  0.9956    2674   2706   2707   2719
                  5       0.9831  0.9917  0.9926    2382   2403   2405   2423
                  6       0.9775  0.9922  0.9941    1994   2024   2028   2040
                  7       0.9880  0.9972  0.9972    1404   1417   1417   1421
                  8       0.9870  0.9957  0.9957     911    919    919    923
                  9       0.9897  0.9923  0.9923     384    385    385    388
                  10      0.9922  0.9922  0.9922     254    254    254    256
                  11      1.0000  1.0000  1.0000      93     93     93     93
                  12      1.0000  1.0000  1.0000      52     52     52     52
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9140  0.9484  0.9656     319    331    337    349
                  2       0.9758  0.9916  0.9916    1050   1067   1067   1076
                  3       0.9760  0.9900  0.9905    1750   1775   1776   1793
                  4       0.9734  0.9918  0.9918    2485   2532   2532   2553
                  5       0.9799  0.9929  0.9937    2490   2523   2525   2541
                  6       0.9834  0.9939  0.9939    2432   2458   2458   2473
                  7       0.9770  0.9905  0.9928    2167   2197   2202   2218
                  8       0.9842  0.9949  0.9956    1559   1576   1577   1584
                  9       0.9840  0.9976  0.9976    1228   1245   1245   1248
                  10      0.9964  0.9964  0.9964     560    560    560    562
                  11      0.9916  0.9944  0.9944     354    355    355    357
                  12      0.9754  0.9836  0.9836     119    120    120    122
                  13      0.9878  0.9878  0.9878      81     81     81     82
                  14      1.0000  1.0000  1.0000      22     22     22     22
                  15      1.0000  1.0000  1.0000      18     18     18     18
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      11308  11308
                  2       4760   4760
                  3        818    818
                  4        103    103
                  5         11     11
extra_word_added -1          3      3
                  0        867    867
                  1       1873   1873
                  2       2453   2453
                  3       2750   2750
                  4       2534   2534
                  5       2151   2151
                  6       1756   1756
                  7       1154   1154
                  8        791    791
                  9        306    306
                  10       216    216
                  11        79     79
                  12        46     46
                  13        15     15
                  14         5      5
                  15         1      1
extra_word_count  0        452    452
                  1       1380   1380
                  2       2129   2129
                  3       2694   2694
                  4       2719   2719
                  5       2423   2423
                  6       2040   2040
                  7       1421   1421
                  8        923    923
                  9        388    388
                  10       256    256
                  11        93     93
                  12        52     52
                  13        23     23
                  14         6      6
                  15         1      1
part_word_count   1        349    349
                  2       1076   1076
                  3       1793   1793
                  4       2553   2553
                  5       2541   2541
                  6       2473   2473
                  7       2218   2218
                  8       1584   1584
                  9       1248   1248
                  10       562    562
                  11       357    357
                  12       122    122
                  13        82     82
                  14        22     22
                  15        18     18
                  16         2      2

================================================================================

Statistics after processing 17500 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9823  0.9927  0.9933   11432  11553  11560  11638
                  2       0.9729  0.9916  0.9931    4766   4858   4865   4899
                  3       0.9704  0.9870  0.9870     821    835    835    846
                  4       0.9340  0.9623  0.9717      99    102    103    106
                  5       0.9091  1.0000  1.0000      10     11     11     11
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9283  0.9653  0.9720     829    862    868    893
                  1       0.9714  0.9906  0.9906    1870   1907   1907   1925
                  2       0.9719  0.9909  0.9921    2457   2505   2508   2528
                  3       0.9827  0.9929  0.9933    2778   2807   2808   2827
                  4       0.9836  0.9947  0.9950    2574   2603   2604   2617
                  5       0.9864  0.9941  0.9946    2179   2196   2197   2209
                  6       0.9807  0.9934  0.9950    1777   1800   1803   1812
                  7       0.9899  0.9950  0.9950    1177   1183   1183   1189
                  8       0.9877  0.9975  0.9975     800    808    808    810
                  9       0.9937  0.9968  0.9968     314    315    315    316
                  10      0.9955  0.9955  0.9955     221    221    221    222
                  11      1.0000  1.0000  1.0000      81     81     81     81
                  12      1.0000  1.0000  1.0000      47     47     47     47
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9247  0.9548  0.9677     430    444    450    465
                  1       0.9683  0.9915  0.9915    1374   1407   1407   1419
                  2       0.9695  0.9895  0.9900    2128   2172   2173   2195
                  3       0.9794  0.9917  0.9920    2709   2743   2744   2766
                  4       0.9839  0.9954  0.9957    2755   2787   2788   2800
                  5       0.9831  0.9920  0.9928    2447   2469   2471   2489
                  6       0.9782  0.9924  0.9943    2064   2094   2098   2110
                  7       0.9884  0.9973  0.9973    1454   1467   1467   1471
                  8       0.9872  0.9957  0.9957     928    936    936    940
                  9       0.9901  0.9926  0.9926     399    400    400    403
                  10      0.9924  0.9924  0.9924     262    262    262    264
                  11      1.0000  1.0000  1.0000      94     94     94     94
                  12      1.0000  1.0000  1.0000      54     54     54     54
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9162  0.9497  0.9665     328    340    346    358
                  2       0.9739  0.9910  0.9910    1080   1099   1099   1109
                  3       0.9762  0.9897  0.9902    1801   1826   1827   1845
                  4       0.9729  0.9916  0.9916    2551   2600   2600   2622
                  5       0.9805  0.9931  0.9939    2565   2598   2600   2616
                  6       0.9839  0.9941  0.9941    2504   2530   2530   2545
                  7       0.9772  0.9908  0.9930    2225   2256   2261   2277
                  8       0.9848  0.9951  0.9957    1618   1635   1636   1643
                  9       0.9845  0.9977  0.9977    1269   1286   1286   1289
                  10      0.9965  0.9965  0.9965     575    575    575    577
                  11      0.9918  0.9946  0.9946     365    366    366    368
                  12      0.9760  0.9840  0.9840     122    123    123    125
                  13      0.9880  0.9880  0.9880      82     82     82     83
                  14      1.0000  1.0000  1.0000      23     23     23     23
                  15      1.0000  1.0000  1.0000      18     18     18     18
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      11638  11638
                  2       4899   4899
                  3        846    846
                  4        106    106
                  5         11     11
extra_word_added -1          3      3
                  0        893    893
                  1       1925   1925
                  2       2528   2528
                  3       2827   2827
                  4       2617   2617
                  5       2209   2209
                  6       1812   1812
                  7       1189   1189
                  8        810    810
                  9        316    316
                  10       222    222
                  11        81     81
                  12        47     47
                  13        15     15
                  14         5      5
                  15         1      1
extra_word_count  0        465    465
                  1       1419   1419
                  2       2195   2195
                  3       2766   2766
                  4       2800   2800
                  5       2489   2489
                  6       2110   2110
                  7       1471   1471
                  8        940    940
                  9        403    403
                  10       264    264
                  11        94     94
                  12        54     54
                  13        23     23
                  14         6      6
                  15         1      1
part_word_count   1        358    358
                  2       1109   1109
                  3       1845   1845
                  4       2622   2622
                  5       2616   2616
                  6       2545   2545
                  7       2277   2277
                  8       1643   1643
                  9       1289   1289
                  10       577    577
                  11       368    368
                  12       125    125
                  13        83     83
                  14        23     23
                  15        18     18
                  16         2      2

================================================================================

Statistics after processing 18000 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9821  0.9928  0.9934   11757  11885  11892  11971
                  2       0.9728  0.9915  0.9931    4907   5001   5009   5044
                  3       0.9699  0.9873  0.9873     838    853    853    864
                  4       0.9364  0.9636  0.9727     103    106    107    110
                  5       0.9091  1.0000  1.0000      10     11     11     11
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9305  0.9663  0.9729     857    890    896    921
                  1       0.9711  0.9909  0.9909    1916   1955   1955   1973
                  2       0.9720  0.9908  0.9919    2533   2582   2585   2606
                  3       0.9825  0.9931  0.9935    2857   2888   2889   2908
                  4       0.9833  0.9944  0.9952    2645   2675   2677   2690
                  5       0.9860  0.9943  0.9947    2247   2266   2267   2279
                  6       0.9806  0.9935  0.9952    1822   1846   1849   1858
                  7       0.9894  0.9943  0.9943    1209   1215   1215   1222
                  8       0.9867  0.9976  0.9976     819    828    828    830
                  9       0.9939  0.9970  0.9970     326    327    327    328
                  10      0.9957  0.9957  0.9957     229    229    229    230
                  11      1.0000  1.0000  1.0000      83     83     83     83
                  12      1.0000  1.0000  1.0000      48     48     48     48
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9274  0.9564  0.9689     447    461    467    482
                  1       0.9684  0.9918  0.9918    1411   1445   1445   1457
                  2       0.9695  0.9894  0.9898    2194   2239   2240   2263
                  3       0.9793  0.9919  0.9923    2790   2826   2827   2849
                  4       0.9840  0.9951  0.9958    2827   2859   2861   2873
                  5       0.9820  0.9922  0.9930    2515   2541   2543   2561
                  6       0.9783  0.9926  0.9945    2120   2151   2155   2167
                  7       0.9881  0.9967  0.9967    1493   1506   1506   1511
                  8       0.9865  0.9959  0.9959     952    961    961    965
                  9       0.9904  0.9928  0.9928     414    415    415    418
                  10      0.9927  0.9927  0.9927     271    271    271    273
                  11      1.0000  1.0000  1.0000      96     96     96     96
                  12      1.0000  1.0000  1.0000      55     55     55     55
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9191  0.9515  0.9677     341    353    359    371
                  2       0.9737  0.9912  0.9912    1110   1130   1130   1140
                  3       0.9764  0.9900  0.9906    1864   1890   1891   1909
                  4       0.9724  0.9914  0.9914    2612   2663   2663   2686
                  5       0.9807  0.9933  0.9941    2645   2679   2681   2697
                  6       0.9839  0.9943  0.9943    2574   2601   2601   2616
                  7       0.9768  0.9905  0.9931    2274   2306   2312   2328
                  8       0.9841  0.9947  0.9953    1669   1687   1688   1696
                  9       0.9834  0.9977  0.9977    1300   1319   1319   1322
                  10      0.9966  0.9966  0.9966     595    595    595    597
                  11      0.9921  0.9948  0.9948     379    380    380    382
                  12      0.9767  0.9845  0.9845     126    127    127    129
                  13      0.9881  0.9881  0.9881      83     83     83     84
                  14      1.0000  1.0000  1.0000      23     23     23     23
                  15      1.0000  1.0000  1.0000      18     18     18     18
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      11971  11971
                  2       5044   5044
                  3        864    864
                  4        110    110
                  5         11     11
extra_word_added -1          3      3
                  0        921    921
                  1       1973   1973
                  2       2606   2606
                  3       2908   2908
                  4       2690   2690
                  5       2279   2279
                  6       1858   1858
                  7       1222   1222
                  8        830    830
                  9        328    328
                  10       230    230
                  11        83     83
                  12        48     48
                  13        15     15
                  14         5      5
                  15         1      1
extra_word_count  0        482    482
                  1       1457   1457
                  2       2263   2263
                  3       2849   2849
                  4       2873   2873
                  5       2561   2561
                  6       2167   2167
                  7       1511   1511
                  8        965    965
                  9        418    418
                  10       273    273
                  11        96     96
                  12        55     55
                  13        23     23
                  14         6      6
                  15         1      1
part_word_count   1        371    371
                  2       1140   1140
                  3       1909   1909
                  4       2686   2686
                  5       2697   2697
                  6       2616   2616
                  7       2328   2328
                  8       1696   1696
                  9       1322   1322
                  10       597    597
                  11       382    382
                  12       129    129
                  13        84     84
                  14        23     23
                  15        18     18
                  16         2      2

================================================================================

Statistics after processing 18500 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9822  0.9928  0.9934   12088  12219  12226  12307
                  2       0.9726  0.9915  0.9930    5033   5131   5139   5175
                  3       0.9676  0.9866  0.9866     865    882    882    894
                  4       0.9381  0.9646  0.9735     106    109    110    113
                  5       0.9091  1.0000  1.0000      10     11     11     11
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9290  0.9661  0.9724     876    911    917    943
                  1       0.9710  0.9911  0.9911    1973   2014   2014   2032
                  2       0.9714  0.9900  0.9911    2618   2668   2671   2695
                  3       0.9819  0.9933  0.9936    2934   2968   2969   2988
                  4       0.9833  0.9946  0.9953    2713   2744   2746   2759
                  5       0.9863  0.9944  0.9948    2296   2315   2316   2328
                  6       0.9812  0.9937  0.9953    1875   1899   1902   1911
                  7       0.9896  0.9944  0.9944    1237   1243   1243   1250
                  8       0.9872  0.9977  0.9977     847    856    856    858
                  9       0.9941  0.9971  0.9971     337    338    338    339
                  10      0.9958  0.9958  0.9958     235    235    235    236
                  11      1.0000  1.0000  1.0000      85     85     85     85
                  12      1.0000  1.0000  1.0000      52     52     52     52
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       1      1      1      1
extra_word_count  0       0.9253  0.9556  0.9677     458    473    479    495
                  1       0.9680  0.9920  0.9920    1453   1489   1489   1501
                  2       0.9696  0.9893  0.9897    2265   2311   2312   2336
                  3       0.9792  0.9921  0.9925    2867   2905   2906   2928
                  4       0.9834  0.9953  0.9959    2902   2937   2939   2951
                  5       0.9824  0.9924  0.9931    2572   2598   2600   2618
                  6       0.9785  0.9924  0.9942    2181   2212   2216   2229
                  7       0.9877  0.9961  0.9961    1531   1544   1544   1550
                  8       0.9869  0.9960  0.9960     981    990    990    994
                  9       0.9907  0.9930  0.9930     426    427    427    430
                  10      0.9929  0.9929  0.9929     279    279    279    281
                  11      1.0000  1.0000  1.0000      98     98     98     98
                  12      1.0000  1.0000  1.0000      59     59     59     59
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       1      1      1      1
part_word_count   1       0.9162  0.9503  0.9660     350    363    369    382
                  2       0.9735  0.9915  0.9915    1141   1162   1162   1172
                  3       0.9766  0.9903  0.9908    1921   1948   1949   1967
                  4       0.9722  0.9913  0.9913    2692   2745   2745   2769
                  5       0.9805  0.9935  0.9942    2711   2747   2749   2765
                  6       0.9839  0.9944  0.9944    2634   2662   2662   2677
                  7       0.9770  0.9908  0.9933    2335   2368   2374   2390
                  8       0.9845  0.9948  0.9954    1717   1735   1736   1744
                  9       0.9831  0.9971  0.9971    1337   1356   1356   1360
                  10      0.9951  0.9951  0.9951     613    613    613    616
                  11      0.9924  0.9949  0.9949     391    392    392    394
                  12      0.9774  0.9850  0.9850     130    131    131    133
                  13      0.9886  0.9886  0.9886      87     87     87     88
                  14      1.0000  1.0000  1.0000      23     23     23     23
                  15      1.0000  1.0000  1.0000      18     18     18     18
                  16      1.0000  1.0000  1.0000       2      2      2      2


metric                    top3   top5
category         subcat
edit_count        1      12307  12307
                  2       5175   5175
                  3        894    894
                  4        113    113
                  5         11     11
extra_word_added -1          3      3
                  0        943    943
                  1       2032   2032
                  2       2695   2695
                  3       2988   2988
                  4       2759   2759
                  5       2328   2328
                  6       1911   1911
                  7       1250   1250
                  8        858    858
                  9        339    339
                  10       236    236
                  11        85     85
                  12        52     52
                  13        15     15
                  14         5      5
                  15         1      1
extra_word_count  0        495    495
                  1       1501   1501
                  2       2336   2336
                  3       2928   2928
                  4       2951   2951
                  5       2618   2618
                  6       2229   2229
                  7       1550   1550
                  8        994    994
                  9        430    430
                  10       281    281
                  11        98     98
                  12        59     59
                  13        23     23
                  14         6      6
                  15         1      1
part_word_count   1        382    382
                  2       1172   1172
                  3       1967   1967
                  4       2769   2769
                  5       2765   2765
                  6       2677   2677
                  7       2390   2390
                  8       1744   1744
                  9       1360   1360
                  10       616    616
                  11       394    394
                  12       133    133
                  13        88     88
                  14        23     23
                  15        18     18
                  16         2      2

================================================================================

Statistics after processing 19000 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9820  0.9930  0.9935   12400  12538  12545  12627
                  2       0.9731  0.9917  0.9932    5178   5277   5285   5321
                  3       0.9654  0.9870  0.9870     893    913    913    925
                  4       0.9391  0.9652  0.9739     108    111    112    115
                  5       0.9091  1.0000  1.0000      10     11     11     11
                  6       1.0000  1.0000  1.0000       1      1      1      1
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9295  0.9668  0.9731     897    933    939    965
                  1       0.9705  0.9914  0.9914    2038   2082   2082   2100
                  2       0.9721  0.9902  0.9913    2684   2734   2737   2761
                  3       0.9821  0.9932  0.9935    3011   3045   3046   3066
                  4       0.9831  0.9947  0.9954    2795   2828   2830   2843
                  5       0.9854  0.9946  0.9950    2355   2377   2378   2390
                  6       0.9816  0.9939  0.9954    1925   1949   1952   1961
                  7       0.9884  0.9946  0.9946    1274   1282   1282   1289
                  8       0.9874  0.9977  0.9977     861    870    870    872
                  9       0.9942  0.9971  0.9971     342    343    343    344
                  10      0.9958  0.9958  0.9958     238    238    238    239
                  11      1.0000  1.0000  1.0000      88     88     88     88
                  12      1.0000  1.0000  1.0000      57     57     57     57
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       2      2      2      2
extra_word_count  0       0.9250  0.9566  0.9684     469    485    491    507
                  1       0.9677  0.9922  0.9922    1498   1536   1536   1548
                  2       0.9699  0.9896  0.9900    2322   2369   2370   2394
                  3       0.9794  0.9920  0.9923    2943   2981   2982   3005
                  4       0.9832  0.9954  0.9961    2987   3024   3026   3038
                  5       0.9818  0.9926  0.9933    2642   2671   2673   2691
                  6       0.9790  0.9926  0.9943    2239   2270   2274   2287
                  7       0.9869  0.9962  0.9962    1576   1591   1591   1597
                  8       0.9871  0.9960  0.9960     998   1007   1007   1011
                  9       0.9909  0.9932  0.9932     434    435    435    438
                  10      0.9931  0.9931  0.9931     286    286    286    288
                  11      1.0000  1.0000  1.0000     101    101    101    101
                  12      1.0000  1.0000  1.0000      64     64     64     64
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       2      2      2      2
part_word_count   1       0.9160  0.9517  0.9669     360    374    380    393
                  2       0.9743  0.9917  0.9917    1176   1197   1197   1207
                  3       0.9771  0.9906  0.9910    1965   1992   1993   2011
                  4       0.9715  0.9912  0.9912    2763   2819   2819   2844
                  5       0.9803  0.9937  0.9944    2793   2831   2833   2849
                  6       0.9837  0.9946  0.9946    2710   2740   2740   2755
                  7       0.9772  0.9910  0.9935    2397   2431   2437   2453
                  8       0.9839  0.9950  0.9955    1767   1787   1788   1796
                  9       0.9834  0.9971  0.9971    1363   1382   1382   1386
                  10      0.9952  0.9952  0.9952     624    624    624    627
                  11      0.9925  0.9950  0.9950     398    399    399    401
                  12      0.9784  0.9856  0.9856     136    137    137    139
                  13      0.9894  0.9894  0.9894      93     93     93     94
                  14      1.0000  1.0000  1.0000      24     24     24     24
                  15      1.0000  1.0000  1.0000      18     18     18     18
                  16      1.0000  1.0000  1.0000       3      3      3      3


metric                    top3   top5
category         subcat
edit_count        1      12627  12627
                  2       5321   5321
                  3        925    925
                  4        115    115
                  5         11     11
                  6          1      1
extra_word_added -1          3      3
                  0        965    965
                  1       2100   2100
                  2       2761   2761
                  3       3066   3066
                  4       2843   2843
                  5       2390   2390
                  6       1961   1961
                  7       1289   1289
                  8        872    872
                  9        344    344
                  10       239    239
                  11        88     88
                  12        57     57
                  13        15     15
                  14         5      5
                  15         2      2
extra_word_count  0        507    507
                  1       1548   1548
                  2       2394   2394
                  3       3005   3005
                  4       3038   3038
                  5       2691   2691
                  6       2287   2287
                  7       1597   1597
                  8       1011   1011
                  9        438    438
                  10       288    288
                  11       101    101
                  12        64     64
                  13        23     23
                  14         6      6
                  15         2      2
part_word_count   1        393    393
                  2       1207   1207
                  3       2011   2011
                  4       2844   2844
                  5       2849   2849
                  6       2755   2755
                  7       2453   2453
                  8       1796   1796
                  9       1386   1386
                  10       627    627
                  11       401    401
                  12       139    139
                  13        94     94
                  14        24     24
                  15        18     18
                  16         3      3

================================================================================

Statistics after processing 19500 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9819  0.9929  0.9935   12719  12861  12869  12953
                  2       0.9728  0.9916  0.9931    5321   5424   5432   5470
                  3       0.9662  0.9873  0.9873     915    935    935    947
                  4       0.9407  0.9661  0.9746     111    114    115    118
                  5       0.9091  1.0000  1.0000      10     11     11     11
                  6       1.0000  1.0000  1.0000       1      1      1      1
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9282  0.9666  0.9737     918    956    963    989
                  1       0.9707  0.9912  0.9912    2084   2128   2128   2147
                  2       0.9715  0.9901  0.9912    2758   2811   2814   2839
                  3       0.9820  0.9930  0.9934    3101   3136   3137   3158
                  4       0.9832  0.9945  0.9952    2876   2909   2911   2925
                  5       0.9857  0.9947  0.9951    2409   2431   2432   2444
                  6       0.9822  0.9941  0.9955    1981   2005   2008   2017
                  7       0.9879  0.9947  0.9947    1303   1312   1312   1319
                  8       0.9865  0.9978  0.9978     877    887    887    889
                  9       0.9943  0.9972  0.9972     350    351    351    352
                  10      0.9960  0.9960  0.9960     246    246    246    247
                  11      1.0000  1.0000  1.0000      91     91     91     91
                  12      1.0000  1.0000  1.0000      58     58     58     58
                  13      1.0000  1.0000  1.0000      15     15     15     15
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       2      2      2      2
extra_word_count  0       0.9232  0.9559  0.9693     481    498    505    521
                  1       0.9678  0.9918  0.9918    1531   1569   1569   1582
                  2       0.9691  0.9894  0.9898    2387   2437   2438   2463
                  3       0.9793  0.9919  0.9922    3025   3064   3065   3089
                  4       0.9830  0.9952  0.9958    3070   3108   3110   3123
                  5       0.9822  0.9927  0.9935    2704   2733   2735   2753
                  6       0.9796  0.9928  0.9945    2304   2335   2339   2352
                  7       0.9865  0.9963  0.9963    1610   1626   1626   1632
                  8       0.9865  0.9961  0.9961    1022   1032   1032   1036
                  9       0.9911  0.9933  0.9933     447    448    448    451
                  10      0.9933  0.9933  0.9933     295    295    295    297
                  11      1.0000  1.0000  1.0000     104    104    104    104
                  12      1.0000  1.0000  1.0000      66     66     66     66
                  13      1.0000  1.0000  1.0000      23     23     23     23
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       2      2      2      2
part_word_count   1       0.9129  0.9502  0.9677     367    382    389    402
                  2       0.9741  0.9911  0.9911    1205   1226   1226   1237
                  3       0.9768  0.9903  0.9908    2023   2051   2052   2071
                  4       0.9713  0.9911  0.9911    2839   2897   2897   2923
                  5       0.9802  0.9935  0.9942    2873   2912   2914   2931
                  6       0.9840  0.9947  0.9947    2770   2800   2800   2815
                  7       0.9778  0.9913  0.9937    2466   2500   2506   2522
                  8       0.9842  0.9951  0.9956    1805   1825   1826   1834
                  9       0.9817  0.9972  0.9972    1394   1416   1416   1420
                  10      0.9954  0.9954  0.9954     643    643    643    646
                  11      0.9928  0.9952  0.9952     411    412    412    414
                  12      0.9790  0.9860  0.9860     140    141    141    143
                  13      0.9895  0.9895  0.9895      94     94     94     95
                  14      1.0000  1.0000  1.0000      25     25     25     25
                  15      1.0000  1.0000  1.0000      19     19     19     19
                  16      1.0000  1.0000  1.0000       3      3      3      3


metric                    top3   top5
category         subcat
edit_count        1      12953  12953
                  2       5470   5470
                  3        947    947
                  4        118    118
                  5         11     11
                  6          1      1
extra_word_added -1          3      3
                  0        989    989
                  1       2147   2147
                  2       2839   2839
                  3       3158   3158
                  4       2925   2925
                  5       2444   2444
                  6       2017   2017
                  7       1319   1319
                  8        889    889
                  9        352    352
                  10       247    247
                  11        91     91
                  12        58     58
                  13        15     15
                  14         5      5
                  15         2      2
extra_word_count  0        521    521
                  1       1582   1582
                  2       2463   2463
                  3       3089   3089
                  4       3123   3123
                  5       2753   2753
                  6       2352   2352
                  7       1632   1632
                  8       1036   1036
                  9        451    451
                  10       297    297
                  11       104    104
                  12        66     66
                  13        23     23
                  14         6      6
                  15         2      2
part_word_count   1        402    402
                  2       1237   1237
                  3       2071   2071
                  4       2923   2923
                  5       2931   2931
                  6       2815   2815
                  7       2522   2522
                  8       1834   1834
                  9       1420   1420
                  10       646    646
                  11       414    414
                  12       143    143
                  13        95     95
                  14        25     25
                  15        19     19
                  16         3      3

================================================================================

Statistics after processing 20000 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9819  0.9929  0.9935   13048  13194  13202  13289
                  2       0.9720  0.9914  0.9929    5448   5557   5565   5605
                  3       0.9672  0.9877  0.9877     943    963    963    975
                  4       0.9412  0.9664  0.9748     112    115    116    119
                  5       0.9091  1.0000  1.0000      10     11     11     11
                  6       1.0000  1.0000  1.0000       1      1      1      1
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9289  0.9674  0.9743     941    980    987   1013
                  1       0.9700  0.9909  0.9909    2137   2183   2183   2203
                  2       0.9710  0.9900  0.9910    2817   2872   2875   2901
                  3       0.9821  0.9932  0.9935    3176   3212   3213   3234
                  4       0.9833  0.9943  0.9950    2950   2983   2985   3000
                  5       0.9849  0.9944  0.9948    2480   2504   2505   2518
                  6       0.9821  0.9942  0.9956    2028   2053   2056   2065
                  7       0.9874  0.9948  0.9948    1337   1347   1347   1354
                  8       0.9857  0.9967  0.9967     897    907    907    910
                  9       0.9945  0.9972  0.9972     359    360    360    361
                  10      0.9961  0.9961  0.9961     258    258    258    259
                  11      1.0000  1.0000  1.0000      95     95     95     95
                  12      1.0000  1.0000  1.0000      61     61     61     61
                  13      1.0000  1.0000  1.0000      16     16     16     16
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       2      2      2      2
extra_word_count  0       0.9231  0.9568  0.9700     492    510    517    533
                  1       0.9673  0.9914  0.9914    1567   1606   1606   1620
                  2       0.9691  0.9893  0.9897    2444   2495   2496   2522
                  3       0.9795  0.9921  0.9924    3102   3142   3143   3167
                  4       0.9834  0.9953  0.9959    3139   3177   3179   3192
                  5       0.9813  0.9926  0.9933    2780   2812   2814   2833
                  6       0.9797  0.9930  0.9946    2367   2399   2403   2416
                  7       0.9851  0.9958  0.9958    1651   1669   1669   1676
                  8       0.9858  0.9953  0.9953    1044   1054   1054   1059
                  9       0.9913  0.9935  0.9935     457    458    458    461
                  10      0.9936  0.9936  0.9936     310    310    310    312
                  11      1.0000  1.0000  1.0000     108    108    108    108
                  12      1.0000  1.0000  1.0000      69     69     69     69
                  13      1.0000  1.0000  1.0000      24     24     24     24
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       2      2      2      2
part_word_count   1       0.9124  0.9513  0.9684     375    391    398    411
                  2       0.9732  0.9905  0.9905    1235   1257   1257   1269
                  3       0.9768  0.9901  0.9905    2064   2092   2093   2113
                  4       0.9714  0.9914  0.9914    2921   2981   2981   3007
                  5       0.9806  0.9936  0.9943    2930   2969   2971   2988
                  6       0.9840  0.9948  0.9948    2836   2867   2867   2882
                  7       0.9769  0.9912  0.9935    2539   2576   2582   2599
                  8       0.9836  0.9947  0.9952    1860   1881   1882   1891
                  9       0.9815  0.9973  0.9973    1432   1455   1455   1459
                  10      0.9939  0.9939  0.9939     652    652    652    656
                  11      0.9931  0.9954  0.9954     429    430    430    432
                  12      0.9795  0.9863  0.9863     143    144    144    146
                  13      0.9899  0.9899  0.9899      98     98     98     99
                  14      1.0000  1.0000  1.0000      25     25     25     25
                  15      1.0000  1.0000  1.0000      20     20     20     20
                  16      1.0000  1.0000  1.0000       3      3      3      3


metric                    top3   top5
category         subcat
edit_count        1      13289  13289
                  2       5605   5605
                  3        975    975
                  4        119    119
                  5         11     11
                  6          1      1
extra_word_added -1          3      3
                  0       1013   1013
                  1       2203   2203
                  2       2901   2901
                  3       3234   3234
                  4       3000   3000
                  5       2518   2518
                  6       2065   2065
                  7       1354   1354
                  8        910    910
                  9        361    361
                  10       259    259
                  11        95     95
                  12        61     61
                  13        16     16
                  14         5      5
                  15         2      2
extra_word_count  0        533    533
                  1       1620   1620
                  2       2522   2522
                  3       3167   3167
                  4       3192   3192
                  5       2833   2833
                  6       2416   2416
                  7       1676   1676
                  8       1059   1059
                  9        461    461
                  10       312    312
                  11       108    108
                  12        69     69
                  13        24     24
                  14         6      6
                  15         2      2
part_word_count   1        411    411
                  2       1269   1269
                  3       2113   2113
                  4       3007   3007
                  5       2988   2988
                  6       2882   2882
                  7       2599   2599
                  8       1891   1891
                  9       1459   1459
                  10       656    656
                  11       432    432
                  12       146    146
                  13        99     99
                  14        25     25
                  15        20     20
                  16         3      3

================================================================================
Saved detailed statistics to ./drive/MyDrive/Colab Notebooks/vr-txt-corr/saved_models/text correction (unbounded triplets cursor strategies)/correction_normal_multiple_point_uniform_mask_cursor-relax10/stats_triplets-m-relax10.csv

Final Statistics:

Statistics after processing 20880 samples:
================================================================================

                        accuracy                 matches                total  \
metric                      top1    top3    top5    top1   top3   top5   top1
category         subcat
edit_count        1       0.9819  0.9929  0.9935   13114  13261  13269  13356
                  2       0.9722  0.9915  0.9929    5484   5593   5601   5641
                  3       0.9675  0.9878  0.9878     953    973    973    985
                  4       0.9412  0.9664  0.9748     112    115    116    119
                  5       0.9167  1.0000  1.0000      11     12     12     12
                  6       1.0000  1.0000  1.0000       1      1      1      1
extra_word_added -1       1.0000  1.0000  1.0000       3      3      3      3
                  0       0.9282  0.9676  0.9744     944    984    991   1017
                  1       0.9702  0.9910  0.9910    2149   2195   2195   2215
                  2       0.9713  0.9901  0.9911    2840   2895   2898   2924
                  3       0.9821  0.9932  0.9935    3190   3226   3227   3248
                  4       0.9834  0.9944  0.9950    2962   2995   2997   3012
                  5       0.9850  0.9945  0.9949    2501   2525   2526   2539
                  6       0.9822  0.9942  0.9957    2036   2061   2064   2073
                  7       0.9875  0.9949  0.9949    1345   1355   1355   1362
                  8       0.9858  0.9967  0.9967     903    913    913    916
                  9       0.9946  0.9973  0.9973     365    366    366    367
                  10      0.9961  0.9961  0.9961     258    258    258    259
                  11      1.0000  1.0000  1.0000      95     95     95     95
                  12      1.0000  1.0000  1.0000      61     61     61     61
                  13      1.0000  1.0000  1.0000      16     16     16     16
                  14      1.0000  1.0000  1.0000       5      5      5      5
                  15      1.0000  1.0000  1.0000       2      2      2      2
extra_word_count  0       0.9213  0.9569  0.9700     492    511    518    534
                  1       0.9674  0.9914  0.9914    1573   1612   1612   1626
                  2       0.9692  0.9894  0.9897    2458   2509   2510   2536
                  3       0.9796  0.9922  0.9925    3120   3160   3161   3185
                  4       0.9835  0.9953  0.9959    3154   3192   3194   3207
                  5       0.9814  0.9926  0.9933    2804   2836   2838   2857
                  6       0.9798  0.9930  0.9946    2377   2409   2413   2426
                  7       0.9852  0.9958  0.9958    1661   1679   1679   1686
                  8       0.9860  0.9953  0.9953    1054   1064   1064   1069
                  9       0.9914  0.9936  0.9936     463    464    464    467
                  10      0.9936  0.9936  0.9936     310    310    310    312
                  11      1.0000  1.0000  1.0000     108    108    108    108
                  12      1.0000  1.0000  1.0000      69     69     69     69
                  13      1.0000  1.0000  1.0000      24     24     24     24
                  14      1.0000  1.0000  1.0000       6      6      6      6
                  15      1.0000  1.0000  1.0000       2      2      2      2
part_word_count   1       0.9102  0.9515  0.9684     375    392    399    412
                  2       0.9733  0.9906  0.9906    1241   1263   1263   1275
                  3       0.9769  0.9901  0.9906    2076   2104   2105   2125
                  4       0.9715  0.9914  0.9914    2931   2991   2991   3017
                  5       0.9807  0.9937  0.9943    2947   2986   2988   3005
                  6       0.9842  0.9948  0.9948    2861   2892   2892   2907
                  7       0.9770  0.9912  0.9935    2550   2587   2593   2610
                  8       0.9837  0.9947  0.9953    1871   1892   1893   1902
                  9       0.9816  0.9973  0.9973    1442   1465   1465   1469
                  10      0.9940  0.9940  0.9940     660    660    660    664
                  11      0.9931  0.9954  0.9954     432    433    433    435
                  12      0.9795  0.9863  0.9863     143    144    144    146
                  13      0.9899  0.9899  0.9899      98     98     98     99
                  14      1.0000  1.0000  1.0000      25     25     25     25
                  15      1.0000  1.0000  1.0000      20     20     20     20
                  16      1.0000  1.0000  1.0000       3      3      3      3


metric                    top3   top5
category         subcat
edit_count        1      13356  13356
                  2       5641   5641
                  3        985    985
                  4        119    119
                  5         12     12
                  6          1      1
extra_word_added -1          3      3
                  0       1017   1017
                  1       2215   2215
                  2       2924   2924
                  3       3248   3248
                  4       3012   3012
                  5       2539   2539
                  6       2073   2073
                  7       1362   1362
                  8        916    916
                  9        367    367
                  10       259    259
                  11        95     95
                  12        61     61
                  13        16     16
                  14         5      5
                  15         2      2
extra_word_count  0        534    534
                  1       1626   1626
                  2       2536   2536
                  3       3185   3185
                  4       3207   3207
                  5       2857   2857
                  6       2426   2426
                  7       1686   1686
                  8       1069   1069
                  9        467    467
                  10       312    312
                  11       108    108
                  12        69     69
                  13        24     24
                  14         6      6
                  15         2      2
part_word_count   1        412    412
                  2       1275   1275
                  3       2125   2125
                  4       3017   3017
                  5       3005   3005
                  6       2907   2907
                  7       2610   2610
                  8       1902   1902
                  9       1469   1469
                  10       664    664
                  11       435    435
                  12       146    146
                  13        99     99
                  14        25     25
                  15        20     20
                  16         3      3

================================================================================

test evaluation:
{'test_sample_size': 20114, 'test_loss': 0.0031918638851493597, 'test_cer_unfiltered': 0.00031731556194199704, 'test_cer_filtered': 0.0002612048833059122, 'test_tkacc_unfiltered/t1acc': 0.9719598289748433, 'test_tkacc_unfiltered/t3acc': 0.9888634781744059, 'test_tkacc_unfiltered/t5acc': 0.9910012926319977, 'test_tkacc_filtered/t1acc': 0.9781744058864472, 'test_tkacc_filtered/t3acc': 0.9920950581684399, 'test_tkacc_filtered/t5acc': 0.992940240628418, 'test_runtime': 23566.3545, 'test_samples_per_second': 0.886, 'test_steps_per_second': 0.222, 'eval_bloss': None}